<div>
    <?php if($order == null): ?>
    <h1>There is no order to show bank transfer details for</h1>
    <p>Go to <a href="<?php echo $this->url('product'); ?>">products</a> and 
        choose the items you want.</p>
    <?php else: ?>
    <p>Please transfer the amount by SEPA bank transfer to the following account:</p>
    <p>To <strong>make the orgas life easy</strong>, please add the reason for 
        payment: <strong><?php echo $order->getCode()->getValue(); ?></strong></p>
    <table class="table">
        <tr>
            <td>Owner</td>
            <td>STICHTING EUROPEAN JUGGLING ASSOCIATION</td>
        </tr>
        <tr>
            <td>IBAN</td>
            <td>NL84 INGB 0007 8721 92</td>
        </tr>
        <tr>
            <td>BIC</td>
            <td>INGBNL2A</td>
        </tr>
        <tr>
            <td>Amount</td>
            <td><?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></td>
        </tr>
        <tr>
            <td>reason for payment</td>
            <td><?php echo $order->getCode()->getValue(); ?></td>
        </tr>
    </table>
    <div>
        <p>We sent this information to your email address: <strong><?php echo $order->getPurchaser()->getEmail(); ?></strong></p>
        <h3>You can request this information again</h3>
        <p>All you need to do is:</p>
        <ul>
            <li><strong>Setup a password</strong> for your account with your email address <?php echo $order->getPurchaser()->getEmail(); ?>.</li>
            <li><strong>Login</strong> to your account.</li>
            <li>View your <strong>order detail</strong>.</li>
            <li>View your <strong>payment detail</strong>.</li>
        </ul>
    </div>
    <?php endif; ?>
</div>