<div>
    <?php if($order == null): ?>
    <h1>There is no order to show bank transfer details for</h1>
    <p>Go to <a href="<?php echo $this->url('product'); ?>">products</a> and 
        choose the items you want.</p>
    <?php else: ?>
    <p><?php echo $this->translate('Please transfer the amount by SEPA bank transfer to the following account:'); ?></p>
    <table class="table">
        <tr>
            <td><?php echo $this->translate('Owner'); ?></td>
            <td><?php echo $this->config()['ERS\SEPA']['owner']; ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('IBAN'); ?></td>
            <td><?php echo $this->niceiban($this->config()['ERS\SEPA']['iban']); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('BIC'); ?></td>
            <td><?php echo $this->config()['ERS\SEPA']['bic']; ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Bank'); ?></td>
            <td><?php echo $this->config()['ERS\SEPA']['bank']; ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Country'); ?></td>
            <td><?php echo $this->config()['ERS\SEPA']['country']; ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Amount'); ?></td>
            <td><?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Reason for payment'); ?></td>
            <td><?php echo $order->getCode()->getValue(); ?></td>
        </tr>
    </table>
    
    <h4><?php echo $this->translate('Owner address'); ?></h4>
    <p><?php 
        if($this->config()['ERS\SEPA']['owner_address_line1']): echo $this->config()['ERS\SEPA']['owner_address_line1'].'<br />'; endif;
        if($this->config()['ERS\SEPA']['owner_address_line2']): echo $this->config()['ERS\SEPA']['owner_address_line2'].'<br />'; endif;
        if($this->config()['ERS\SEPA']['owner_address_line3']): echo $this->config()['ERS\SEPA']['owner_address_line3'].'<br />'; endif;
        if($this->config()['ERS\SEPA']['owner_address_line4']): echo $this->config()['ERS\SEPA']['owner_address_line4'].'<br />'; endif;
        ?></p>
    
    <h4><?php echo $this->translate('Bank address'); ?></h4>
    <p><?php 
        if($this->config()['ERS\SEPA']['bank_address_line1']): echo $this->config()['ERS\SEPA']['bank_address_line1'].'<br />'; endif;
        if($this->config()['ERS\SEPA']['bank_address_line2']): echo $this->config()['ERS\SEPA']['bank_address_line2'].'<br />'; endif;
        if($this->config()['ERS\SEPA']['bank_address_line3']): echo $this->config()['ERS\SEPA']['bank_address_line3'].'<br />'; endif;
        if($this->config()['ERS\SEPA']['bank_address_line4']): echo $this->config()['ERS\SEPA']['bank_address_line4'].'<br />'; endif;
        ?></p>

    <p>
        <?php printf($this->translate('Make sure to fill in this reason for payment <strong>%s</strong> as the reference for the transfer. Otherwise we won\'t be able to match your payment and your order can\'t be processed.'), $order->getCode()->getValue()); ?>
    </p>

    <?php endif; ?>
</div>