<div class='row nav-checkout'>
    <?php 
    $count = 1;
    foreach ($this->container as $page):
        /* @var $page Zend\Navigation\Page\Mvc */
        // when using partials we need to manually check for ACL conditions
        if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue;
            $hasChildren = $page->hasPages(); 
        ?>
        <div class='col-md-3 nav-checkout-item'>
            <a class="nav-header h4<?php if($page->isActive()) { echo ' active'; } ?>" href="<?php echo $page->getHref() ?>">
                <span class='nav-checkout-number'><?php echo $count; ?></span>
                <?php echo $this->translate($page->getLabel()) ?>
                <?php if($this->checkoutactive($page->getHref())): ?>
                    <i class='fa fa-check pull-right primary-color'></i>
                <?php endif; ?>
                
            </a>
            <?php if(count($this->container) != $count): ?>
                <!--<i class='fa fa-lg fa-arrow-right nav-checkout-arrow'></i>-->
            <?php endif; ?>
        </div>
        <?php 
        $count++;
    endforeach; ?>
</div>