<?php 
$form->setAttribute('action', $this->url('product', array('action' => 'change-currency')));
$form->prepare();

echo $this->form()->openTag($form); ?>
<div class="input-group">
    <div class="input-group-addon"><?php echo $this->session()->currency; ?></div>
    <?php echo $this->formRow($form->get('currency')); ?>
    <span class="input-group-btn">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </span>
</div>
<?php
echo $this->formHidden($form->get('csrf'));
echo $this->form()->closeTag();
?>