<div class="order small">
    <h3 class="black"><?php echo $package->getCode()->getValue(); ?></h3>
    <p class="order-description">Name:</p>
    <p class="order-value">
        <?php 
        $participant = $package->getParticipant();
        echo $participant->getFirstname().' '.$participant->getSurname(); 
        ?>
    </p>
    <p class="order-description">Birthday:</p>
    <p class="order-value">
        <?php 
        if($participant->getBirthday() != null) :
            echo $participant->getBirthday()->format('d.m.Y'); 
        endif;
        ?>
    </p>
    <?php foreach($products as $product): ?>
        <p class="order-description"><?php echo $product->getName(); ?>:</p>
        <?php switch($product->getId()):
                /*
                 * week ticket
                 */
                case '1': ?>
                    <?php if(!isset($items[$product->getId()]) || count($items[$product->getId()]) == 0): ?>
                        <p class="order-value"><span class="fa">&#xf096;</span></p>
                    <?php else:
                        foreach($items[$product->getId()] as $item):
                            if($item->hasParentItems()) :
                                continue;
                            endif; ?>
                            <p class="order-value"><span class="fa">&#xf046;</span></p>
                            <?php foreach($item->getChildItems() as $cItem): ?>
                                <p class="order-description">
                                    included <?php echo $cItem->getProduct()->getName(); ?>: 
                                </p>
                                <p class="order-value">
                                    <?php foreach($cItem->getItemVariants() as $variant): ?>
                                        <span><?php echo $variant->getValue(); ?></span>
                                    <?php endforeach; ?>
                                </p>
                            <?php endforeach; ?>
                        <?php endforeach; 
                    endif; ?>
                    <?php break;
                /*
                 * gala show ticket
                 */
                case '98': ?>
                    <?php if(!isset($items[$product->getId()]) || count($items[$product->getId()]) == 0): ?>
                        <p class="order-value">none</p>
                    <?php else: ?>
                        <?php foreach($items[$product->getId()] as $item):
                            if($item->hasParentItems()) :
                                continue;
                            endif; ?>
                            <p class="order-description"><?php echo $item->getProduct()->getName(); ?>:</p>
                            <p class="order-value">
                                <?php foreach($item->getItemVariants() as $variant): ?>
                                <span><?php echo $variant->getValue(); ?></span>
                                <?php endforeach; ?>
                            </p>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php break;
                /*
                 * day ticket
                 */
                case '99': ?>
                        <p class="order-value">
                            <table class="day-table">
                                <tr>
                                    <?php foreach($product->getProductVariantByName('Day')->getProductVariantValues() as $value):
                                        $timestamp = strtotime($value->getValue());
                                        $date = new DateTime();
                                        $date->setTimestamp($timestamp); ?>
                                        <td><?php echo $date->format('D'); ?></td>
                                    <?php endforeach; ?>
                                </tr>
                                <tr>
                                    <?php foreach($product->getProductVariantByName('Day')->getProductVariantValues() as $value):
                                        $timestamp = strtotime($value->getValue());
                                        $date = new DateTime();
                                        $date->setTimestamp($timestamp); ?>
                                        <td style='font-size: 6px;'><?php echo $date->format('d.m.'); ?></td>
                                    <?php endforeach; ?>
                                </tr>
                                <tr>
                                    <?php foreach($product->getProductVariantByName('Day')->getProductVariantValues() as $value):
                                        $timestamp = strtotime($value->getValue());
                                        $date = new DateTime();
                                        $date->setTimestamp($timestamp);
                                        $found = false;
                                        if(isset($items[$product->getId()]) && is_array($items[$product->getId()])):
                                            foreach($items[$product->getId()] as $item):
                                                $itemValue = $item->getItemVariantByName('Day')->getValue();
                                                if($timestamp == strtotime($itemValue)) {
                                                    $found = true;
                                                }
                                            endforeach;
                                        endif;
                                        ?>
                                        <?php if($found): ?>
                                            <td><span class="fa">&#xf046;</span></td>
                                        <?php else: ?>
                                            <td><span class="fa">&#xf096;</span></td>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </tr>
                            </table>
                        </p>
                    <?php break;
                default: ?>
                    <p class="order-description"><?php echo $item->getProduct()->getName(); ?>:</p>
                    <?php break;
            endswitch; ?>
    <?php endforeach; ?>
</div>