<div class="order small">
    <h3 class="black"><?php echo $package->getCode()->getValue(); ?></h3>
    <p class="order-description">Name:</p>
    <p class="order-value">
        <?php 
        $participant = $package->getParticipant();
        echo $participant->getFirstname().' '.$participant->getSurname(); 
        ?>
    </p>
    <p class="order-description">Birthday:</p>
    <p class="order-value">
        <?php 
        if($participant->getBirthday() != null) :
            echo $participant->getBirthday()->format('d.m.Y'); 
        endif;
        ?>
    </p>
    <?php foreach($products as $product): ?>
        <?php switch($product->getTicketTemplate()):
            #switch($product->getId()):
                /*
                 * week ticket
                 */
                case 'weekticket': ?>
                    <?php if(!isset($items[$product->getId()]) || count($items[$product->getId()]) == 0): ?>
                        <p class="order-description">
                            <span class="order-value fa">&#xf096;</span> <?php echo $product->getName(); ?>
                        </p>
                    <?php else:
                        foreach($items[$product->getId()] as $item):
                            if($item->hasParentItems()) :
                                continue;
                            endif; ?>
                            <p class="order-description">
                                <span class="order-value fa">&#xf046;</span> <?php echo $product->getName(); ?>
                            </p>
                            <?php foreach($item->getItemVariants() as $variant): ?>
                                <p class="additional-order-description">
                                    <?php echo $variant->getName(); ?>: <?php echo $variant->getValue(); ?>
                                </p>
                            <?php endforeach; ?>
                            <?php foreach($item->getChildItems() as $childItem): ?>
                                <p class="additional-order-description">
                                    included <?php echo $childItem->getProduct()->getName(); ?>: 
                                </p>
                                <p class="order-value">
                                    <?php foreach($childItem->getItemVariants() as $variant): ?>
                                        <span><?php echo $variant->getValue(); ?></span>
                                    <?php endforeach; ?>
                                </p>
                            <?php endforeach; ?>
                        <?php endforeach; 
                    endif; ?>
                    <?php break;
                /*
                 * gala show ticket
                 */
                case 'galashow': ?>
                    <?php $itemcount = 0; ?>
                    <?php if(!empty($items[$product->getId()]) && count($items[$product->getId()]) >= 0): ?>
                        <?php foreach($items[$product->getId()] as $item):
                            if($item->hasParentItems()) :
                                continue;
                            else:
                                $itemcount++;
                            endif; ?>
                            <p class="order-description"><span class="order-value fa">&#xf046;</span> <?php echo $this->translate('Separate'); ?> <?php echo $product->getName(); ?></p>
                            <p class="order-value">
                                <?php foreach($item->getItemVariants() as $variant): ?>
                                    <span><?php echo $variant->getValue(); ?></span>
                                <?php endforeach; ?>
                            </p>
                        <?php endforeach; ?>
                    <?php endif;
                    if($itemcount == 0): ?>
                        <p class="order-description"><span class="order-value fa">&#xf096;</span> <?php echo $this->translate('separate'); ?> <?php echo $product->getName(); ?></p>
                    <?php endif; ?>
                    <?php break;
                /*
                 * day ticket
                 */
                case 'dayticket': 
                    $productVariantName = 'Day ticket - select day';
                    #$productVariantName = 'Tag';
                    /*$translate = array(
                        'Freitag' => '28.10.2016',
                        'Samstag' => '29.10.2016',
                        'Sonntag' => '30.10.2016',
                    );*/
                    ?>
                    <p class="order-description"><?php echo $product->getName(); ?></p>
                    <p class="order-value">
                        <table class="day-table">
                            <tr>
                                <?php 
                                #error_log('variant name: '.$productVariantName);
                                $productVariant = $product->getProductVariantByName($productVariantName);
                                foreach($productVariant->getProductVariantValues() as $value):
                                    $pattern = [
                                        '/^.*\ -\ /',
                                        '/st\ /',
                                        '/nd\ /',
                                        '/rd\ /',
                                        '/th\ /',
                                    ];
                                    $replace = [
                                        '',
                                        '',
                                        '',
                                        '',
                                        '',
                                    ];
                                    $datestring = preg_replace($pattern, $replace, $value->getValue()).' 2018';
                                    $timestamp = strtotime($datestring);
                                    $date = new DateTime();
                                    $date->setTimestamp($timestamp); 
                                    ?>
                                    <td><?php echo strftime('%a', $date->getTimestamp()); ?></td>
                                <?php endforeach; ?>
                            </tr>
                            <tr>
                                <?php foreach($product->getProductVariantByName($productVariantName)->getProductVariantValues() as $value):
                                    $pattern = [
                                        '/^.*\ -\ /',
                                        '/st\ /',
                                        '/nd\ /',
                                        '/rd\ /',
                                        '/th\ /',
                                    ];
                                    $replace = [
                                        '',
                                        '',
                                        '',
                                        '',
                                        '',
                                    ];
                                    $datestring = preg_replace($pattern, $replace, $value->getValue()).' 2018';
                                    $timestamp = strtotime($datestring);
                                    $date = new DateTime();
                                    $date->setTimestamp($timestamp); ?>
                                    <td style='font-size: 6px;'><?php echo $date->format('d.m.'); ?></td>
                                <?php endforeach; ?>
                            </tr>
                            <tr>
                                <?php foreach($product->getProductVariantByName($productVariantName)->getProductVariantValues() as $value):
                                    $timestamp = strtotime($value->getValue());
                                    $date = new DateTime();
                                    $date->setTimestamp($timestamp);
                                    $found = false;
                                    if(isset($items[$product->getId()]) && is_array($items[$product->getId()])):
                                        foreach($items[$product->getId()] as $item):
                                            $itemValue = $item->getItemVariantByName($productVariantName)->getValue();
                                            if($timestamp == strtotime($itemValue)) {
                                                $found = true;
                                            }
                                        endforeach;
                                    endif;
                                    ?>
                                    <?php if($found): ?>
                                        <td><span class="fa">&#xf046;</span></td>
                                    <?php else: ?>
                                        <td><span class="fa">&#xf096;</span></td>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </tr>
                        </table>
                    </p>
                    <?php break;
                case 'clothes': ?>
                    <?php if(isset($items[$product->getId()]) && count($items[$product->getId()]) > 0): ?>
                        <p class="order-description"><span class="order-value fa">&#xf046;</span> <?php echo $product->getName(); ?></p>
                    <?php else: ?>
                        <p class="order-description"><span class="order-value fa">&#xf096;</span> <?php echo $product->getName(); ?></p>
                    <?php endif; ?>
                    <?php if(!empty($items[$product->getId()]) && count($items[$product->getId()]) > 0): ?>
                        <?php foreach($items[$product->getId()] as $item):
                            if($item->hasParentItems()) :
                                continue;
                            endif; ?>
                            <p class="order-value">
                                <?php $variants = $item->getItemVariants()->toArray();
                                usort($variants, array('ErsBase\Entity\Item', 'variantCmp'));
                                $i = 0;
                                foreach($variants as $variant): 
                                    #echo $variant->getName().': '.$variant->getValue()."<br />";
                                    if(++$i == count($variants)) {
                                        echo $variant->getValue();
                                    } else {
                                        echo $variant->getValue().', ';
                                    }
                                endforeach; ?>
                            </p>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php break;
                case 'default':
                default: ?>
                    <?php if(isset($items[$product->getId()]) && count($items[$product->getId()]) > 0): ?>
                        <p class="order-description"><span class="order-value fa">&#xf046;</span> <?php echo $product->getName(); ?></p>
                    <?php else: ?>
                        <p class="order-description"><span class="order-value fa">&#xf096;</span> <?php echo $product->getName(); ?></p>
                    <?php endif; ?>
                    <?php break;
            endswitch; ?>
    <?php endforeach; ?>
</div>
