<?php switch($order->getPaymentStatus()):
    case 'paid': ?>
        <div class="panel panel-success">
            <div class="panel-heading text-center">
                <i class="fa fa-check"></i> <?php echo $order->getPaymentStatus(); ?>
            </div>
        </div>
        <?php break;
    case 'unpaid': ?>
        <div class="panel panel-warning">
            <div class="panel-heading text-center">
                <i class="fa fa-warning"></i> <?php echo $order->getPaymentStatus(); ?>
            </div>
        </div>
        <?php break;
    case 'cancelled': ?>
        <div class="panel panel-danger">
            <div class="panel-heading text-center">
                <i class="fa fa-close"></i> <?php echo $order->getPaymentStatus(); ?>
            </div>
        </div>
        <?php break;
    default: ?>
        <div class="panel panel-info">
            <div class="panel-heading text-center">
                <i class="fa fa-info"></i> <?php echo $order->getPaymentStatus(); ?>
            </div>
        </div>
<?php endswitch; ?>