<div>
    <?php if($order == null): ?>
    <h1><?php echo $this->translate('There is no order to show bank transfer details for'); ?></h1>
    <p>Go to <a href="<?php echo $this->url('product'); ?>">products</a> and 
        choose the items you want.</p>
    <?php else: 
        $paymentType = $order->getPaymentType();
        ?>
    <p><?php echo $this->translate('Please transfer the amount by bank transfer to the following account:'); ?></p>
    <table class="table">
        <tr>
            <td><?php echo $this->translate('Owner'); ?></td>
            <td><?php echo $paymentType->getOwner(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('IBAN'); ?></td>
            <td><?php echo $this->niceiban($paymentType->getIban()); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('BIC'); ?></td>
            <td><?php echo $paymentType->getBic(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Bank'); ?></td>
            <td><?php echo $paymentType->getBankName(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Country'); ?></td>
            <td><?php echo $paymentType->getBankCountry(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Amount'); ?></td>
            <td><?php echo $this->currencyFormat($order->getSum(), $order->getCurrency()->getShort(), null, 'de_DE'); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Reason for payment'); ?></td>
            <td><?php echo $order->getCode()->getValue(); ?></td>
        </tr>
    </table>
    
    <h4><?php echo $this->translate('Owner address'); ?></h4>
    <p><?php 
        if(!empty($paymentType->getOwnerAddress1())): echo $paymentType->getOwnerAddress1().'<br />'; endif;
        if(!empty($paymentType->getOwnerAddress2())): echo $paymentType->getOwnerAddress2().'<br />'; endif;
        if(!empty($paymentType->getOwnerAddress3())): echo $paymentType->getOwnerAddress3().'<br />'; endif;
        if(!empty($paymentType->getOwnerAddress4())): echo $paymentType->getOwnerAddress4().'<br />'; endif;
        ?></p>
    
    <h4><?php echo $this->translate('Bank address'); ?></h4>
    <p><?php 
        if(!empty($paymentType->getBankAddress1())): echo $paymentType->getBankAddress1().'<br />'; endif;
        if(!empty($paymentType->getBankAddress2())): echo $paymentType->getBankAddress2().'<br />'; endif;
        if(!empty($paymentType->getBankAddress3())): echo $paymentType->getBankAddress3().'<br />'; endif;
        if(!empty($paymentType->getBankAddress4())): echo $paymentType->getBankAddress4().'<br />'; endif;
        ?></p>

    <p>
        <?php printf($this->translate('Make sure to fill in this reason for payment <strong>%s</strong> as the reference for the transfer. Otherwise we won\'t be able to match your payment and your order can\'t be processed.'), $order->getCode()->getValue()); ?>
    </p>

    <?php endif; ?>
</div>