<?php
$title = "Undo item shipping";
$this->headTitle($title);

$form->setAttribute('action', $this->url('onsite/package', ['action' => 'undo-item', 'id' => $package->getId(), 'item-id' => $item->getId()]));
$form->prepare();
?>

<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>Do you really want to set the following item of <b><?php echo $this->escapeHtml($package->getParticipant()->getFullName()); ?></b> back to <b>unshipped</b>?</p>
<div class="row">
<div class="package col-xs-offset-1 col-xs-9">
    <p class="h4"><?php echo $this->escapeHtml($item->getName()); ?></p>
    <?php foreach ($item->getItemVariants() AS $itemVariant): ?>
        <div><?php echo $this->escapeHtml($itemVariant->getName() . ': ' . $itemVariant->getValue()); ?></div>
    <?php endforeach; ?>
</div>
</div>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
&nbsp;
<a href="<?php echo $this->url('onsite/package', ['action' => 'detail', 'id' => $package->getId()]); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();