<?php

$title = 'Add Currency';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/currency', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('parent_id'));
echo $this->formRow($form->get('factor'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('symbol'));
echo $this->formRow($form->get('short'));
echo $this->formRow($form->get('active'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/currency');?>">Cancel</a>
<?php
echo $this->form()->closeTag();