<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Currency Overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Pos.</th>
        <th>Name</th>
        <th>active</th>
        <th class="text-right">
            <a class="btn btn-success" href="<?php echo $this->url('admin/currency', array('action'=>'add'));?>"><i class="fa fa-plus"></i> currency</a>
        </th>
    </tr>
<?php foreach ($currencys as $currency) : ?>
    <tr>
        <td><?php echo $currency->getPosition(); ?></td>
        <td><?php echo $currency->getName(); ?> (<?php echo $currency->getShort().' / '.$currency->getSymbol(); ?>)</td>
        <td>
            <?php if($currency->getActive()): ?>
            <i class="fa fa-check"></i>
            <?php else: ?>
            <i class="fa fa-close"></i>
            <?php endif; ?>
        </td>
        <td class="text-right">
            <a class="btn btn-default" href="<?php echo $this->url('admin/currency', array('action'=>'edit', 'id' => $currency->getId()));?>"><i class="fa fa-edit"></i></a>
            <a class="btn btn-danger" href="<?php echo $this->url('admin/currency', array('action'=>'delete', 'id' => $currency->getId()));?>"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>