<?php
$itemStatusMessages = [
    'ordered' => 'The item was not paid.',
    'shipped' => 'The item was delivered.',
    'cancelled' => 'The item was cancelled.',
    'unknown' => 'No status information available about the item.',
];
$itemStatusColors = [
    'paid' => 'success',
    'shipped' => 'primary',
    'default' => 'warning',
];
$itemStatusIcons = [
    'paid' => 'fa-check',
    'shipped' => 'fa-barcode',
    'default' => 'fa-warning',
];


$status = ($item->getShipped() ? 'shipped' : ($item->getStatus() ?: 'unknown'));
$itemOK = ($status === 'paid');
?>
<li><label class="block package">
    <div class="row">
        <div class="col-xs-6">
            <p class="h4 item-name"><?php echo $this->escapeHtml($item->getName()); ?></p>

            <?php foreach ($item->getItemVariants() AS $itemVariant): ?>
                <div><?php echo $this->escapeHtml($itemVariant->getName() . ': ' . $itemVariant->getValue()); ?></div>
            <?php endforeach; ?>
        </div>
        <div class="col-xs-2">
            <?php echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); ?>
        </div>
        
        <?php if($item->getShipped()): ?>
            <div class="col-xs-4 text-primary">
                <p class="h4">
                    <i class="fa fa-barcode"></i> shipped
                </p>
                <p>The item was delivered.</p>

                <a href="<?php echo $this->url('onsite/package', ['action' => 'undo-item', 'id' => $item->getPackage()->getId(), 'item-id' => $item->getId()])
                ?>" class="btn btn-sm btn-danger">Undo</a>
            </div>
        
        <?php else: ?>
            <div class="col-xs-3 text-<?php echo ($itemOK ? 'success' : 'warning'); ?>">
                <p class="h4">
                    <i class="fa <?php echo ($itemOK ? 'fa-success' : 'fa-warning'); ?>"></i>
                    <?php echo $this->escapeHtml($status); ?>
                </p>
                <?php
                if(isset($itemStatusMessages[$status])):
                    echo '<p>' . $itemStatusMessages[$status] . '</p>';
                endif;
                ?>
            </div>
            <div class="col-xs-1">
                <input type="checkbox" class="checkbox item-ship-checkbox" name="items[]" value="<?php echo $item->getId(); ?>" <?php echo ($itemOK ? '' : ' disabled') ?>>
            </div>
        <?php endif; ?>
    </div>
</label></li>