<?php

$title = 'Add role for user '.$user->getEmail();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/user',
    array(
        'action' => 'add-role',
        'id'     => $user->getId(),
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('user_id')); ?>
<div class="row">
    <div class="col-md-3">
        <?php 
        echo $this->formRow($form->get('role_id'));
        ?>
    </div>
</div>
<?php
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
