<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')); ?>
<div class="row">
    <div class="col-md-3">
        <?php 
        echo $this->formRow($form->get('firstname'));
        echo $this->formRow($form->get('surname'));
        echo $this->formRow($form->get('birthday'));
        echo $this->formRow($form->get('email'));
        echo $this->formRow($form->get('Country_id'));
        ?>
    </div>
</div>
<?php
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/user');?>">Cancel</a>
<?php
echo $this->form()->closeTag();