<?php

$title = 'Delete User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete price limit
    <strong><?php echo $user->getEmail().' '.$user->getFirstname().' '.$user->getSurname(); ?></strong>?
</p>
<?php
$url = $this->url('admin/user', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $user->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/user');?>">Cancel</a>
</div>
</form>