<?php
/* I'd like to have a banana! */

$title = 'User Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/user', array('action'=>'add'));?>">Add User</a>
</p>

<table class="table">
    <tr>
        <th>name</th>
        <th>email</th>
        <th>age</th>
        <th>roles</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($users as $user) : ?>
    <tr>
        <td><?php echo $user->getFirstname().' '.$user->getSurname(); ?></td>
        <td><?php echo $user->getEmail(); ?></td>
        <td><?php 
            if($user->getBirthday() != null) {
                $now = new \DateTime();
                echo $now->diff($user->getBirthday())->format('%Y'); 
            }
        ?></td>
        <td>
            <?php foreach($user->getRoles() as $role) : ?>
            <p><?php echo $role->getRoleId(); ?></p>
            <?php endforeach; ?>
        </td>
        <td>
            <a href="<?php echo $this->url('admin/user', array('action'=>'edit', 'id' => $user->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>