<?php
/* I'd like to have a banana! */

$title = 'User Overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>name</th>
        <th>email</th>
        <th>age</th>
        <th>roles</th>
        <th>
            <a class="btn btn-sm btn-success" href="<?php echo $this->url('admin/user', array('action'=>'add'));?>"><i class="fa fa-plus"></i></a>
        </th>
    </tr>
<?php foreach ($users as $user) : ?>
    <tr>
        <td><?php echo $user->getFirstname().' '.$user->getSurname(); ?></td>
        <td><?php echo $user->getEmail(); ?></td>
        <td><?php 
            if($user->getBirthday() != null) {
                $now = new \DateTime();
                echo $now->diff($user->getBirthday())->format('%Y'); 
            }
        ?></td>
        <td>
            <?php foreach($user->getRoles() as $role) : ?>
            <p><?php echo $role->getRoleId(); ?></p>
            <?php endforeach; ?>
        </td>
        <td>
            <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/user', array('action'=>'edit', 'id' => $user->getId()));?>"><i class="fa fa-edit"></i></a>
            <?php if(in_array('supradm', $roles)): ?>
                <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/user', array('action'=>'role', 'id' => $user->getId()));?>"><i class="fa fa-group"></i></a>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>