<?php
/* pizza would be really nice */

$title = 'Role Overview for user '.$user->getEmail();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<p>
    
</p>

<table class="table">
    <tr>
        <th>RoleId</th>
        <th>
            <a class="btn btn-sm btn-success" href="<?php echo $this->url('admin/user', array('action'=>'add-role', 'id' => $user->getId()));?>"><i class="fa fa-plus"></i></a>
        </th>
    </tr>
<?php foreach ($roles as $role) : ?>
    <tr>
        <td>
            <?php echo $role->getRoleId();?>
        </td>
        <td>
            <a class="btn btn-sm btn-danger" href="<?php echo $this->url('admin/user', array('action'=>'delete-role', 'id' => $user->getId()), array('query' => array('role_id' => $role->getId())));?>"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>