<?php
$this->headTitle("Checkout");


echo $this->flashMessenger()
        ->setMessageOpenFormat('<div%s><p>')
        ->setMessageSeparatorString('</p><p>')
        ->setMessageCloseString('</p></div>')
        ->render('error', ['alert', 'alert-danger']);

?>

<div class="row row-space">
    <div class="col-xs-12 text-center">
        <span class="h1"><?php echo $this->currencyFormat($sum, 'EUR', null, 'de_DE'); ?></span>
    </div>
</div>
<div class="row row-space">
    <div class="col-xs-6">
        <a href="#" class="btn btn-primary btn-xl btn-fullwidth">cash</a>
    </div>
    <div class="col-xs-6">
        <a href="#" class="btn btn-default btn-xl btn-fullwidth">card terminal</a>
    </div>
</div>
<div class="row row-space">
    <div class="col-xs-12 text-center">
        <a href="#" class="btn btn-danger btn-xl">cancel</a>
    </div>
</div>