<?php
$title = 'Change My Profile';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('profile',array('action' => 'change')));
$form->prepare();
#$form->getInputFilter()->get('email')->setRequired(false);

echo $this->form()->openTag($form);
#echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('id'));
?>
<div class="row">
    <div class="col-lg-3">
        <?php 
        echo $this->formRow($form->get('firstname'));
        echo $this->formRow($form->get('surname'));
        echo $this->formRow($form->get('birthday')); 
        echo $this->formRow($form->get('email'));
        echo $this->formRow($form->get('Country_id'));
        ?>
    </div>
    <div class="col-lg-5">
        <p><strong>Note for personal data:</strong> Please enter your  first name, surname and 
            date of birth like they appear on your passport ID card (they will 
            be checked at EJC onsite registration to validate that this e-Ticket 
            belongs to you).</p>
        <p><strong>Note for email address:</strong> If you enter the email 
            address of this person, they will receive a copy of their 
            e-Ticket.</p>
        <p><strong>Note for the buyer:</strong> The person who performs the 
            purchase will automatically receive all ordered e-Tickets. For this 
            reason, they have to enter their email address.</p>
        <p><strong>Note for edit details:</strong> You can edit this person's 
            details at any time by clicking My Persons in the menu</p>
    </div>
</div>
<?php
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();