<?php

$title = $this->translate('Edit Profile');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'profile',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('firstname'));
echo $this->formRow($form->get('surname'));
echo $this->formRow($form->get('birthday'));
echo $this->formRow($form->get('email'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('profile'); ?>"><?php echo $this->translate('Cancel'); ?></a>
<?php
echo $this->form()->closeTag();