<?php

$title = 'My Profile';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="profile-nav">
    <?php echo $this->navigation()
        ->menu('profile_nav')
        ->setUlClass('nav nav-pills'); ?>
</div>
<div>
    <table class='table'>
        <tr>
            <td>Firstname:</td>
            <td><?php echo $user->getFirstname(); ?></td>
        </tr>
        <tr>
            <td>Surname:</td>
            <td><?php echo $user->getSurname(); ?></td>
        </tr>
        <tr>
            <td>E-Mail:</td>
            <td><?php echo $user->getEmail(); ?></td>
        </tr>
        <tr>
            <td>Birthdate:</td>
            <td>
                <?php if($user->getBirthday() instanceof \DateTime): ?>
                    <?php echo $user->getBirthday()->format('d.m.Y'); ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td>Country:</td>
            <td>
                <?php if($user->getCountry() instanceof \ErsBase\Entity\Country): ?>
                    <?php echo $user->getCountry()->getName(); ?>
                <?php endif; ?>
            </td>
        </tr>
    </table>
</div>