<?php

$title = $this->translate('My Profile');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="profile-nav">
    <?php echo $this->navigation()
        ->menu('profile_nav')
        ->setUlClass('nav nav-pills'); ?>
</div>
<div>
    <table class='table'>
        <tr>
            <td><?php echo $this->translate('Firstname:'); ?></td>
            <td><?php echo $user->getFirstname(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Surname:'); ?></td>
            <td><?php echo $user->getSurname(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('E-Mail:'); ?></td>
            <td><?php echo $user->getEmail(); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Birthdate:'); ?></td>
            <td>
                <?php if($user->getBirthday() instanceof \DateTime): ?>
                    <?php echo $user->getBirthday()->format('d.m.Y'); ?>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Country:'); ?></td>
            <td>
                <?php if($user->getCountry() instanceof \ErsBase\Entity\Country): ?>
                    <?php echo $user->getCountry()->getName(); ?>
                <?php endif; ?>
            </td>
        </tr>
    </table>
</div>