<?php

$title = $this->translate('Set your password');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'profile',
    array(
        'action' => 'password-reset',
        'hashkey' => $user->getHashKey(),
    )
));
$form->prepare();

$form->get('newPassword')->setAttributes(array( 
    'placeholder' => $this->translate('your password...'),
    'class' => 'form-control form-element',
));
$form->get('newPassword2')->setAttributes(array( 
    'placeholder' => $this->translate('confirm your password...'),
    'class' => 'form-control form-element',
));

$form->get('submit')->setAttributes(array( 
    'class' => 'btn btn-primary',
));?>

<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();