<?php

$title = $this->translate('Edit Profile');
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'profile',
    array(
        'action' => 'password',
    )
));
$form->prepare();

$form->get('submit')->setAttributes(array( 
    'class' => 'btn btn-primary',
));
$form->get('credential')->setAttributes(array( 
    'placeholder' => $this->translate('old password...'),
    'class' => 'form-control form-element',
));
$form->get('credential')->setOptions(array( 
    'label_attributes' => array(
        'class'  => 'media-object',
    ),
));

$form->get('newCredential')->setAttributes(array( 
    'placeholder' => $this->translate('new password...'),
    'class' => 'form-control form-element',
));
$form->get('newCredential')->setOptions(array( 
    'label_attributes' => array(
        'class'  => 'media-object',
    ),
));

$form->get('newCredentialVerify')->setAttributes(array( 
    'placeholder' => $this->translate('verify password...'),
    'class' => 'form-control form-element',
));
$form->get('newCredentialVerify')->setOptions(array( 
    'label_attributes' => array(
        'class'  => 'media-object',
    ),
));


echo $this->form()->openTag($form);
echo $this->formCollection($form);

?>
<a href="<?php echo $this->url('profile'); ?>"><?php echo $this->translate('Cancel'); ?></a>
<?php echo $this->form()->closeTag();