<?php

$title = $this->translate('Request password change');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
if($sent): ?>
    <h3><?php echo $this->translate('If we were able to find your email address in our system an email was 
        sent to you with a link to change your password.'); ?></h3>
    <p><?php echo $this->translate('If you did not receive an email check your spam folder.'); ?></p>
<?php else:
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'profile',
        array(
            'action' => 'request-password',
        )
    ));
    $form->prepare();

    $form->get('email')->setAttributes(array( 
        'placeholder' => $this->translate('Your email address...'),
        'class' => 'form-control form-element',
    ));

    $form->get('submit')->setAttributes(array( 
        'class' => 'btn btn-primary',
    ));?>

    <?php
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    ?>
    <a href="<?php echo $this->url('profile'); ?>"><?php echo $this->translate('Cancel'); ?></a>
    <?php 
    echo $this->form()->closeTag();
endif;