<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Product Price for '.$product->getName();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/product-price',
    array(
        'action' => 'add',
        'id'     => $this->product->getId(),
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('charge'));
echo $this->formRow($form->get('Deadline_id'));
echo $this->formRow($form->get('Product_id'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/product');?>">Cancel</a>
<?php
echo $this->form()->closeTag();