<?php
// module/Admin/view/admin/product-price/delete.phtml:

$title = 'Delete Product Price from '.$product->getName();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete product price
    <strong><?php echo $this->escapeHtml($price->getCharge()); ?> €</strong>?
</p>
<?php
$url = $this->url('admin/product-price', array(
    'action' => 'delete',
    'id'     => $price->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $price->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/product');?>">Cancel</a>
</div>
</form>