<?php
// module/Admin/view/admin/product/edit.phtml:

$title = 'Edit Product Price for '.$product->getName();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/product-price',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('charge'));
echo $this->formRow($form->get('Deadline_id'));
echo $this->formRow($form->get('Agegroup_id'));
echo $this->formRow($form->get('Product_id'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();