<?php

$title = 'Add order status';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/status', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('value'));
echo $this->formRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/status');?>">Cancel</a>
<?php
echo $this->form()->closeTag();