<?php

$title = 'Status Overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-md-6 col-xs-8">
        <table class="table">
            <tr>
                <th>Pos.</th>
                <th>name</th>
                <th>active</th>
                <th>valid</th>
                <th>description</th>
                <th>
                    <a class="btn btn-success btn-sm" href="<?php echo $this->url('admin/status', array('action' => 'add')); ?>"><i class="fa fa-plus"></i> status</a>
                </th>
            </tr>
        <?php foreach ($status as $status) : ?>
            <tr>
                <td><?php echo $status->getPosition(); ?></td>
                <td><?php echo $status->getValue(); ?></td>
                <td>
                    <?php if($status->getActive()): ?>
                        <i class="fa fa-check"></i>
                    <?php else: ?>
                        <i class="fa fa-times"></i>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if($status->getValid()): ?>
                        <i class="fa fa-check"></i>
                    <?php else: ?>
                        <i class="fa fa-times"></i>
                    <?php endif; ?>
                </td>
                <td><?php echo $status->getDescription(); ?></td>
                <td class="text-nowrap">
                    <a class="btn btn-default btn-sm" href="<?php echo $this->url('admin/status', array('action' => 'edit', 'id' => $status->getId())); ?>"><i class="fa fa-edit"></i></a>
                    <a class="btn btn-danger btn-sm" href="<?php echo $this->url('admin/status', array('action' => 'delete', 'id' => $status->getId())); ?>"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>