<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Country Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Order</th>
        <th>Name</th>
        <th>Code</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($countries as $country) : ?>
    <tr>
        <td><?php echo $country->getOrder(); ?></td>
        <td><?php echo $country->getName(); ?></td>
        <td><?php echo $country->getCode(); ?></td>
        <td>
            <a href="<?php echo $this->url('admin/country', array('action'=>'edit', 'id' => $country->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>