<?php
// /Catalogue/view/sticky-notes/sticky-notes/index.phtml
?>

<div id="sticky-notes">
    <?php foreach($stickynotes as $stickynote):?>
    <div class="sticky-note">
        <textarea id="stickynote-<?php echo $stickynote->id; ?>"><?php echo $stickynote->note; ?></textarea>
        <a href="#" id="remove-<?php echo $stickynote->id; ?>"class="delete-sticky">X</a>
    </div>
    <?php endforeach; ?>
    <div id="create">+</div>

</div>
<div class="clear-both"></div>