<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-zf2inputfilterannotation) on 2015-02-02
 * 21:38:10.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ersEntity\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Entity\Order
 *
 * @ORM\Entity()
 * @ORM\Table(name="`Order`", indexes={@ORM\Index(name="fk_Order_User1_idx", columns={"Purchaser_id"}), @ORM\Index(name="fk_Order_PaymentType1_idx", columns={"PaymentType_id"}), @ORM\Index(name="fk_Order_Barcode1_idx", columns={"Barcode_id"})})
 * @ORM\HasLifecycleCallbacks()
 */
class Order implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Purchaser_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $PaymentType_id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $matchKey;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $invoiceDetail;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Barcode_id;

    /**
     * @ORM\OneToMany(targetEntity="Match", mappedBy="order")
     * @ORM\JoinColumn(name="id", referencedColumnName="Order_id")
     */
    protected $matches;

    /**
     * @ORM\OneToMany(targetEntity="Package", mappedBy="order")
     * @ORM\JoinColumn(name="id", referencedColumnName="Order_id")
     */
    protected $packages;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="orders")
     * @ORM\JoinColumn(name="Purchaser_id", referencedColumnName="id")
     */
    protected $purchaser;

    /**
     * @ORM\ManyToOne(targetEntity="PaymentType", inversedBy="orders")
     * @ORM\JoinColumn(name="PaymentType_id", referencedColumnName="id")
     */
    protected $paymentType;

    /**
     * @ORM\ManyToOne(targetEntity="Barcode", inversedBy="orders")
     * @ORM\JoinColumn(name="Barcode_id", referencedColumnName="id")
     */
    protected $barcode;

    public function __construct()
    {
        $this->matches = new ArrayCollection();
        $this->packages = new ArrayCollection();
    }
    
    /**
     * @ORM\PrePersist
     */
    public function PrePersist()
    {
        if(!isset($this->created)) {
            $this->created = new \DateTime();
        }
        $this->updated = new \DateTime();
    }
    
    /**
     * Set id of this object to null if it's cloned
     */
    public function __clone() {
        $this->id = null;
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\Order
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Purchaser_id.
     *
     * @param integer $Purchaser_id
     * @return \Entity\Order
     */
    public function setPurchaserId($Purchaser_id)
    {
        $this->Purchaser_id = $Purchaser_id;

        return $this;
    }

    /**
     * Get the value of Purchaser_id.
     *
     * @return integer
     */
    public function getPurchaserId()
    {
        return $this->Purchaser_id;
    }

    /**
     * Set the value of PaymentType_id.
     *
     * @param integer $PaymentType_id
     * @return \Entity\Order
     */
    public function setPaymentTypeId($PaymentType_id)
    {
        $this->PaymentType_id = $PaymentType_id;

        return $this;
    }

    /**
     * Get the value of PaymentType_id.
     *
     * @return integer
     */
    public function getPaymentTypeId()
    {
        return $this->PaymentType_id;
    }

    /**
     * Set the value of matchKey.
     *
     * @param string $matchKey
     * @return \Entity\Order
     */
    public function setMatchKey($matchKey)
    {
        $this->matchKey = $matchKey;

        return $this;
    }

    /**
     * Get the value of matchKey.
     *
     * @return string
     */
    public function getMatchKey()
    {
        return $this->matchKey;
    }

    /**
     * Set the value of invoiceDetail.
     *
     * @param string $invoiceDetail
     * @return \Entity\Order
     */
    public function setInvoiceDetail($invoiceDetail)
    {
        $this->invoiceDetail = $invoiceDetail;

        return $this;
    }

    /**
     * Get the value of invoiceDetail.
     *
     * @return string
     */
    public function getInvoiceDetail()
    {
        return $this->invoiceDetail;
    }

    /**
     * Set the value of updated.
     *
     * @param datetime $updated
     * @return \Entity\Order
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get the value of updated.
     *
     * @return datetime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set the value of created.
     *
     * @param datetime $created
     * @return \Entity\Order
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get the value of created.
     *
     * @return datetime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set the value of Barcode_id.
     *
     * @param integer $Barcode_id
     * @return \Entity\Order
     */
    public function setBarcodeId($Barcode_id)
    {
        $this->Barcode_id = $Barcode_id;

        return $this;
    }

    /**
     * Get the value of Barcode_id.
     *
     * @return integer
     */
    public function getBarcodeId()
    {
        return $this->Barcode_id;
    }

    /**
     * Add Match entity to collection (one to many).
     *
     * @param \Entity\Match $match
     * @return \Entity\Order
     */
    public function addMatch(Match $match)
    {
        $this->matches[] = $match;

        return $this;
    }

    /**
     * Remove Match entity from collection (one to many).
     *
     * @param \Entity\Match $match
     * @return \Entity\Order
     */
    public function removeMatch(Match $match)
    {
        $this->matches->removeElement($match);

        return $this;
    }

    /**
     * Get Match entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMatches()
    {
        return $this->matches;
    }

    /**
     * Add Package entity to collection (one to many).
     *
     * @param \Entity\Package $package
     * @return \Entity\Order
     */
    public function addPackage(Package $package)
    {
        if(!is_numeric($package->getSessionId())) {
            $id = \count($this->getPackages())+1;
            $package->setSessionId($id);
        }
        $this->packages[] = $package;

        return $this;
    }
    
    /**
     * Add Item to the according package with the correct Purchaser_id
     * 
     * @param \Entity\Item $item
     * @param integer $Purchaser_id
     * @return \Entity\Order
     */
    public function addItem(Item $item, $Purchaser_id)
    {
        if(isset($this->packages[$Purchaser_id])) {
            $this->packages[$Purchaser_id]->addItem($item);
        } else {
            $this->packages[$Purchaser_id] = new Package();
            $this->packages[$Purchaser_id]->setParticipant(new User());
            $this->packages[$Purchaser_id]->addItem($item);
            #throw new \Exception("Unable to add item to your shopping cart.");
        }
        
        return $this;
    }
    
    /**
     * Remove Package entity from collection (one to many).
     *
     * @param \Entity\Package $package
     * @return \Entity\Order
     */
    public function removePackage(Package $package)
    {
        $this->packages->removeElement($package);

        return $this;
    }

    /**
     * Get Package entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPackages()
    {
        return $this->packages;
    }
    
    /**
     * Get Package by participant session id.
     * 
     * @return Entity\Package
     */
    public function getPackageByParticipantSessionId($id) {
        foreach($this->getPackages() as $package) {
            if($package->getParticipant()->getSessionId() == $id) {
                return $package;
            }
        }
        return false;
    }

    /**
     * Get Participants of Packages
     * 
     * @return array
     */
    public function getParticipants() {
        $participants = array();
        foreach($this->getPackages() as $package) {
            if($package->getParticipant()->getPrename() != '' && $package->getParticipant()->getSurname() != '') {
                $id = $package->getParticipant()->getSessionId();
                $participants[$id] = $package->getParticipant();
            }
        }
        
        return $participants;
    }
    
    /**
     * Get Participant by session_id
     * 
     * @return Entity\User
     * @return false
     */
    public function getParticipantBySessionId($id) {
        /*$packages = $this->getPackages();
        for($i = 0; $i < count($packages); $i++) {
            if($packages[$i]->getParticipant()->getSessionId() == $id) {
                return $packages[$i]->getParticipant();
            }
        }*/
        foreach($this->getPackages() as $package) {
            if($package->getParticipant()->getSessionId() == $id) {
                return $package->getParticipant();
            }
        }
        return false;
    }
    
    /**
     * Set Participant by session_id
     * 
     * @return boolean
     */
    public function setParticipantBySessionId(User $user, $id) {
        $packages = $this->getPackages();
        for($i = 0; $i < count($packages); $i++) {
            if($packages[$i]->getParticipant()->getSessionId() == $id) {
                $packages[$i]->setParticipant($user);
                return true;
            }
        }
        return false;
    }
    
    /**
     * Add Participant (add new Package and set participant)
     * 
     * @param \Entity\User $participant
     * @return \Entity\Order
     */
    
    public function addParticipant($participant) {
        $package = new Package();
        $id = \count($this->getPackages())+1;
        $participant->setSessionId($id);
        $package->setParticipant($participant);
        
        $this->packages[] = $package;
        
        return $this;
    }
    
    /**
     * Remove Package entity by participant
     *
     * @param int
     * @return \Entity\Order
     */
    public function removeParticipantBySessionId($id)
    {
        foreach($this->getPackages() as $package) {
            if($package->getParticipant()->getSessionId() == $id) {
                $this->packages->removeElement($package);
            }
        }

        return $this;
    }
    
    /**
     * Set Purchaser entity (many to one).
     *
     * @param \Entity\User $purchaser
     * @return \Entity\Order
     */
    public function setPurchaser(User $purchaser = null)
    {
        $this->purchaser = $purchaser;

        return $this;
    }

    /**
     * Get Purchaser entity (many to one).
     *
     * @return \Entity\User
     */
    public function getPurchaser()
    {
        return $this->purchaser;
    }

    /**
     * Set PaymentType entity (many to one).
     *
     * @param \Entity\PaymentType $paymentType
     * @return \Entity\Order
     */
    public function setPaymentType(PaymentType $paymentType = null)
    {
        $this->paymentType = $paymentType;

        return $this;
    }

    /**
     * Get PaymentType entity (many to one).
     *
     * @return \Entity\PaymentType
     */
    public function getPaymentType()
    {
        return $this->paymentType;
    }

    /**
     * Set Barcode entity (many to one).
     *
     * @param \Entity\Barcode $barcode
     * @return \Entity\Order
     */
    public function setBarcode(Barcode $barcode = null)
    {
        $this->barcode = $barcode;

        return $this;
    }

    /**
     * Get Barcode entity (many to one).
     *
     * @return \Entity\Barcode
     */
    public function getBarcode()
    {
        return $this->barcode;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'Purchaser_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'PaymentType_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'matchKey',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'invoiceDetail',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'updated',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'created',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'Barcode_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }
    public function exchangeArray(array $data = array()) {
        $this->populate($data);
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'Purchaser_id', 'PaymentType_id', 'matchKey', 'invoiceDetail', 'updated', 'created', 'Barcode_id');
        $relationFields = array('user', 'paymentType', 'barcode');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'Purchaser_id', 'PaymentType_id', 'matchKey', 'invoiceDetail', 'packages', 'updated', 'created', 'Barcode_id');
    }
}