<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-zf2inputfilterannotation) on 2015-02-02
 * 21:38:10.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ersEntity\Entity;

use Doctrine\ORM\Mapping as ORM;
#use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;
use Zend\Validator;


/**
 * Entity\ProductPrice
 *
 * @ORM\Entity()
 * @ORM\Table(name="ProductPrice", indexes={@ORM\Index(name="fk_ProductPrice_Product1_idx", columns={"Product_id"})})
 * @ORM\HasLifecycleCallbacks()
 */
class ProductPrice implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Product_id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $charge;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $Deadline_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $Agegroup_id;
    
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $Counter_id;
    
    /**
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @ORM\ManyToOne(targetEntity="Product", inversedBy="productPrices")
     * @ORM\JoinColumn(name="Product_id", referencedColumnName="id")
     */
    protected $product;

    /**
     * @ORM\ManyToOne(targetEntity="Deadline", inversedBy="productPrices")
     * @ORM\JoinColumn(name="Deadline_id", referencedColumnName="id", nullable=true)
     */
    protected $deadline;

    /**
     * @ORM\ManyToOne(targetEntity="Agegroup", inversedBy="productPrices")
     * @ORM\JoinColumn(name="Agegroup_id", referencedColumnName="id", nullable=true)
     */
    protected $agegroup;
    
    public function __construct()
    {
    }
    
    /**
     * @ORM\PrePersist
     */
    public function PrePersist()
    {
        if(!isset($this->created)) {
            $this->created = new \DateTime();
        }
        $this->updated = new \DateTime();
    }
    
    /**
     * @ORM\PreUpdate
     */
    public function PreUpdate()
    {
        $this->updated = new \DateTime();
    }
    
    /**
     * Set id of this object to null if it's cloned
     */
    public function __clone() {
        $this->id = null;
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Entity\ProductPrice
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Product_id.
     *
     * @param integer $Product_id
     * @return \Entity\ProductPrice
     */
    public function setProductId($Product_id)
    {
        $this->Product_id = $Product_id;

        return $this;
    }

    /**
     * Get the value of Product_id.
     *
     * @return integer
     */
    public function getProductId()
    {
        return $this->Product_id;
    }

    /**
     * Set the value of charge.
     *
     * @param string $charge
     * @return \Entity\ProductPrice
     */
    public function setCharge($charge)
    {
        $this->charge = $charge;

        return $this;
    }

    /**
     * Get the value of charge.
     *
     * @return string
     */
    public function getCharge()
    {
        return $this->charge;
    }

    /**
     * Set the value of Deadline_id.
     *
     * @param integer $Deadline_id
     * @return \Entity\ProductPrice
     */
    public function setDeadlineId($Deadline_id)
    {
        $this->Deadline_id = $Deadline_id;

        return $this;
    }

    /**
     * Get the value of Deadline_id.
     *
     * @return integer
     */
    public function getDeadlineId()
    {
        return $this->Deadline_id;
    }
    
    /**
     * Set the value of Agegroup_id.
     *
     * @param integer $Agegroup_id
     * @return \Entity\ProductPrice
     */
    public function setAgegroupId($Agegroup_id)
    {
        $this->Agegroup_id = $Agegroup_id;

        return $this;
    }

    /**
     * Get the value of Agegroup_id.
     *
     * @return integer
     */
    public function getAgegroupId()
    {
        return $this->Agegroup_id;
    }

    /**
     * Set the value of Counter_id.
     *
     * @param integer $Counter_id
     * @return \Entity\ProductPrice
     */
    public function setCounterId($Counter_id)
    {
        $this->Counter_id = $Counter_id;

        return $this;
    }

    /**
     * Get the value of Counter_id.
     *
     * @return integer
     */
    public function getCounterId()
    {
        return $this->Counter_id;
    }

    /**
     * Set Deadline entity (many to one).
     *
     * @param \Entity\Deadline $deadline
     * @return \Entity\ProductPrice
     */
    public function setDeadline(Deadline $deadline = null)
    {
        $this->deadline = $deadline;

        return $this;
    }

    /**
     * Get Deadline entity (many to one).
     *
     * @return \Entity\Deadline
     */
    public function getDeadline()
    {
        return $this->deadline;
    }
    
    /**
     * Set Agegroup entity (many to one).
     *
     * @param \Entity\Agegroup $agegroup
     * @return \Entity\ProductPrice
     */
    public function setAgegroup(Agegroup $agegroup = null)
    {
        $this->agegroup = $agegroup;

        return $this;
    }

    /**
     * Get Agegroup entity (many to one).
     *
     * @return \Entity\Agegroup
     */
    public function getAgegroup()
    {
        return $this->agegroup;
    }

    /**
     * Set Counter entity (many to one).
     *
     * @param \Entity\Counter $counter
     * @return \Entity\ProductPrice
     */
    public function setCounter(Counter $counter = null)
    {
        $this->counter = $counter;

        return $this;
    }

    /**
     * Get Counter entity (many to one).
     *
     * @return \Entity\Counter
     */
    public function getCounter()
    {
        return $this->counter;
    }
    
    /**
     * Set the value of updated.
     *
     * @param string $updated
     * @return \Entity\ProductPrice
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get the value of updated.
     *
     * @return string
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set the value of created.
     *
     * @param string $created
     * @return \Entity\ProductPrice
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get the value of created.
     *
     * @return string
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set Product entity (many to one).
     *
     * @param \Entity\Product $product
     * @return \Entity\ProductPrice
     */
    public function setProduct(Product $product = null)
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Get Product entity (many to one).
     *
     * @return \Entity\Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Add PriceLimit entity to collection.
     *
     * @param \Entity\PriceLimit $priceLimit
     * @return \Entity\ProductPrice
     */
    public function addPriceLimit(PriceLimit $priceLimit)
    {
        $priceLimit->addProductPrice($this);
        $this->priceLimits[] = $priceLimit;

        return $this;
    }

    /**
     * Remove PriceLimit entity from collection.
     *
     * @param \Entity\PriceLimit $priceLimit
     * @return \Entity\ProductPrice
     */
    public function removePriceLimit(PriceLimit $priceLimit)
    {
        $priceLimit->removeProductPrice($this);
        $this->priceLimits->removeElement($priceLimit);

        return $this;
    }

    /**
     * Get PriceLimit entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPriceLimits()
    {
        return $this->priceLimits;
    }
    
    /**
     * Set the value of priceLimit_id.
     *
     * @param string $id
     * @return \Entity\ProductPrice
     */
    public function setPriceLimitId($id)
    {
        $this->priceLimitId = (int) $id;

        return $this;
    }

    /**
     * Get the value of priceLimit_id.
     *
     * @return integer
     */
    public function getPriceLimitId()
    {
        return $this->priceLimitId;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(
                    array('name' => 'Int'),
                ),
                'validators' => array(),
            ),
            array(
                'name' => 'Product_id',
                'required' => true,
                'filters' => array(
                    array('name' => 'StripTags'),
                    array('name' => 'StringTrim'),
                    array('name' => 'Int'),
                ),
                'validators' => array(),
            ),
            array(
                'name' => 'charge',
                'required' => false,
                'filters' => array(
                    array('name' => 'StripTags'),
                    array('name' => 'StringTrim'),
                    new \Zend\I18n\Filter\NumberFormat("en_US"),
                ),
                'validators' => array(
                    array (
                        'name' => '\ersEntity\Validator\NotEmptyAllowZero',
                        #'name' => 'NotEmptyAllowZero',
                        'options' => array(
                            'messages' => array(
                                'isEmpty' => '',
                                Validator\NotEmpty::IS_EMPTY => 'Please give a charge for this price.',
                            )
                        ),
                    ),
                    array('name'    => 'Float'),
                ),
            ),
            array(
                'name' => 'updated',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'created',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'Deadline_id',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'Counter_id',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'Product_id', 'charge', 'Deadline_id', 'Agegroup_id', 'updated', 'created');
        $relationFields = array('product');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'Product_id', 'charge', 'Deadline_id', 'Agegroup_id', 'updated', 'created');
    }
}