<?php

$title = 'Delete Counter';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete counter
    <strong><?php echo $counter->getName(); ?></strong>?
</p>
<?php
$url = $this->url('admin/counter', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $counter->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/counter');?>">Cancel</a>
</div>
</form>