<?php
// module/Album/view/album/album/add.phtml:

$title = 'Edit Counter';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/counter',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name')); ?>
<?php echo $this->formRow($form->get('value')); ?>
<div class="row">
    <div class="col-md-12">
        <h3>Choose one of the following:</h3>
    </div>
    <div class="col-md-4">
        <?php echo $this->formRow($form->get('product')); ?>
    </div>
    <div class="col-md-4">
        <?php echo $this->formRow($form->get('productVariant')); ?>
    </div>
    <div class="col-md-4">
        <?php echo $this->formRow($form->get('productVariantValue')); ?>
    </div>
</div>

<?php echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/counter'); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();