<?php

$title = 'Accept match';
$this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
    <a class="small" href="<?php echo $this->url('admin/matching', array('action' => 'manual')); ?>">Cancel</a>
</h1>
<?php if((count($orders) == 1 && count($statements) >= 1) || (count($orders) >= 1 && count($statements) == 1)): ?>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <span class="panel-title">orders for this match</span>
                </div>
                <div class="panel-body">
                    <?php foreach($orders as $order): 
                        $buyer = $order->getBuyer();
                        ?>
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-11">
                                        <span class="panel-title"><?php echo $order->getCode()->getValue(); ?></span>
                                    </div>
                                    <div class="col-xs-1 text-right">
                                        <span class="panel-title"><i class="fa fa-arrow-right"></i></span>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <p>Buyer: <?php echo $buyer->getFirstname().' '.$buyer->getSurname(); ?></p>
                                <p>Amount: <?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></p>
                                <?php foreach($order->getPackages() as $package): 
                                    $participant = $package->getParticipant();
                                    ?>
                                    <div class="panel panel-success">
                                        <div class="panel-body">
                                            <h3><?php echo $participant->getFirstname().' '.$participant->getSurname(); ?></h3>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <span class="panel-title">statements for this match</span>
                </div>
                <div class="panel-body">
                    <?php foreach($statements as $statement): ?>
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-1">
                                        <span class="panel-title"><i class="fa fa-arrow-left"></i></span>
                                    </div>
                                    <div class="col-xs-11">
                                        <span class="panel-title"><?php echo $statement->getBankAccount()->getName(); ?></span>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <p>name: <?php echo $statement->getName()->getValue(); ?></p>
                                <p>amount: <?php echo $this->currencyFormat((float) $statement->getAmount()->getValue(), 'EUR', null, 'de_DE'); ?></p>
                                <p>code: <?php echo $statement->getCode()->getValue(); ?></p>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('admin/matching', 
            array('action' => 'accept'),
            array('query' => $params)
            ));
    $form->prepare();

    echo $this->form()->openTag($form); ?>
    <?php 
    foreach($statements as $statement): ?>
        <input type='hidden' name='BankStatement_id[]' value='<?php echo $statement->getId(); ?>' />
    <?php endforeach;
    foreach($orders as $order): ?>
        <input type='hidden' name='Order_id[]' value='<?php echo $order->getId(); ?>' />
    <?php endforeach;
    echo $this->formHidden($form->get('Admin_id')); ?>
    <div class="row">
        <div class="col-md-12">
            <?php echo $this->formRow($form->get('comment')); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            
            <?php 
            echo $this->formHidden($form->get('csrf'));
            echo $this->formSubmit($form->get('submit')); 
            ?>
            <a href="<?php echo $this->url('admin/matching', array('action' => 'manual')); ?>">Cancel</a>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
<?php else: ?>
    <p>It's not possible to do the match. Please choose one of the following: </p>
    <ol>
        <li>a single order and one or multiple bankstatements</li>
        <li>one or multiple orders and a single bankstatement</li>
    </ol>
    <a href='<?php echo $this->url('admin/matching', array('action' => 'manual')); ?>'>Cancel</a>
<?php endif; ?>