<?php
$this->headTitle("Search");
?>

<?php echo $this->partial('partial/search-box'); ?>

<?php if ($query !== NULL): ?>
    <h4>Search results for "<?php echo $this->escapeHtml($query); ?>"</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Order code</th>
                <th>Package code</th>
                <th>Name</th>
                <th>Date of birth</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($results as $package): ?>
            <tr>
                <td><?php echo $this->escapeHtml($package->getOrder()->getCode()->getValue()); ?></td>
                <td><?php echo $this->escapeHtml($package->getCode()->getValue()); ?></td>
                <td><?php echo $this->escapeHtml($package->getParticipant()->getFullName()); ?></td>
                <td>
                    <?php
                    $bd = $package->getParticipant()->getBirthday();
                    echo ($bd ? $bd->format('d.m.Y') : '-');
                    ?>
                </td>
                <td><a class="btn btn-default" href="<?php echo $this->url('onsite/package', array('action' => 'detail', 'id' => $package->getId())); ?>">Register</a></td>
            </tr>
            <?php endforeach;
            if(empty($results)): ?>
            <tr>
                <td colspan="5" class="text-center gray">No packages found</td>
            </tr>
            <?php endif; ?>
        </tbody>
    </table>
<?php endif; ?>