<?php
// module/Catalogue/view/pre-registration/product/index.phtml:

$title = 'EJC 2015 Pre Registration';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
foreach ($products as $product) : 
    if(count($product->getPrices()) == 0):
        error_log('VIEW: got '.count($product->getPrices()).' prices for product id: '.$product->id);
        continue;
    endif;
?>
<div class="product-container">
    <div class="add-to-cart">
        <p class="price">
            <?php echo $product->getPrice()->charge.",- €"; ?>
        </p>
        <p class="product-detail">
            <a href="<?php echo $this->url('product', array('action'=>'view','id' => $product->id));?>"><?php echo $this->translate('product detail'); ?></a>
        </p>
    </div>
    <h3><?php echo $product->name; ?></h3>
    <p><?php echo $product->shortDescription; ?></p>
    
    <?php #$NextPriceDate = \DateTime::createFromFormat('Y-m-d H:i:s', $product->getNextPrice()->validFrom); ?>
    
</div>
<hr />

<?php endforeach; ?>