<?php

$this->headTitle($product->name);
?>
<a href="<?php echo $this->url('product');?>"><?php echo $this->translate('back to Overview'); ?></a>
<h1><?php echo $this->escapeHtml($product->name); ?></h1>
<?php
if(count($product->getPrices()) == 0):
?>
<p class="desc-short">This product is unavailable</p>
<?php
else:
?>
<p class="desc-short"><?php echo $product->shortDescription; ?></p>
<div class="product-view">
    <div class="product-image"><img src="/img/no-available-image.png" alt="No available image" width="200"></div>
    <div class="desc-long"><?php echo $product->longDescription; ?></div>
    <div class="clearfix"></div>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'shoppingcart',
        array(
            'action' => 'add',
        )
    ));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('Product_id'));
    for($i = 0; $i<$form->getVariantCounter(); $i++) {
        echo $this->formRow($form->get('variant_'.$i));
    }
    ?>
    <div class="product-price-div">
        <span class="product-price"><?php echo $product->getPrice()->charge.",- €"; ?></span>    
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
<?php
endif;
?>