<?php

$title = 'Edit Sub Product of '.$product->getName();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/product-package',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('Product_id'));
echo $this->formRow($form->get('SubProduct_id'));
echo $this->formRow($form->get('active'));
echo $this->formRow($form->get('amount'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options);?>">Cancel</a>
<?php
echo $this->form()->closeTag();