<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Buyer';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('buyer', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('firstname'));
echo $this->formRow($form->get('surname'));
echo $this->formRow($form->get('email'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();