<?php
    $ejc_with_year = "EJC 2016";
    $ejc_with_number = "39th European Juggling Convention";
    $ejc_info_mail = "info@ejc2016.org";
    $ejc_website = "http://www.ejc2016.org";
?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .header, .footer {
            	width: 100%;
            	text-align: center;
            	padding: 1em;
            }
            .header {
            	margin-top: 0px;
            	background-color: #85b32a;
            	color: #fff;
            }
            .clear-both {
                clear: both;
            }
            .header > a {
            	color: #fff;
            	font-weight: bold;
            	text-decoration: none;
            }
            .footer {
            	background-color: #eeeeee;
            }
        </style>
    </head>
    <body>
        <div class='header'>EJC 2016 - 30.07.2016 - 07.08.2016 in Almere, The Netherlands - <a href='http://www.ejc2016.org'>www.ejc2016.org</a></div>
        <?php $participant = $package->getParticipant(); ?>
        
        <p>Dear <?php echo $participant->getFirstname().' '.$participant->getSurname(); ?>,</p>
        <p>thank you again for registering for EJC 2016.</p>
        <p>First of all, please check your date of birth and your name on the e-ticket if they fit with your passport or identity card. If not please send an email with your order number and the updated data to prereg@eja.net. After we changed the data you will receive the up to date e-ticket.</p>

        <p>Attached to this email, you can find your e-ticket. To read the text on the e-ticket in another language for a better understanding visit <?php echo $this->url('info', array('action' => 'e-ticket')); ?>.</p>
        <p>Print this ticket and never give it to a third person. Sign the disclaimer. Bring this ticket together with your valid ID card to the EJC and present them at the registration desk. To be able to read the documents, you need to install Adobe Acrobat Reader, which you can download here: <a href="http://get.adobe.com/en/reader">http://get.adobe.com/en/reader</a>.</p>
        <p>For the latest information about EJC 2016, stay tuned to www.ejc2016.org. If you have any further questions concerning your EJC 2016 ticket, please contact the prereg-coordinator via <a href="mailto:prereg@eja.net">prereg@eja.net</a>.</p>
        <p>We wish you a pleasant journey and we are looking forward to a great convention.</p>
        <p>Best regards,<br />
        Your European Juggling Association and the EJC 2016 organisers</p>
    </body>
</html>