<?php

$this->headTitle('EJC Registration System');
?>

<div class="jumbotron">
    <h1>
        <?php echo $this->escapeHtml('Welcome to the'); ?>
        <br />
        <span class="green"><?php echo $this->escapeHtml('EJC Registration System'); ?></span>
    </h1>
    
    <p>In 2015 the European Juggling Convention (EJC) will take place in Bruneck (Italy). You can help the orga team by register your ticket and pay early.</p>

    <p>This site provides a shop to purchase ticket to take part at the EJC 2015.</p>

    <ul>
        <li>You can choose your language at the top right.</li>
        <li>You can login with your data to change your order.</li>
        <li>Here you can look at the <a href="<?php echo $this->url('product') ?>">product list</a></li>
        <li>Your <a href="<?php echo $this->url('order') ?>">shopping cart</a> shows the chosen products.</li>
    </ul>
</div>