<?php
/* pizza would be really nice */

$title = 'Enter refund for order '.$order->getCode()->getValue();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/refund', array(
    'action' => 'enter', 
    'id' => $order->getId()
    )));
$form->prepare();

echo $this->form()->openTag($form); ?>
<?php 
echo $this->formHidden($form->get('id')); ?>
<table class="table table-striped">
    <tr>
        <th>Order Amount</th>
        <td><?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?></td>
    </tr>
    <tr>
        <th>Refund Amount</th>
        <td><?php echo $this->currencyFormat($order->getPrice('refund'), 'EUR', null, 'de_DE'); ?></td>
    </tr>
</table>
<div class="row">
    <div class="col-md-12">
        <p><?php echo $this->formRow($form->get('amount')); ?></p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">

        <?php 
        echo $this->formHidden($form->get('csrf'));
        echo $this->formSubmit($form->get('submit'));
        ?>
        <a href="<?php echo $this->url('admin/refund', array()); ?>">Cancel</a>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
