<?php
/* pizza would be really nice */

$title = 'Refund pending ('.count($orders).')';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Order info</th>
        <th>Buyer</th>
        <th>Payment type</th>
        <th>Order amount</th>
        <th>Refund amount</th>
        <th>Status</th>
        <th></th>
    </tr>
    <?php foreach($orders as $order): ?>
    <tr>
        <td>
            <?php echo $order->getCode()->getValue(); ?>
            <br />
            <?php echo $order->getCreated()->format('d.m.Y H:i:s'); ?>
        </td>
        <td>
            <?php echo $order->getBuyer()->getFirstname().' '.$order->getBuyer()->getSurname(); ?>
            <br />
            <a href="mailto:<?php echo $order->getBuyer()->getEmail(); ?>"><?php echo $order->getBuyer()->getEmail(); ?></a>
        </td>
        <td>
            <?php echo $order->getPaymentType()->getName(); ?>
        </td>
        <td>
            <?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?>
        </td>
        <td>
            <?php echo $this->currencyFormat($order->getPrice('refund'), 'EUR', null, 'de_DE'); ?>
        </td>
        <td>
            <?php echo $order->getPaymentStatus(); ?>
        </td>
        <td>
            <div class="navbar pull-right">
                <ul class="nav nav-pills">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <span>Tools<span class="caret"></span></span>
                        </a>
                        <ul id="page_2" class="dropdown-menu">
                            <li>
                                <a href="<?php echo $this->url('admin/order', array('action' => 'detail', 'id' => $order->getId()));?>"><?php echo $this->translate('order detail'); ?></a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('admin/refund', array('action' => 'enter', 'id' => $order->getId()));?>"><?php echo $this->translate('enter refund'); ?></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </td>
    </tr>
    <?php endforeach; ?>
</table>