<table class="table">
<tr>
    <th></th>
    <?php foreach($agegroups as $agegroup) : ?>
        <th><?php echo $agegroup->getName().' ('.$agegroup->getAgegroup()->format('d.m.Y').')'; ?></th>
    <?php endforeach; ?>
    <th>no Agegroup</th>
</tr>
<?php foreach ($deadlines as $deadline) : ?>
<tr>
    <th>
        <?php echo $deadline->getDeadline()->format('d.m.Y H:i:s'); ?>
    </th>
    <?php foreach($agegroups as $agegroup) : ?>
        <td>
        <?php foreach($product->getProductPrices() as $price):
            if(
                $price->getAgegroup() != null && 
                $price->getAgegroup()->getId() == $agegroup->getId() && 
                $price->getDeadline() != null && 
                $price->getDeadline()->getId() == $deadline->getId()): ?>
                <?php echo $this->currencyFormat($price->getCharge(), 'EUR', null, 'de_DE'); ?>
                <a href="<?php echo $this->url('admin/product-price', array('action' => 'edit', 'id' => $price->getId())) ?>"><i class="fa fa-edit"></i></a>
                <a href="<?php echo $this->url('admin/product-price', array('action' => 'delete', 'id' => $price->getId())) ?>"><i class="fa fa-remove"></i></a>
            <?php endif;
        endforeach; ?>
        </td>
    <?php endforeach; ?>
    <td>
    <?php foreach($product->getProductPrices() as $price):
        if(
            $price->getAgegroup() == null &&
            $price->getDeadline() != null && 
            $price->getDeadline()->getId() == $deadline->getId()): ?>
            <?php echo $this->currencyFormat($price->getCharge(), 'EUR', null, 'de_DE'); ?>
            <a href="<?php echo $this->url('admin/product-price', array('action' => 'edit', 'id' => $price->getId())) ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('admin/product-price', array('action' => 'delete', 'id' => $price->getId())) ?>"><i class="fa fa-remove"></i></a>
        <?php endif; 
    endforeach;?>
    </td>
</tr>
<?php endforeach; ?>
<tr>
    <th>no Deadline</th>
    <?php foreach($agegroups as $agegroup) : ?>
        <td>
        <?php foreach($product->getProductPrices() as $price):
            if(
                $price->getAgegroup() != null && 
                $price->getAgegroup()->getId() == $agegroup->getId() && 
                $price->getDeadline() == null): ?>
                <?php echo $this->currencyFormat($price->getCharge(), 'EUR', null, 'de_DE'); ?>
                <a href="<?php echo $this->url('admin/product-price', array('action' => 'edit', 'id' => $price->getId())) ?>"><i class="fa fa-edit"></i></a>
                <a href="<?php echo $this->url('admin/product-price', array('action' => 'delete', 'id' => $price->getId())) ?>"><i class="fa fa-remove"></i></a>
            <?php endif;
        endforeach; ?>
        </td>
    <?php endforeach; ?>
    <td>
    <?php foreach($product->getProductPrices() as $price):
        if($price->getAgegroup() == null):
            error_log('agegroup is null for '.$price->getCharge());
        endif; ?>
        <?php if($price->getDeadline() == null):
            error_log('deadline is null for '.$price->getCharge());
        endif; ?>
        <?php if(
            $price != null &&
            $price->getAgegroup() == null && 
            $price->getDeadline() == null): ?>
            <?php error_log('found charge with do agegroup and no deadline: '.$price->getCharge()); ?>
            <?php echo $this->currencyFormat($price->getCharge(), 'EUR', null, 'de_DE'); ?>
            <a href="<?php echo $this->url('admin/product-price', array('action' => 'edit', 'id' => $price->getId())) ?>"><i class="fa fa-edit"></i></a>
            <a href="<?php echo $this->url('admin/product-price', array('action' => 'delete', 'id' => $price->getId())) ?>"><i class="fa fa-remove"></i></a>
        <?php endif; ?>
    <?php endforeach; ?>
    </td>
</tr>
</table>