<?php

if($emptycart) :
    $title = $this->translate('Your Shopping Cart is empty now');
    $this->headTitle($title);
    $this->headMeta()->appendHttpEquiv('Refresh', '3;URL='.$this->url('product'));?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>You are being redirected, please click <a href="<?php echo $this->url('product') ?>">here</a> if your browser does not redirect you.</p>
<?php 
else:
    $title = $this->translate('Empty your Shopping Cart and My Person list');
    $this->headTitle($title);
    ?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>Are you sure that you want to empty your shopping cart and your My Person list?</p>
    
    <?php
    #$obj = $form->getObject();
    $form->setAttribute('action', $this->url('cart', array('action' => 'reset')))
          ->prepare();

    echo $this->form()->openTag($form);

    echo $this->formHidden($form->get('csrf'));
    echo $this->formElement($form->get('submit')); ?>

    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>

    <?php echo $this->form()->closeTag(); ?>

<?php endif;


