<?php

$title = 'Set status to ordered for item '.$item->getCode()->getValue();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<p>Do you really want to set the status to <strong>ordered</strong> for the item <?php echo $item->getCode()->getValue(); ?>?</p>
<?php
$url = $this->url('admin/item', array(
    'action' => 'ordered',
    'id'     => $item->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $item->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-warning" id="submitbutton" />
    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
</div>
</form>