<?php

$title = 'Set status to zero ok for item '.$item->getName();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<p>Do you really want to set the status to <strong>0 € OK</strong> for the item <?php echo $item->getName(); ?>?</p>
<?php
$url = $this->url('admin/item', array(
    'action' => 'zero-ok',
    'id'     => $item->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $item->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-warning" id="submitbutton" />
    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
</div>
</form>