<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Deadline';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/price-limit', array('action' => 'addDeadline')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('value'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/price-limit');?>">Cancel</a>
<?php
echo $this->form()->closeTag();