<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Price Limit Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/price-limit', array('action'=>'addDeadline'));?>">Add deadline</a> |
    <a href="<?php echo $this->url('admin/price-limit', array('action'=>'addAgegroup'));?>">Add agegroup</a> |
    <a href="<?php echo $this->url('admin/price-limit', array('action'=>'addCounter'));?>">Add counter</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($limits as $limit) : ?>
    <tr>
        <td><?php echo $limit->getType().': '.$limit->getValue(); ?></td>
        <td>
            <a href="<?php echo $this->url('admin/price-limit', array('action'=>'edit' . ucfirst($limit->getType()), 'id' => $limit->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
            <a href="<?php echo $this->url('admin/price-limit', array('action'=>'copy' . ucfirst($limit->getType()), 'id' => $limit->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
            <a href="<?php echo $this->url('admin/price-limit', array('action'=>'delete', 'id' => $limit->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>