<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Price Limit Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/price-limit', array('action'=>'add'));?>">Add new price limit</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($limits as $limit) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($limit->name);?></td>
        <td>
            <a href="<?php echo $this->url('admin/price-limit', array('action'=>'edit', 'id' => $product->id));?>"><?php echo $this->translate('Edit'); ?></a>
            <a href="<?php echo $this->url('admin/price-limit', array('action'=>'copy', 'id' => $product->id));?>"><?php echo $this->translate('Copy'); ?></a>
            <a href="<?php echo $this->url('admin/price-limit', array('action'=>'delete', 'id' => $product->id));?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>