<?php
// module/PreReg/view/pre-registration/product/index.phtml:

$title = 'Forgot Password? No Problem!';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    Give us the email address which you registered. We will generate a 
    <strong>password reset link</strong> and send it to your email address with 
    which you will be able to reset your password. This link will be 
    <strong>valid for 2h</strong>.
</p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'forgot-password')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('product');?>">Cancel</a>
<?php
echo $this->form()->closeTag();