<?php
// module/PreReg/view/pre-registration/product/index.phtml:

$title = 'Registration';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'register')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('password2'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="/">Cancel</a>
<?php
echo $this->form()->closeTag();