<?php
// module/PreReg/view/pre-registration/product/index.phtml:

$title = 'Reset Password';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'reset-password')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('password1'));
echo $this->formRow($form->get('password2'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('product');?>">Cancel</a>
<?php
echo $this->form()->closeTag();