<?php
$this->headTitle('EJC Registration System');
?>

<h3>
    <span class="green"><?php echo $this->escapeHtml('ERS Onsite Registration'); ?></span>
</h3>
<div class="row">
    <div class="col-lg-12">

    </div>
</div>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('onsite', array('action' => 'search')));
$form->prepare();

echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-xs-8 input-group-lg">
        <?php 
        echo $this->formHidden($form->get('csrf'));
        echo $this->formRow($form->get('q')); 
        ?>
    </div>
    <div class="col-xs-4">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<div class="row">
    <div class="col-xs-4 col-xs-offset-8">
        <a class="btn btn-lg btn-warning" href="market://search?q=i-nigma">QR-Code</a>
    </div>
</div>
