<?php

$title = 'Delete Deadline';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php if(count($productprices) != 0 || count($paymenttypes) != 0): ?>
    <?php if(count($productprices) != 0): ?>
    <p>Please delete these ProductPrices according to this deadline first.</p>

    <ul>
    <?php foreach($productprices as $price): ?>
    <li>
        <?php echo $price->getProduct()->getName().': ';?>
        <?php echo $this->currencyFormat($price->getCharge(), 'EUR', null, 'de_DE'); ?>
    </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
    <?php if(count($paymenttypes) != 0): ?>
    <p>Please delete these PaymentTypes according to this deadline first.</p>


    <ul>
    <?php foreach($paymenttypes as $type): ?>
    <li>
        <?php echo $type->getName(); ?>
    </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
    
<?php else: ?>
<p>Are you sure that you want to delete price limit
    <strong><?php echo $deadline->getDeadline()->format('Y-m-d H:i:s'); ?></strong>?
</p>
<?php
$url = $this->url('admin/deadline', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $deadline->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/deadline');?>">Cancel</a>
</div>
</form>
<?php endif; ?>