<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Payment Type';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/payment-type', array('action' => 'addBankTransfer')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));

echo $this->formRow($form->get('name'));
/*echo $this->formLabel($form->get('name'));
echo $this->formElement($form->get('name'));
echo $this->formElementErrors($form->get('name'));*/

echo $this->formRow($form->get('logo-upload'));
/*echo $this->formLabel($form->get('logo-upload'));
echo $this->formElement($form->get('logo-upload'));
echo $this->formElementErrors($form->get('logo-upload'));*/

echo $this->formRow($form->get('shortDescription'));
/*echo $this->formLabel($form->get('shortDescription'));
echo $this->formElement($form->get('shortDescription'));
echo $this->formElementErrors($form->get('shortDescription'));*/

echo $this->formRow($form->get('longDescription'));
/*echo $this->formLabel($form->get('longDescription'));
echo $this->formElement($form->get('longDescription'));
echo $this->formElementErrors($form->get('longDescription'));*/

echo $this->formRow($form->get('fixFee'));
/*echo $this->formLabel($form->get('fixFee'));
echo $this->formElement($form->get('fixFee'));
echo $this->formElementErrors($form->get('fixFee'));*/

echo $this->formRow($form->get('percentageFee'));
/*echo $this->formLabel($form->get('percentageFee'));
echo $this->formElement($form->get('percentageFee'));
echo $this->formElementErrors($form->get('percentageFee'));*/

echo $this->formRow($form->get('activeFrom'));
/*echo $this->formLabel($form->get('activeFrom'));
echo $this->formElement($form->get('activeFrom'));
echo $this->formElementErrors($form->get('activeFrom'));*/

echo $this->formRow($form->get('activeUntil'));
/*echo $this->formLabel($form->get('activeUntil'));
echo $this->formElement($form->get('activeUntil'));
echo $this->formElementErrors($form->get('activeUntil'));*/

echo $this->formRow($form->get('days2pay'));
/*echo $this->formLabel($form->get('days2pay'));
echo $this->formElement($form->get('days2pay'));
echo $this->formElementErrors($form->get('days2pay'));*/

echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/payment-type');?>">Cancel</a>
<?php
echo $this->form()->closeTag();