<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Payment Type (Cheque)';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/payment-type', array('action' => 'addCheque')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('visible'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('shortDescription'));
echo $this->formRow($form->get('longDescription'));
echo $this->formRow($form->get('explanation'));
echo $this->formRow($form->get('fixFee'));
echo $this->formRow($form->get('percentageFee'));
echo $this->formRow($form->get('activeFrom_id'));
echo $this->formRow($form->get('activeUntil_id'));
echo $this->formRow($form->get('days2pay'));

echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/payment-type');?>">Cancel</a>
<?php
echo $this->form()->closeTag();