<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Payment Type';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/payment-type', array('action' => 'addBankTransfer')));
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>

<div class="form-element">
    <?php $fileElement = $form->get('image-file'); ?>
    <?php echo $this->formLabel($fileElement); ?>
    <?php echo $this->formFile($fileElement); ?>
    <?php echo $this->formElementErrors($fileElement); ?>
</div>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/payment-type');?>">Cancel</a>
<?php
echo $this->form()->closeTag();