<?php

$title = 'Delete Payment Type';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if($orders != null && count($orders) > 0): ?>
    <p>Payment types with which orders have been made can't be deleted.</p>
    <a href="<?php echo $this->url('admin/payment-type');?>">Back</a>
<?php else: ?>
    <p>Are you sure that you want to delete payment type
        <strong><?php echo $paymenttype->getName().' ('.$paymenttype->getType().')'; ?></strong>?
    </p>
    <?php
    $url = $this->url('admin/payment-type', array(
        'action' => 'delete',
        'id'     => $this->id,
    ));
    ?>
    <form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $paymenttype->getId(); ?>" />
        <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
        <a href="<?php echo $this->url('admin/payment-type');?>">Cancel</a>
    </div>
    </form>
<?php endif; ?>