<?php
$form = $this->form;
$obj = $form->getObject();
switch($obj->getType()) {
    case 'sepa':
        $title = 'Details for Sepa Bank Account: '.$obj->getName();
        break;
    case 'ipayment':
        $title = 'Details for iPayment Account: '.$obj->getName();
        break;
    case 'paypal':
        $title = 'Details for Paypal Account: '.$obj->getName();
        break;
    default:
        $title = 'Details for Account (type unknown): '.$obj->getName();
        break;
}

$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form->setAttribute('action', $this->url('admin/payment-type', array('action' => 'detail', 'id' => $obj->getId())));
$form->prepare();

echo $this->form($form);
