<?php
// module/Album/view/album/album/add.phtml:

$title = 'Edit Payment Type';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/payment-type',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));

echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('visible'));
echo $this->formRow($form->get('preselected'));
echo $this->formRow($form->get('currency_id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('type'));
echo $this->formRow($form->get('short_description'));
echo $this->formRow($form->get('long_description'));
echo $this->formRow($form->get('explanation'));
echo $this->formRow($form->get('fix_fee'));
echo $this->formRow($form->get('percentage_fee'));
echo $this->formRow($form->get('active_from_id'));
echo $this->formRow($form->get('active_until_id'));
echo $this->formRow($form->get('days2pay'));

echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/payment-type');?>">Cancel</a>
<?php
echo $this->form()->closeTag();