<?php
// module/Album/view/album/album/add.phtml:

$title = 'Edit Deadline';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/payment-type',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('paymenttype'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/payment-type');?>">Cancel</a>
<?php
echo $this->form()->closeTag();