<?php

$title = 'Payment Type Overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Order</th>
        <th>Visible</th>
        <th>Name</th>
        <th>Type</th>
        <th>Period</th>
        <th class="text-right">
            <a class="btn btn-success" href="<?php echo $this->url('admin/payment-type', array('action'=>'add'));?>"><i class="fa fa-plus"></i> Payment Type</a>
        </th>
    </tr>
<?php foreach ($paymenttypes as $paymenttype) : ?>
    <tr>
        <td><?php echo $paymenttype->getPosition(); ?></td>
        <td>
            <?php if($paymenttype->getVisible()) : ?>
                <i class="fa fa-eye"></i>
            <?php else: ?>
                <i class="fa fa-eye-slash"></i>
            <?php endif; ?>
        </td>
        <td><?php echo $this->escapeHtml($paymenttype->getName()); ?></td>
        <td><?php echo $this->escapeHtml($paymenttype->getType()); ?></td>
        <td>
            <?php if($paymenttype->getActiveFrom() == null) : ?>
               no Deadline 
            <?php else: ?>
            <?php echo $paymenttype->getActiveFrom()->getDeadline()->format('Y-m-d H:i:s'); ?>
            <?php endif; ?>
            <?php echo ' - '; ?>
            <?php if($paymenttype->getActiveUntil() == null) : ?>
               no Deadline 
            <?php else: ?>
            <?php echo $paymenttype->getActiveUntil()->getDeadline()->format('Y-m-d H:i:s'); ?>
            <?php endif; ?>
        </td>
        <td class="text-right">
            <a class="btn btn-default" href="<?php echo $this->url('admin/payment-type', array('action'=>'edit', 'id' => $paymenttype->getId()));?>" title="edit payment type"><i class="fa fa-edit"></i></a>
            <a class="btn btn-default" href="<?php echo $this->url('admin/payment-type', array('action'=>'detail', 'id' => $paymenttype->getId()));?>" title="details for this payment type"><i class="fa fa-search"></i></a>
            <a class="btn btn-default" href="<?php echo $this->url('admin/payment-type', array('action'=>'format', 'id' => $paymenttype->getId()));?>" title="add statement format"><i class="fa fa-bars"></i></a>
            <a class="btn btn-default" href="<?php echo $this->url('admin/payment-type', array('action'=>'uploads', 'id' => $paymenttype->getId()));?>" title="upload csv"><i class="fa fa-upload"></i></a>
            <a class="btn btn-danger" href="<?php echo $this->url('admin/payment-type', array('action'=>'delete', 'id' => $paymenttype->getId()));?>" title="delete payment type"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>