<?php

$title = 'Payment Type Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/payment-type', array('action'=>'addBankTransfer'));?>">Add Payment Type (Bank Transfer)</a><br />
    <a href="<?php echo $this->url('admin/payment-type', array('action'=>'addCreditCard'));?>">Add Payment Type (Credit Card)</a><br />
    <a href="<?php echo $this->url('admin/payment-type', array('action'=>'addPayPal'));?>">Add Payment Type (PayPal)</a><br />
    <a href="<?php echo $this->url('admin/payment-type', array('action'=>'addCheque'));?>">Add Payment Type (Cheque)</a><br />
</p>

<table class="table">
    <tr>
        <th>Order</th>
        <th>Visible</th>
        <th>Name</th>
        <th>Type</th>
        <th>Logo</th>
        <th>Period</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($paymenttypes as $paymenttype) : ?>
    <tr>
        <td><?php echo $paymenttype->getPosition(); ?></td>
        <td>
            <?php if($paymenttype->getVisible()) : ?>
                <i class="fa fa-eye"></i>
            <?php else: ?>
                <i class="fa fa-eye-slash"></i>
            <?php endif; ?>
        </td>
        <td><?php echo $paymenttype->getName(); ?></td>
        <td><?php echo $paymenttype->getType(); ?></td>
        <td>
            
            <?php if($paymenttype->getLogo() != ''): ?>
            <p>
                <img src="<?php echo $this->serverUrl('/media/'); ?><?php echo $paymenttype->getLogo(); ?>" alt="no logo" />
            </p>
            <p>
                <a href="<?php $this->url('admin/payment-type', array('action' => 'editLogo', 'id' => $paymenttype->getId())); ?>">edit Logo</a>
                <br />
                <a href="<?php $this->url('admin/payment-type', array('action' => 'deleteLogo', 'id' => $paymenttype->getId())); ?>">delete Logo</a>
            </p>
            <?php else: ?>
            <p>
                <span>no logo</span>
            </p>
            <p>
                <a href="<?php $this->url('admin/payment-type', array('action' => 'addLogo', 'id' => $paymenttype->getId())); ?>">add Logo</a>
            </p>
            <?php endif; ?>
        </td>
        <td>
            <?php if($paymenttype->getActiveFrom() == null) : ?>
               no Deadline 
            <?php else: ?>
            <?php echo $paymenttype->getActiveFrom()->getDeadline()->format('Y-m-d H:i:s'); ?>
            <?php endif; ?>
            <?php echo ' - '; ?>
            <?php if($paymenttype->getActiveUntil() == null) : ?>
               no Deadline 
            <?php else: ?>
            <?php echo $paymenttype->getActiveUntil()->getDeadline()->format('Y-m-d H:i:s'); ?>
            <?php endif; ?>
        </td>
        <td>
            <a href="<?php echo $this->url('admin/payment-type', array('action'=>'edit'.$paymenttype->getType(), 'id' => $paymenttype->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
            <a href="<?php echo $this->url('admin/payment-type', array('action'=>'copy'.$paymenttype->getType(), 'id' => $paymenttype->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
            <a href="<?php echo $this->url('admin/payment-type', array('action'=>'delete', 'id' => $paymenttype->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>