<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Payment Type Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/payment-type', array('action'=>'addBankTransfer'));?>">Add Payment Type (Bank Transfer)</a><br />
    <a href="<?php echo $this->url('admin/payment-type', array('action'=>'addCreditCard'));?>">Add Payment Type (Credit Card)</a><br />
    <a href="<?php echo $this->url('admin/payment-type', array('action'=>'addPayPal'));?>">Add Payment Type (PayPal)</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Logo</th>
        <th>Period</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($paymenttypes as $paymenttype) : ?>
    <tr>
        <td><?php echo $paymenttype->getName(); ?></td>
        <td><img src="<?php echo $this->serverUrl('/media/'); ?><?php echo $paymenttype->getLogo(); ?>" alt="no logo" /></td>
        <td><?php 
            echo $paymenttype->getActiveFrom()->format('Y-m-d H:i:s');
            echo ' - ';
            echo $paymenttype->getActiveUntil()->format('Y-m-d H:i:s');
        ?></td>
        <td>
            <a href="<?php echo $this->url('admin/payment-type', array('action'=>'edit'.$paymenttype->getType(), 'id' => $paymenttype->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
            <a href="<?php echo $this->url('admin/payment-type', array('action'=>'copy'.$paymenttype->getType(), 'id' => $paymenttype->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
            <a href="<?php echo $this->url('admin/payment-type', array('action'=>'delete', 'id' => $paymenttype->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>