<?php

$title = 'Credit Card Error';
$this->headTitle($title);
?>

<div class="jumbotron">
    <h1>We were not able to finish your credit card payment</h1>
    <p>You can restart the credit card payment via the
    <a href="<?php echo $this->url(
            'order',
            array(
                'action' => 'view',
                'hashkey' => $order->getHashKey(),
                )); ?>">
            order overview
        </a>.</p>
        <p>We sent this link to your email address address, too.</p>
</div>