<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'My Shopping Cart';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<div class="order-steps">
    <div class="order-step"><span class="order-step-no">1</span> <a href="<?php echo $this->url('order'); ?>">My cart</a></div>
    <div class="order-step"><span class="order-step-no">2</span> <a href="<?php echo $this->url('order', array('action' => 'register')); ?>">Register</a></div>
    <div class="order-step"><span class="order-step-no">3</span> <a href="<?php echo $this->url('order', array('action' => 'payment')); ?>">Payment</a></div>
    <div class="order-step active"><span class="order-step-no">4</span> <a href="<?php echo $this->url('order', array('action' => 'checkout')); ?>">Checkout</a></div>
</div>
<div class="clear-both"></div>
<div class="order-info order-info-left">
    <h1>Purchaser</h1>
    <h2>Prename Surname</h2>
    <p>The purchaser will be able to download all eTickets for all registered participants. If you have provided an email address for a participant this participant will be informed once the ticket is payed and will be able to download the eTicket on his own aswell.</p>
    <h3>We will send all information to: purchaser@email.com</h3>
</div>
<div class="order-info order-info-right">
    <h1>Payment</h1>
    <h3>You have chosen payment type: Bank Transfer</h3>
    <p>After successfull purchase you will see the bank account data to transfer the money to. When we matched your payment to your order you will be informed and can download your eTickets.</p>
    <h3>You have chosen payment type: Credit Card</h3>
    <p>After purchase you will see the credit card formular. After successful payment you will be able to download your eTickets.</p>
    <h3>You have chosen payment type: PayPal</h3>
    <p>After purchase you will be redirected to a PayPal page. After successful payment you will be able to download your eTickets.</p>
    
    
</div>
<div class="clear-both"></div>
<div>
    <h1>Shopping cart</h1>
    <table class="table table-bordered">
        <tr>
            <th class="col-description">Description</th>
            <th class="col-belongsto">belongs to</th>
            <!--<th>amount</th>-->
            <th>price</th>
            <th class="col-tools"></th>
        </tr>
        <tr>
            <td>Week Ticket Adult</td>
            <td>Andreas Nitsche (29.03.1985)</td>
            <td class="col-price">120,00 €</td>
            <td>
            </td>
        </tr>
    </table>
 </div>
 <div class="cart-sum">
     <table class="table sum-table">
         <tr>
             <td class="col-sumdesc  total-sum">Sum</td>
             <td class="col-sum total-sum">122,04 €</td>
         </tr>
         <tr>
             <td>Payment cost included (PayPal)</td>
             <td class="col-sum">2,04 €</td>
         </tr>
         <tr>
             <td>VAT included (22%)</td>
             <td class="col-sum">26,40 €</td>
         </tr>
     </table>
 </div>

<div class="clear-both"></div>
<div class="checkout">
    <a class="btn btn-lg btn-primary" href="#">Buy now</a>
</div>