<?php

$title = $this->translate('My Shopping Cart');
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$partial = array('partial/checkout-nav.phtml', 'checkout_nav');
$this->navigation()
        ->menu('checkout_nav')
        ->setPartial($partial);
echo $this->navigation()
        ->menu('checkout_nav')
        ->render(); 
?>
<div class="clear-both"></div>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('order', array('action' => 'checkout')));
    $form->prepare();
?>
<div class="row">
    <div class="col-md-6">
        <div class="order-info">
            <h1>Buyer</h1>
            <?php $buyer = $order->getBuyer(); ?>
            <?php if($buyer) : ?>
                <h2><?php echo $buyer->getFirstname().' '.$buyer->getSurname(); ?></h2>
                <p><?php echo $this->translate('The buyer will receive all E-Tickets for all registered participants. If you have provided an email address per participant, this participant will be informed once the ticket is paid and will be able to download the E-Ticket on his own as well.'); ?></p>
                <h3><?php echo $this->translate('We will send all information to:').' '.$buyer->getEmail(); ?></h3>
            <?php else: ?>
                <?php $form->get('submit')->setAttribute('disabled', 'disabled'); ?>
                <a href="<?php echo $this->url('order', array('action' => 'buyer')); ?>"><?php echo $this->translate('choose Buyer'); ?></a>
            <?php endif; ?>
        </div>
    </div>
    <div class="col-md-6">
        <div class="order-info">
            <h1>Payment</h1>
            <?php $paymenttype = $order->getPaymentType(); ?>
            <?php if($paymenttype) : ?>
                <h3><?php echo $paymenttype->getName(); ?></h3>
                <p><?php echo $paymenttype->getExplanation(); ?></p>
            <?php else: ?>
                <?php $form->get('submit')->setAttribute('disabled', 'disabled'); ?>
                <a href="<?php echo $this->url('order', array('action' => 'payment')); ?>"><?php echo $this->translate('choose paymenttype'); ?></a>
            <?php endif; ?>
            <!--<h3>Bank Transfer</h3>
            <p>After successfull purchase you will see the bank account data to transfer the money to. When we matched your payment to your order you will be informed and can download your E-Tickets.</p>
            <h3>Credit Card</h3>
            <p>After purchase you will see the credit card formular. After successful payment you will be able to download your E-Tickets.</p>
            <h3>PayPal</h3>
            <p>After purchase you will be redirected to a PayPal page. After successful payment you will be able to download your E-Tickets.</p>-->    
        </div>
    </div>
</div>
<div>
    <h1><?php echo $this->translate('Shopping Cart'); ?></h1>
        <div>
        <?php 
            $sum = 0;
            foreach ($order->getPackages() as $package) : 
                if(count($package->getItems()) == 0) {
                    continue;
                }
                $user = $package->getParticipant();
            
                if($user->getFirstname() == '' && $user->getSurname() == '') :
                    $participant = $this->translate('further items');
                else:
                    $participant = $user->getFirstname().' '.$user->getSurname().' ('.$user->getAge()->format('%Y '.$this->translate('years')).')';
                endif;
        ?>
            <div class="package">
                <h3><?php echo $participant; ?></h3>
                
                <?php if(count($package->getItems()) != 0): ?>
                <table class="table">
                    <tr>
                        <th><?php echo $this->translate('Product'); ?></th>
                        <th class="cart-amount"><?php echo $this->translate('Amount'); ?></th>
                        <th class="cart-price"><?php echo $this->translate('Price'); ?></th>
                    </tr>
                    <?php
                    $subtotal = 0;
                    foreach ($package->getItems() as $item) : 
                        if($item->hasParentItems()) {
                            continue;
                        }
                        $subtotal += $item->getPrice();
                        $sum += $item->getPrice();
                        ?>
                        <tr>
                            <td>
                                <span class="product-name"><?php echo $item->getName(); ?></span>
                                <?php 
                                $variants = array();
                                if(count($item->getItemVariants()) > 0): 
                                    $numVariants = count($item->getItemVariants());
                                    $i = 0;
                                    $var_string = '';
                                    foreach($item->getItemVariants() as $variant): 
                                        $var_string .= $variant->getName().': '.$variant->getValue(); 
                                        if(++$i != $numVariants):
                                            $var_string .= '; ';
                                        endif;
                                        $variants[\urlencode($variant->getName())] = \urlencode($variant->getProductVariantValueId());
                                    endforeach;
                                    if($var_string != ''): ?>
                                        <span class="product-variants">
                                        <?php echo '('.$var_string.')'; ?>
                                        </span>
                                    <?php endif;
                                endif;
                                if(count($item->getChildItems()) > 0):
                                    foreach($item->getChildItems() as $subItem):
                                        $numVariants = count($subItem->getItemVariants());
                                        $i = 0;
                                        $subvar_string = '';
                                        foreach($subItem->getItemVariants() as $variant):
                                            $subvar_string .= $variant->getName().': '.$variant->getValue(); 
                                            if(++$i != $numVariants):
                                                $subvar_string .= '; ';
                                            endif;
                                            $variants[\urlencode($variant->getName())] = \urlencode($variant->getProductVariantValueId());
                                        endforeach;
                                    endforeach;
                                    if($subvar_string != ''): ?>
                                        <span class="subproducts">
                                        <?php echo '('.$subvar_string.')'; ?>
                                        </span>
                                    <?php endif;
                                endif; ?>
                            </td>
                            <td><?php echo $item->getAmount(); ?></td>
                            <td><?php echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td>Subtotal:</td>
                        <td><?php echo $this->currencyFormat($subtotal, 'EUR', null, 'de_DE'); ?></td>
                    </tr>
                </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        <?php if($paymenttype) : ?>
            <table class="table sum-table">
                <tr>
                    <td>Order amount:</td>
                    <td><?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <td>Payment Charge:</td>
                    <td><?php echo $this->currencyFormat($paymenttype->calcFee($sum), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <th><span style="font-size: 18px;">Total amount:</span></th>
                    <th><span style="font-size: 18px;"><?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></span></th>
                </tr>
            </table>
        <?php endif; ?>
    </div>
 </div>


<div class="clear-both"></div>
<div class="checkout">
    <?php
        if(count($order->getItems()) == 0):
            $form->get('submit')->setAttribute('disabled', 'disabled');
        endif;
        echo $this->form()->openTag($form);
    
        if($form->get('submit')->getAttribute('disabled') == 'disabled'):
    ?>
    <div class="alert alert-danger">
        <h4><?php echo $this->translate('Please add missing information for checkout'); ?></h4>
        <?php if(count($order->getItems()) == 0) : ?>
            <p><a href="<?php echo $this->url('product'); ?>"><?php echo $this->translate('Add products'); ?></a> <?php echo $this->translate('to your shopping cart first.'); ?></p>
        <?php endif; ?>
        <?php if(!$order->getBuyer()) : ?>
            <p><?php echo $this->translate('To purchase this order'); ?> <a href="<?php echo $this->url('order', array('action' => 'buyer')); ?>"><?php echo $this->translate('choose/add a buyer'); ?></a> <?php echo $this->translate('with a valid email address.'); ?></p>
        <?php endif; ?>
        <?php if(!$order->getPaymentType()) : ?>
            <p><?php echo $this->translate('To purchase this order'); ?> <a href="<?php echo $this->url('order', array('action' => 'payment')); ?>"><?php echo $this->translate('choose a payment type'); ?></a>.</p>
        <?php endif; ?>
        
    </div>
    <?php
        else:
            ?>
            <p id="TnC">
            <?php
                #echo $this->formLabel($form->get('terms'));
                echo $this->formElement($form->get('terms'));
            ?>
                <?php echo $this->translate('I accept the'); ?> <a href="<?php echo $this->url('info', array('action' => 'terms')) ?>" class="TnC-show" target="_blank"><?php echo $this->translate('terms and conditions'); ?></a>
            </p>
            <div id="TnC-container"></div>
        <?php 
            echo $this->formElementErrors($form->get('terms')); 
        endif; ?>
            <a class="btn btn-lg btn-warning" href="<?php echo $this->url('order'); ?>"><i class="fa fa-chevron-left"></i> <?php echo $this->translate('change order'); ?></a>
        <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->formHidden($form->get('csrf'));
        echo $this->form()->closeTag(); 
    ?>
</div>
