<?php

$title = $this->translate('Resend your emails in another language');
$this->headTitle($title);
?>

<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="row">
        <h3>Sorry, this function is not implemented, yet. Please come back later.</h3>
        <h3>Entschuldigung, diese Funktion wurde noch nicht programmiert. Bitte komme später noch einmal.</h3>
        <h3>Désolé, cette fonction ne est pas encore mis en œuvre,. Se il vous plaît revenir plus tard.</h3>
        <h3>Lo sentimos, esta función no está implementada, aún. Por favor, vuelva más tarde.</h3>
        <h3>Siamo spiacenti, questa funzione non è ancora implementata,. Si prega di tornare più tardi.</h3>

    </div>
</div>