<?php

$title = 'My Shopping Cart';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 

<div class="order-steps">
    <div class="order-step active"><span class="order-step-no">1</span> <a href="<?php echo $this->url('order'); ?>">My cart</a></div>
    <div class="order-step"><span class="order-step-no">2</span> <a href="<?php echo $this->url('order', array('action' => 'register')); ?>">Register</a></div>
    <div class="order-step"><span class="order-step-no">3</span> <a href="<?php echo $this->url('order', array('action' => 'payment')); ?>">Payment</a></div>
    <div class="order-step"><span class="order-step-no">4</span> <a href="<?php echo $this->url('order', array('action' => 'checkout')); ?>">Checkout</a></div>
</div>
<div class="clear-both"></div>

<div class="checkout">
    <a class="btn btn-lg btn-primary" href="<?php echo $this->url('order', array('action' => 'register')) ?>">Checkout this Cart</a>
</div>
<div class="reset-cart">
    <a href="<?php echo $this->url('cart', array('action' => 'reset')) ?>">Reset shopping cart</a>
</div>
<div>
    <?php if(count($packages) == 1 && count($packages[0]->getItems()) == 0): ?>
        <h2>Your Shopping Cart is empty</h2>
    <?php else: ?>
    <table class="table table-bordered">
        <tr>
            <th class="col-description">Description</th>
            <th class="col-belongsto">belongs to</th>
            <!--<th>amount</th>-->
            <th>price</th>
            <th class="col-tools"></th>
        </tr>
        <?php 
        $sum = 0;
        error_log('found '.count($order->getPackages()).' package in this order');
        foreach ($order->getPackages() as $package) : 
            error_log(var_export($package,true));
            $participant = $package->getParticipant();
            
            if($participant->getPrename() == '' && $participant->getSurname() == '') :
                $participant = 'unassigned items';
            else:
                $participant = $participant->getPrename().' '.$participant->getSurname();
            endif;
        
            #if(count($package->getItems()) != 0 && $participant != 'unassigned items'): 
            if(count($package->getItems()) != 0): 
                foreach ($package->getItems() as $item) : 
                    error_log(var_export($item, true));
        ?>
        <tr>
            <td><?php echo $item->getName(); ?></td>
            <td><?php echo $participant; ?></td>
            <td class="col-price"><?php 
                #echo $item->getPrice();
                $sum += $item->getPrice();
                echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); 
            ?>
            </td>
            <td><a href="#">edit</a><a href="#">delete</a></td>
        </tr>
        <?php 
                endforeach;     
            endif;
        endforeach; ?>
        <tr>
            <td></td>
            <td class="sum-desc">Sum:</td>
            <td class="sum-price"><?php echo $this->currencyFormat($sum, 'EUR', null, 'de_DE'); ?></td>
            <td></td>
        </tr>
    </table>
    <?php endif; ?>
 </div>
 <div class="clear-both"></div>
 <div class="checkout">
     <a class="btn btn-lg btn-primary" href="<?php echo $this->url('order', array('action' => 'register')) ?>">Checkout this Cart</a>
 </div>