<?php

$title = $this->translate('My Shopping Cart');
$this->headTitle($title);
?>

<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$partial = array('partial/checkout-nav.phtml', 'checkout_nav');
$this->navigation()
        ->menu('checkout_nav')
        ->setPartial($partial);
echo $this->navigation()
        ->menu('checkout_nav')
        ->render(); 
?>

<div class="clear-both"></div>

<div class="checkout">
    <a class="btn btn-lg btn-primary" href="<?php echo $this->url('order', array('action' => 'buyer')) ?>"><?php echo $this->translate('Continue'); ?></a>
</div>
<div class="reset-cart">
    <a href="<?php echo $this->url('cart', array('action' => 'reset')) ?>"><?php echo $this->translate('Reset My Shopping Cart and My Persons'); ?></a>
</div>
    <div>
        <?php 
            $sum = 0;
            foreach ($order->getPackages() as $package) : 
                if(count($package->getItems()) == 0) {
                    continue;
                }
                $user = $package->getParticipant();
            
                if($user->getFirstname() == '' && $user->getSurname() == '') :
                    $participant = $this->translate('further items');
                    $edit_participant = false;
                else:
                    $participant = $user->getFirstname().' '.$user->getSurname().' ('.$user->getAge()->format('%Y '.$this->translate('years')).')';
                    $edit_participant = true;
                endif;
        ?>
            <div class="package">
                <h3>
                    <?php echo $participant; ?>
                    <?php if($edit_participant): ?>
                    <span style="font-size: 14px;">
                        <a href="<?php echo $this->url('participant', array('action'=>'edit', 'id' => $user->getId()));?>"><i class="fa fa-edit"></i></a>
                        <a href="<?php echo $this->url('participant', array('action'=>'delete', 'id' => $user->getId()));?>"><i class="fa fa-trash"></i></a>
                    </span>
                    <?php endif; ?>
                </h3>
                
                <?php if(count($package->getItems()) != 0): ?>
                <table class="table">
                    <tr>
                        <th><?php echo $this->translate('Product'); ?></th>
                        <th class="cart-amount"><?php echo $this->translate('Amount'); ?></th>
                        <th class="cart-price"><?php echo $this->translate('Price'); ?></th>
                        <th class="cart-tool"></th>
                    </tr>
                    <?php
                    $subtotal = 0;
                    foreach ($package->getItems() as $item) : 
                        if($item->hasParentItems()) {
                            continue;
                        }
                        $subtotal += $item->getPrice();
                        $sum += $item->getPrice();
                        ?>
                        <tr>
                            <td>
                                <span class="product-name"><?php echo $item->getName(); ?></span>
                                <?php 
                                $variants = array();
                                if(count($item->getItemVariants()) > 0): 
                                    $numVariants = count($item->getItemVariants());
                                    $i = 0;
                                    $var_string = '';
                                    foreach($item->getItemVariants() as $variant): 
                                        $var_string .= $variant->getName().': '.$variant->getValue(); 
                                        if(++$i != $numVariants):
                                            $var_string .= '; ';
                                        endif;
                                        $variants[\urlencode($variant->getName())] = \urlencode($variant->getProductVariantValueId());
                                    endforeach;
                                    if($var_string != ''): ?>
                                        <span class="product-variants">
                                        <?php echo '('.$var_string.')'; ?>
                                        </span>
                                    <?php endif;
                                endif;
                                if(count($item->getChildItems()) > 0):
                                    foreach($item->getChildItems() as $subItem):
                                        $numVariants = count($subItem->getItemVariants());
                                        $i = 0;
                                        $subvar_string = '';
                                        foreach($subItem->getItemVariants() as $variant):
                                            $subvar_string .= $variant->getName().': '.$variant->getValue(); 
                                            if(++$i != $numVariants):
                                                $subvar_string .= '; ';
                                            endif;
                                            $variants[\urlencode($variant->getName())] = \urlencode($variant->getProductVariantValueId());
                                        endforeach;
                                    endforeach;
                                    if($subvar_string != ''): ?>
                                        <span class="subproducts">
                                        <?php echo '('.$subvar_string.')'; ?>
                                        </span>
                                    <?php endif;
                                endif; ?>
                            </td>
                            <td><?php echo $item->getAmount(); ?></td>
                            <td><?php echo $this->currencyFormat($item->getPrice(), $order->getCurrency()->getShort(), null, 'de_DE'); ?></td>
                            <td>
                                <?php
                                if($participant != 'further items') :
                                    if($user->getId() != null) :
                                        $variants['participant_id'] = \urlencode($user->getId());
                                        $fragment = 'person';
                                    endif;
                                else:
                                    $agegroup = $agegroupService->getAgegroupByDate($item->getAgegroup());
                                    if($agegroup):
                                        $variants['agegroup_id'] = $agegroup->getId();
                                    else:
                                        $variants['agegroup_id'] = 0;
                                    endif;
                                    $fragment = 'agegroup';
                                endif;
                                
                                ?>
                                <a class="btn btn-default" href="<?php echo $this->url('product', 
                                        array(
                                            'action' => 'edit', 
                                            'product_id' => $item->getProductId(), 
                                            #'participant_id' => $user_id,
                                            'item_id' => $item->getId(),
                                        ),
                                        array(
                                            'query' => $variants,
                                            'fragment' => $fragment,
                                        )) ?>"><i class="fa fa-edit"></i></a>
                                <a class="btn btn-danger" href="<?php echo $this->url('product', 
                                        array(
                                            'action' => 'delete', 
                                            'product_id' => $item->getProductId(), 
                                            'item_id' => $item->getId()
                                        ),
                                        array(
                                            /*'query' => array(
                                                'participant_id' => $user_id,
                                            )*/
                                        )) ?>"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td><?php echo $this->translate('Subtotal'); ?>:</td>
                        <td><?php echo $this->currencyFormat($subtotal, $order->getCurrency()->getShort(), null, 'de_DE'); ?></td>
                        <td></td>
                    </tr>
                </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        <div>
            <table class="table sum-table">
                <tr>
                    <th><span style="font-size: 18px;"><?php echo $this->translate('Order amount'); ?>:</span></th>
                    <th><span style="font-size: 18px;"><?php echo $this->currencyFormat($order->getPrice(), $order->getCurrency()->getShort(), null, 'de_DE'); ?></span></th>
                </tr>
            </table>
        </div>
    </div>
 
 <div class="clear-both"></div>
 <div class="checkout">
     <a class="btn btn-lg btn-primary" href="<?php echo $this->url('order', array('action' => 'buyer')) ?>"><?php echo $this->translate('Continue'); ?></a>
 </div>