<?php

$title = 'My Shopping Cart';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<?php 
echo $this->navigation()
    ->menu('checkout_nav')
    ->setUlClass('nav navbar-nav navbar-checkout');
?>
<div class="clear-both"></div>

<div class="checkout">
    <a class="btn btn-lg btn-primary" href="<?php echo $this->url('order', array('action' => 'purchaser')) ?>">Checkout this Cart</a>
</div>
<div class="reset-cart">
    <a href="<?php echo $this->url('cart', array('action' => 'reset')) ?>">Reset shopping cart</a>
</div>
    <div>
        <?php 
            $sum = 0;
            foreach ($order->getPackages() as $package) : 
                if(count($package->getItems()) == 0) {
                    continue;
                }
                $user = $package->getParticipant();
            
                if($user->getFirstname() == '' && $user->getSurname() == '') :
                    $participant = 'unassigned items';
                    $edit_participant = false;
                else:
                    $participant = $user->getFirstname().' '.$user->getSurname();
                    $edit_participant = true;
                endif;
        ?>
            <div class="package">
                <h3>
                    <?php echo $participant; ?>
                    <?php if($edit_participant): ?>
                    <span style="font-size: 14px;">
                        <a href="<?php echo $this->url('participant', array('action'=>'edit', 'id' => $user->getSessionId()));?>"><?php echo $this->translate('Edit'); ?></a>
                        <a href="<?php echo $this->url('participant', array('action'=>'delete', 'id' => $user->getSessionId()));?>"><?php echo $this->translate('Delete'); ?></a>
                    </span>
                    <?php endif; ?>
                </h3>
                
                <?php if(count($package->getItems()) != 0): ?>
                <table class="table">
                    <tr>
                        <th>Product</th>
                        <th class="cart-amount">Amount</th>
                        <th class="cart-price">Price</th>
                        <th class="cart-tool"></th>
                    </tr>
                    <?php
                    $subtotal = 0;
                    foreach ($package->getItems() as $item) : 
                        $subtotal += $item->getPrice();
                        $sum += $item->getPrice();
                        ?>
                        <tr>
                            <td>
                                <span class="product-name"><?php echo $item->getName(); ?></span>
                                <span class="product-variants">
                                    <?php 
                                    $variants = array();
                                    if(count($item->getItemVariants()) > 0): 
                                    ?>
                                    (
                                    <?php 
                                    $numVariants = count($item->getItemVariants()); 
                                    $i = 0;
                                    ?>
                                    <?php foreach($item->getItemVariants() as $variant): 
                                        echo $variant->getName().': '.$variant->getValue(); 
                                        if(++$i != $numVariants):
                                            echo '; ';
                                        endif;
                                        $variants[$variant->getName()] = $variant->getProductVariantValueId();
                                    endforeach; ?>
                                    )
                                    <?php endif; ?>
                                </span>
                            </td>
                            <td><?php echo $item->getAmount(); ?></td>
                            <td><?php echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                            <td>
                                <?php 
                                if($user->getSessionId() === null) {
                                    $user_id = 0;
                                } else {
                                    $user_id = $user->getSessionId();
                                }
                                ?>
                                <a href="<?php echo $this->url('product', 
                                        array(
                                            'action' => 'edit', 
                                            'product_id' => $item->getProductId(), 
                                            'participant_id' => $user_id,
                                            'item_id' => $item->getSessionId(),
                                            #'variants' => urlencode(json_encode($variants)),
                                        ),
                                        array(
                                            'query' => $variants,
                                        )) ?>">edit</a>
                                <a href="<?php echo $this->url('product', 
                                        array(
                                            'action' => 'delete', 
                                            'product_id' => $item->getProductId(), 
                                            'participant_id' => $user_id,
                                            'item_id' => $item->getSessionId()
                                        )) ?>">delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td>Subtotal:</td>
                        <td><?php echo $this->currencyFormat($subtotal, 'EUR', null, 'de_DE'); ?></td>
                        <td></td>
                    </tr>
                </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        <div>
            <table class="table sum-table">
                <tr>
                    <th><span style="font-size: 18px;">Order amount:</span></th>
                    <th><span style="font-size: 18px;"><?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?></span></th>
                </tr>
            </table>
        </div>
    </div>
 
 <div class="clear-both"></div>
 <div class="checkout">
     <a class="btn btn-lg btn-primary" href="<?php echo $this->url('order', array('action' => 'purchaser')) ?>">Checkout this Cart</a>
 </div>