<?php

$title = 'My Shopping Cart';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
echo $this->navigation()
    ->menu('checkout_nav')
    ->setUlClass('nav navbar-nav navbar-checkout');
?>
<div class="clear-both"></div>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('order', array('action' => 'payment')));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div class="checkout">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<div>
    <?php if(count($paymenttypes) <= 0): ?>
        <h1>There are currently no payment types available</h1>
        <p>There are currently no payment options available. Please check back at a later date. Sorry!</p>
    <?php else: ?>
        <h1>Choose Payment type</h1>
        <?php echo $this->formElementErrors($form->get('paymenttype_id')); ?>
        <?php foreach($paymenttypes as $paymenttype): 
            $now = new \DateTime(); ?>
            <div class="row">
                <div class="col-lg-6 col-bordered col-payment">
                    <?php 
                    if(
                            $now->getTimestamp() < $paymenttype->getActiveUntil()->getDeadline()->getTimestamp() &&
                            $now->getTimestamp() > $paymenttype->getActiveFrom()->getDeadline()->getTimestamp()
                            ) :
                        if($order->getPaymentTypeId() != null && $order->getPaymentTypeId() == $paymenttype->getId()) :
                            $checked = true;
                        else:
                            $checked = false;
                        endif; ?>
                        <label class="payment-type">
                        <input style="display: inline;" <?php echo $checked ? 'checked="checked"' : ''; ?> type='radio' name='paymenttype_id' value='<?php echo $paymenttype->getId(); ?>' /> 
                        <?php echo $paymenttype->getName(); ?>
                        </label>
                    <?php elseif($now->getTimestamp() < $paymenttype->getActiveFrom()->getDeadline()->getTimestamp()): ?>
                    <p class="alert alert-warning">
                        <i class="fa fa-warning"></i> This payment type is not available, yet. It will be available from <?php echo $paymenttype->getActiveFrom()->getDeadline()->format('d.m.Y'); ?> until <?php echo $paymenttype->getActiveUntil()->getDeadline()->format('d.m.Y'); ?>. Please choose another payment type.
                    </p>
                    <?php else: ?>
                    <p class="alert alert-warning">
                        <i class="fa fa-warning"></i> This payment type was available until <?php echo $paymenttype->getActiveUntil()->getDeadline()->format('d.m.Y'); ?>. Please choose another payment type.
                    </p>
                    <?php endif; ?>
                    <p class="payment-desc">
                        <!--<?php echo $paymenttype->getShortDescription(); ?> <a href="<?php echo $this->url('info', array('action' => 'payment', 'id' => $paymenttype->getId()))?>">more info...</a>-->
                        <?php echo $paymenttype->getLongDescription(); ?>
                    </p>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<div class="clear-both"></div>
<div class="checkout">
    <?php 
        echo $this->formSubmit($form->get('submit'));
        echo $this->formHidden($form->get('csrf'));
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>