<?php

$title = 'My Shopping Cart';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
/*echo $this->navigation()
    ->menu('checkout_nav')
    ->setUlClass('nav navbar-nav navbar-checkout');*/
?>

<?php 
$partial = array('partial/checkout-nav.phtml', 'checkout_nav');
$this->navigation()
        ->menu('checkout_nav')
        ->setPartial($partial);
echo $this->navigation()
        ->menu('checkout_nav')
        ->render(); 
?>
<div class="clear-both"></div>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('order', array('action' => 'payment')));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div class="checkout">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<div>
    <?php if(count($paymenttypes) <= 0): ?>
        <h1>There are currently no payment types available</h1>
        <p>There are currently no payment options available. Please check back at a later date. Sorry!</p>
    <?php else: ?>
        <h1>Choose Payment type</h1>
        <?php echo $this->formElementErrors($form->get('paymenttype_id')); ?>
        <?php foreach($paymenttypes as $paymenttype):
            if(!$paymenttype->getVisible())
                continue;
            
            $checked = ($order->getPaymentTypeId() != null && $order->getPaymentTypeId() == $paymenttype->getId());
            $tooLate = false;
            $tooEarly = false;
            
            $now = new \DateTime();
            $activeFrom = $paymenttype->getActiveFrom();
            $activeUntil = $paymenttype->getActiveUntil();
            
            if($activeFrom != null && $now < $activeFrom->getDeadline())
                $tooEarly = true;
            if($activeUntil != null && $now > $activeUntil->getDeadline())
                $tooLate = true;
            ?>
            <div class="row">
                <div class="col-lg-6 col-bordered col-payment">
                    <label class="payment-type">
                        <input style="display: inline;"
                            <?php if($checked) echo 'checked="checked" '; ?>
                            <?php if($tooEarly || $tooLate) echo 'disabled="disabled" '; ?>
                               type='radio' name='paymenttype_id' value='<?php echo $paymenttype->getId(); ?>' /> 
                        <?php echo $paymenttype->getName() ?>
                        <span class="h5">(payment fee: <?php echo $this->currencyFormat($order->getPaymentFees($paymenttype), 'EUR', null, 'de_DE'); ?>)</span>
                    </label>
                    <?php if($tooEarly): ?>
                        <p class="alert alert-warning">
                            <i class="fa fa-warning"></i>
                            This payment type is not available yet.
                            It will be available from <?php echo $activeFrom->getDeadline()->format('d.m.Y'); if($activeUntil != null) { echo ' until ' . $activeUntil->getDeadline()->format('d.m.Y'); } ?>.
                            Please choose another payment type.
                        </p>
                    <?php elseif($tooLate): ?>
                        <p class="alert alert-warning">
                            <i class="fa fa-warning"></i>
                            This payment type was available until <?php echo $paymenttype->getActiveUntil()->getDeadline()->format('d.m.Y'); ?>.
                            Please choose another payment type.
                        </p>
                    <?php endif; ?>
                    <p class="payment-desc">
                        <!--<?php echo $paymenttype->getShortDescription(); ?> <a href="<?php echo $this->url('info', array('action' => 'payment', 'id' => $paymenttype->getId()))?>">more info...</a>-->
                        <?php echo $paymenttype->getLongDescription(); ?>
                    </p>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<div class="clear-both"></div>
<div class="checkout">
    <?php 
        echo $this->formSubmit($form->get('submit'));
        echo $this->formHidden($form->get('csrf'));
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>