<?php

$title = $this->translate('My Shopping Cart');
$this->headTitle($title);
?>

<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$partial = array('partial/checkout-nav.phtml', 'checkout_nav');
$this->navigation()
        ->menu('checkout_nav')
        ->setPartial($partial);
echo $this->navigation()
        ->menu('checkout_nav')
        ->render(); 
?>
<div class="clear-both"></div>
<div class="row">
    <div class="text-right col-md-3 col-md-offset-9 col-lg-3 col-lg-offset-9">
        <?php echo $this->partial('partial/currency-chooser.phtml', array('form' => $this->currencychooser())); ?>
    </div>
</div>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('order', array('action' => 'payment')));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div>
    <?php if(count($paymenttypes) <= 0): ?>
        <h2><?php echo $this->translate('There are currently no payment types available'); ?></h2>
        <p><?php echo $this->translate('There are currently no payment options available. Please check back at a later date. Sorry!'); ?></p>
    <?php else: ?>
        <h2><?php echo $this->translate('Choose Payment type'); ?></h2>
        <?php echo $this->formElementErrors($form->get('paymenttype_id')); ?>
        <?php foreach($paymenttypes as $paymenttype): 
            $now = new \DateTime(); ?>
            <div class="row">
                <div class="col-lg-6 col-bordered col-payment">
                    <?php if(
                            $now->getTimestamp() < $paymenttype->getActiveUntil()->getDeadline()->getTimestamp() &&
                            $now->getTimestamp() > $paymenttype->getActiveFrom()->getDeadline()->getTimestamp() &&
                            $paymenttype->getCurrency()->getShort() == $this->session()->currency
                            ): ?>
                        <?php if($order->getPaymentTypeId() != null):
                            if($order->getPaymentTypeId() == $paymenttype->getId()) :
                                $checked = true;
                            endif;
                        else:
                            if($paymenttype->getPreselected()):
                                $checked = true;
                            else:
                                $checked = false;
                            endif;
                        endif; ?>
                        <label class="payment-type">
                            <input style="display: inline;" <?php echo $checked ? 'checked="checked"' : ''; ?> type='radio' name='paymenttype_id' value='<?php echo $paymenttype->getId(); ?>' /> 
                            <?php echo $paymenttype->getName() ?>
                            <span class="h5">(<?php echo $this->translate('payment fee:'); ?> <?php echo $this->currencyFormat($order->getPaymentFees($paymenttype), $order->getCurrency()->getShort(), null, 'de_DE'); ?>)</span>
                        </label>
                    <?php elseif(
                            $now->getTimestamp() < $paymenttype->getActiveUntil()->getDeadline()->getTimestamp() &&
                            $now->getTimestamp() > $paymenttype->getActiveFrom()->getDeadline()->getTimestamp() &&
                            $paymenttype->getCurrency()->getShort() != $this->session()->currency
                            ): ?>
                        <label class="payment-type">
                            <input style="display: inline;" disabled="disabled" type='radio' name='paymenttype_id' value='<?php echo $paymenttype->getId(); ?>' /> 
                            <?php echo $paymenttype->getName() ?>
                        </label>
                        <p class="alert alert-info">
                            <i class="fa fa-info"></i> <?php echo sprintf($this->translate('This payment type is only available for the currency %s.'), $paymenttype->getCurrency()); ?>
                        </p>
                    <?php elseif($now->getTimestamp() < $paymenttype->getActiveFrom()->getDeadline()->getTimestamp()): ?>
                        <label class="payment-type">
                            <input style="display: inline;" disabled="disabled" type='radio' name='paymenttype_id' value='<?php echo $paymenttype->getId(); ?>' /> 
                            <?php echo $paymenttype->getName() ?>
                            <span class="h5">(payment fee: <?php echo $this->currencyFormat($order->getPaymentFees($paymenttype), $order->getCurrency()->getShort(), null, 'de_DE'); ?>)</span>
                        </label>
                        <p class="alert alert-warning">
                            <i class="fa fa-warning"></i> <?php echo $this->translate('This payment type is not available, yet. It will be available from').' '.$paymenttype->getActiveFrom()->getDeadline()->format('d.m.Y').' '.$this->translate('until').' '.$paymenttype->getActiveUntil()->getDeadline()->format('d.m.Y'); ?>. <?php echo $this->translate('Please choose another payment type.'); ?>
                        </p>
                    <?php else: ?>
                        <label class="payment-type">
                            <input style="display: inline;" disabled="disabled" type='radio' name='paymenttype_id' value='<?php echo $paymenttype->getId(); ?>' /> 
                            <?php echo $paymenttype->getName() ?>
                            <span class="h5">(payment fee: <?php echo $this->currencyFormat($order->getPaymentFees($paymenttype), $order->getCurrency()->getShort(), null, 'de_DE'); ?>)</span>
                        </label>
                        <p class="alert alert-warning">
                            <i class="fa fa-warning"></i> <?php echo $this->translate('This payment type was available until').' '.$paymenttype->getActiveUntil()->getDeadline()->format('d.m.Y'); ?>. <?php echo $this->translate('Please choose another payment type.'); ?>
                        </p>
                    <?php endif; ?>
                    <p class="payment-desc">
                        <!--<?php echo $paymenttype->getShortDescription(); ?> <a href="<?php echo $this->url('info', array('action' => 'payment', 'id' => $paymenttype->getId()))?>">more info...</a>-->
                        <?php echo $paymenttype->getLongDescription(); ?>
                    </p>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<div class="clear-both"></div>
<div class="checkout">
    <?php 
        echo $this->formSubmit($form->get('submit'));
        echo $this->formHidden($form->get('csrf'));
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>