<?php

$title = 'My Shopping Cart';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('order', array('action' => 'register')));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div class="order-steps">
    <div class="order-step"><span class="order-step-no">1</span> <a href="<?php echo $this->url('order'); ?>">My cart</a></div>
    <div class="order-step active"><span class="order-step-no">2</span> <a href="<?php echo $this->url('order', array('action' => 'register')); ?>">Register</a></div>
    <div class="order-step"><span class="order-step-no">3</span> <a href="<?php echo $this->url('order', array('action' => 'payment')); ?>">Payment</a></div>
    <div class="order-step"><span class="order-step-no">4</span> <a href="<?php echo $this->url('order', array('action' => 'checkout')); ?>">Checkout</a></div>
</div>
<div class="clear-both"></div>
<div class="checkout">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<div>
    <h1>Register</h1>
    <?php if(count($order->getPackages()) > 1): ?>
    <p>Every participant who has an email set will receive his own eTicket. The <strong>purchaser</strong> you choose will receive <strong>all eTickets</strong>.</p>
    <?php
        echo $this->formRow($form->get('purchaser'));
    else: 
        $form->get('purchaser')->setAttribute('value', 0);
        echo $this->formHidden($form->get('purchaser'));
    endif;
    
    echo $this->formRow($form->get('prename'));
    echo $this->formRow($form->get('surname'));
    echo $this->formRow($form->get('email'));
    ?>
</div>

<div class="clear-both"></div>
<div class="checkout">
    <?php 
        echo $this->formSubmit($form->get('submit'));
        echo $this->formHidden($form->get('csrf'));
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>