<?php

$title = 'My Shopping Cart';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
echo $this->navigation()
    ->menu('checkout_nav')
    ->setUlClass('nav navbar-nav navbar-checkout');
?>
<div class="clear-both"></div>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('order', array('action' => 'register')));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div class="checkout">
    <?php echo $this->formSubmit($form->get('submit')); ?>
</div>
<div>
    <h1>Register</h1>
    <?php if(count($order->getPackages()) > 1): ?>
    <p>Every participant who has an email set will receive his own eTicket. The <strong>purchaser</strong> you choose will receive <strong>all eTickets</strong>.</p>
    <h3>Choose Purchaser</h3>
    <?php if(count($form->getMessages()) != 0): ?>
    <div>
        <ul>
            <?php foreach($form->getMessages() as $field => $messages): ?>
                <?php foreach($messages as $message): ?>
                <li><?php echo $message; ?></li>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
    <?php foreach($participants as $participant): ?>
        <?php if($participant->getEmail() == '' || $participant->getFirstname() == '' || $participant->getSurname() == ''): 
            $disabled = true;
        else:
            $disabled = false;
        endif; ?>
        <?php if($order->getPurchaser() != null && $order->getPurchaser()->getEmail() == $participant->getEmail()) :
            $checked = true;
        else:
            $checked = false;
        endif; ?>
        <div class="purchaser">
            <h4>
                <input type="radio" <?php echo $checked ? 'checked="checked"' : '' ?> <?php echo $disabled ? 'disabled="disabled"' : ''; ?> name="purchaser_id" value="<?php echo $participant->getSessionId() ?>" />
                <?php echo $participant->getFirstname().' '.$participant->getSurname(); ?>
                <span style="font-size: 14px;">
                    <?php if($participant->getBirthday() != null): ?>
                    <a href="<?php echo $this->url('participant', array('action' => 'edit', 'id' => $participant->getSessionId())); ?>">edit</a>
                    <?php else: ?>
                    <a href="<?php echo $this->url('purchaser', array('action' => 'edit', 'id' => $participant->getSessionId())); ?>">edit</a>
                    <?php endif; ?>
                </span>
            </h4>
            <?php if($participant->getEmail() != ''): ?>
                <p>Email: <?php echo $participant->getEmail(); ?></p>
            <?php else: ?>
                <p><a href="<?php echo $this->url('participant', array('action' => 'edit', 'id' => $participant->getSessionId())); ?>">Add email address</a> to choose this participant as purchaser.</p>
            <?php endif; ?>

            <?php if($participant->getBirthday() != null): ?>
            <p>Birthday: <?php echo $participant->getBirthday()->format('d.m.Y'); ?></p>
            <?php endif; ?>

        </div>
    <?php endforeach; ?>
    <?php
        #echo $this->formRow($form->get('purchaser_id'));
    else: 
        $form->get('purchaser_id')->setAttribute('value', 0);
        echo $this->formHidden($form->get('purchaser_id'));
    endif;
    ?>
    <!--<div class="purchaser">
        <h4>
            <input type="radio" name="purchaser_id" value="0" />
            Add Purchaser
        </h4>
        <?php
            #echo $this->formRow($form->get('firstname'));
            #echo $this->formRow($form->get('surname'));
            #echo $this->formRow($form->get('email'));
        ?>
    </div>-->
    <div>
        <a class="btn btn-primary" href="<?php echo $this->url('purchaser', array('action' => 'add')); ?>">add Purchaser</a>
    </div>
</div>

<div class="clear-both"></div>
<div class="checkout">
    <?php 
        echo $this->formSubmit($form->get('submit'));
        echo $this->formHidden($form->get('csrf'));
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>