<html>
    <head>
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .clear-both {
                clear: both;
            }
            .small {
                font-size: 12px;
            }
            .very-small {
                font-size: 10px;
            }
            .bluetext {
                color: #5278cf;
            }
            .greytext {
                color: #888;
            }
            .initial-info {
                width: 40%;
            }
            .codes {
                width: 340px;
                background: #fff;
                text-align: right;
                position: absolute;
                top: 100px;
                right: 0px;
                border: 1px solid #eee;
            }
            .very-small p {
                margin: 2px;
                padding: 0;
            }
            .very-small h1 {
                color: #5278cf;
                font-size: 32px;
            }
            .justify {
                text-align: justify;
            }
            .disclaimer {
                border: 1px solid #ddd;
                border-radius: 5px;
                padding: 1mm 2mm;
            }
        </style>
    </head>
    <body>
        <h1><img src="/home/ers/www/ers.sixhop.net/public/img/logo.jpg" alt="EJC 2015 Bruneck" /> E-Ticket <?php echo $name; ?></h1>
    </body>
</html>