<?php

$title = _('Thank you');
$this->headTitle($title);
?>

<div class="jumbotron">
    <h1><span class="green"><?php echo $this->escapeHtml($title); ?></span></h1>
    
    <p><?php echo _('...for your purchase and with that for your support to make the EJC 2016 possible.'); ?></p>
    
    <p><strong><?php echo _('Note:'); ?></strong> <?php echo _('To receive the email with your E-Tickets correctly 
        it\'s important that you add the email address prereg@eja.net to your 
        address book.'); ?></p>

    <p><?php echo _('We sent an order confirmation mail to your email address. If you did not 
        receive this email, please have a look at your spam folder. If it\'s not 
        there contact us at <a href=\'mailto: prereg@eja.net\'>prereg@eja.net</a>.'); ?></p>

    <p><?php echo _('In this email you will find further information of your purchase.'); ?></p>
</div>