<?php

$title = 'Thank you';
$this->headTitle($title);
?>

<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    
    <p>...for your purchase and with that for your support to make the EJC 2015 possible.</p>

    <p>We send an email to your email address. If you did not receive this email, please first have a look at your spam folder. If it's not there contact us at <a href='mailto: prereg@eja.net'>prereg@eja.net</a>.</p>

    <p>In this email you will find further information of your purchase.</p>
</div>