<?php

$title = $this->translate('My Order');
$this->headTitle($title);

$preregMail = $this->setting('ers.prereg_mail', 'email');
$infoMail = $this->setting('ers.info_mail', 'email');
?>

<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-lg-6">
        <div class="order-info">
            <h2><?php echo $this->translate('Buyer'); ?></h2>
            <?php $buyer = $order->getBuyer(); ?>
            <?php if($buyer): ?>
            <h2><?php echo $buyer->getFirstname().' '.$buyer->getSurname(); ?></h2>
            <?php else: ?>
            <h2>No buyer found</h2>
            <?php endif; ?>
            <p><?php echo $this->translate('The buyer will receive all E-Tickets for all registered participants. If you have provided an email address per participant, this participant will be informed once the ticket is paid and will be able to download the E-Ticket on his own aswell.'); ?></p>
            <h3><?php echo $this->translate('We will send all information to:'); ?> <?php echo $buyer->getEmail(); ?></h3>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="order-info">
            <h2><?php echo $this->translate('Payment'); ?></h2>
            <?php if($order->getPaymentStatus() == 'paid') : ?>
            <div class="alert alert-success"><i class="fa fa-check"></i> <?php echo $this->translate('order is paid'); ?></div>
            <?php elseif($order->getPaymentStatus() == 'unpaid') : ?>
            <div class="alert alert-warning"><i class="fa fa-warning"></i> <?php echo $this->translate('order is unpaid'); ?></div>
            <?php elseif($order->getPaymentStatus() == 'cancelled') : ?>
            <div class="alert alert-danger"><i class="fa fa-close"></i> <?php echo $this->translate('order is cancelled'); ?></div>
            <?php endif; ?>
            <?php $paymenttype = $order->getPaymentType(); ?>
            <h3><?php echo $paymenttype->getName(); ?></h3>
            <p><?php echo $paymenttype->getExplanation(); ?></p>
            <?php #if($order->getStatus() == 'paid'): ?>
            <?php if($order->getStatus()->getValue() == 'paid'): ?>
                <h3><?php echo $this->translate('This order is already paid'); ?></h3>
                <p><?php echo $this->translate('Your E-Tickets will be sent out in june.'); ?></p>
                <p><strong><?php echo $this->translate('Note:'); ?></strong> <?php echo sprintf($this->translate('Please add the email address 
                    %s to your address book. To be sure the email 
                    with your E-Tickets will not arrive in your spamfolder.'), $this->setting('ers.info_mail', 'email')); ?></p>
            <?php elseif($order->getStatus()->getValue() == 'ordered'): ?>
                <?php if($paymenttype->getType() == 'sepa'): ?>
                    <h3><?php echo $this->translate('Bank Transfer Details'); ?></h3>
                    <?php echo $this->partial('partial/sepa-banktransfer-info.phtml', array('order' => $order)); ?>
                <?php elseif($paymenttype->getType() == 'creditcard'): ?>
                    <a class="btn btn-primary" href="<?php echo $this->url('payment', array('action' => 'creditcard', 'hashkey' => $order->getHashKey())); ?>">
                        Start payment with Credit Card
                    </a>
                <?php elseif($paymenttype->getType() == 'ipayment'): ?>
                    <a class="btn btn-primary" href="<?php echo $this->url('payment', array('action' => 'ipayment', 'hashkey' => $order->getHashKey())); ?>">
                        Start payment with Credit Card
                    </a>
                <?php elseif($paymenttype->getType() == 'paypal'): ?>
                    <a class="btn btn-primary" href="<?php echo $this->url('payment', array('action' => 'paypal', 'hashkey' => $order->getHashKey())); ?>">
                        Start payment with PayPal
                    </a>
                <?php else: ?>
                    <?php echo $this->translate('No payment type was recognized'); ?> (<?php echo $paymenttype->getType(); ?>)
                <?php endif; ?>
            <?php else: ?>
                <h3><?php echo $this->translate('undefined status'); ?></h3>
                <p><?php echo $this->translate('Please contact the prereg coordinator to solve this problem:'); echo $preregMail; ?></p>
            <?php endif; ?>
        </div>
    </div>
</div>
<div>
    <h2>Shopping Cart</h2>
        <div>
        <?php 
            $sum = 0;
            foreach ($order->getPackages() as $package) : 
                if(count($package->getItems()) == 0) {
                    continue;
                }
                $user = $package->getParticipant();
            
                if($user->getFirstname() == '' && $user->getSurname() == '') :
                    $participant = $this->translate('unassigned items');
                else:
                    $participant = $user->getFirstname().' '.$user->getSurname();
                endif;
        ?>
            <div class="package">
                <h3><?php echo $participant; ?></h3>
                
                <?php if(count($package->getItems()) != 0): ?>
                <table class="table">
                    <tr>
                        <th>Product</th>
                        <th class="cart-amount"><?php echo $this->translate('Amount'); ?></th>
                        <th class="cart-price"><?php echo $this->translate('Price'); ?></th>
                    </tr>
                    <?php
                    $subtotal = 0;
                    foreach ($package->getItems() as $item) : 
                        $subtotal += $item->getPrice();
                        $sum += $item->getPrice();
                        ?>
                        <tr>
                            <td>
                                <span class="product-name"><?php echo $item->getName(); ?></span>
                                <span class="product-variants">
                                    <?php 
                                    $variants = array();
                                    if(count($item->getItemVariants()) > 0): 
                                    ?>
                                    (
                                    <?php 
                                    $numVariants = count($item->getItemVariants()); 
                                    $i = 0;
                                    ?>
                                    <?php foreach($item->getItemVariants() as $variant): 
                                        echo $variant->getName().': '.$variant->getValue(); 
                                        if(++$i != $numVariants):
                                            echo '; ';
                                        endif;
                                        $variants[$variant->getName()] = $variant->getProductVariantValueId();
                                    endforeach; ?>
                                    )
                                    <?php endif; ?>
                                </span>
                            </td>
                            <td><?php echo $item->getAmount(); ?></td>
                            <td><?php echo $this->currencyFormat($item->getPrice(), $order->getCurrency()->getShort(), null, 'de_DE'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td><?php echo $this->translate('Subtotal:'); ?></td>
                        <td><?php echo $this->currencyFormat($subtotal, $order->getCurrency()->getShort(), null, 'de_DE'); ?></td>
                    </tr>
                </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        <?php if($paymenttype) : ?>
            <table class="table sum-table">
                <tr>
                    <td><?php echo $this->translate('Order amount:'); ?></td>
                    <td><?php echo $this->currencyFormat($order->getPrice(), $order->getCurrency()->getShort(), null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <td>Payment Charge:</td>
                    <td><?php echo $this->currencyFormat($paymenttype->calcFee($sum), $order->getCurrency()->getShort(), null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <th><span style="font-size: 18px;"><?php echo $this->translate('Total amount:'); ?></span></th>
                    <th><span style="font-size: 18px;"><?php echo $this->currencyFormat($order->getSum(), $order->getCurrency()->getShort(), null, 'de_DE'); ?></span></th>
                </tr>
            </table>
        <?php endif; ?>
    </div>
</div>
<div class="clear-both"></div>
