<?php

$title = 'My Order';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-lg-6">
        <div class="order-info">
            <h1>Purchaser</h1>
            <?php $purchaser = $order->getPurchaser(); ?>
            <h2><?php echo $purchaser->getFirstname().' '.$purchaser->getSurname(); ?></h2>
            <p>The purchaser will receive all eTickets for all registered participants. If you have provided an email address for a participant this participant will be informed once the ticket is payed and will be able to download the eTicket on his own aswell.</p>
            <h3>We will send all information to: <?php echo $purchaser->getEmail(); ?></h3>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="order-info">
            <h1>Payment</h1>
            <?php $paymenttype = $order->getPaymentType(); ?>
            <h3><?php echo $paymenttype->getName(); ?></h3>
            <p><?php echo $paymenttype->getExplanation(); ?></p>
            <?php if($order->getStatus() == 'unpaid'): ?>
                <?php if($paymenttype->getType() == 'BankTransfer'): ?>
                    <h3>Bank Transfer Details</h3>
                    <?php echo $this->partial('partial/banktransfer-info.phtml', array('order' => $order)); ?>
                <?php elseif($paymenttype->getType() == 'CreditCard'): ?>
                    <a href="<?php echo $this->url('payment', array('action' => 'creditcard', 'hashkey' => $order->getHashKey())); ?>">
                        Start payment with Credit Card
                    </a>
                <?php endif; ?>
            <?php elseif($order->getStatus() == 'paid'): ?>
                <h3>This order is already paid</h3>
                <p>All eTickets have been sent to this email address: <?php echo $order->getPurchaser()->getEmail(); ?></p>
                <p>Please have a look at your Spam folder, maybe the email is there.</p>
            <?php else: ?>
                <h3>undefined status</h3>
                <p>Please contact the EJC team to solve this problem: <a href="mailto:info@ejc2015.org">info@ejc2015.org</a></p>
            <?php endif; ?>
        </div>
    </div>
</div>
<div>
    <h1>Shopping Cart</h1>
        <div>
        <?php 
            $sum = 0;
            foreach ($order->getPackages() as $package) : 
                if(count($package->getItems()) == 0) {
                    continue;
                }
                $user = $package->getParticipant();
            
                if($user->getFirstname() == '' && $user->getSurname() == '') :
                    $participant = 'unassigned items';
                else:
                    $participant = $user->getFirstname().' '.$user->getSurname();
                endif;
        ?>
            <div class="package">
                <h3><?php echo $participant; ?></h3>
                
                <?php if(count($package->getItems()) != 0): ?>
                <table class="table">
                    <tr>
                        <th>Product</th>
                        <th class="cart-amount">Amount</th>
                        <th class="cart-price">Price</th>
                    </tr>
                    <?php
                    $subtotal = 0;
                    foreach ($package->getItems() as $item) : 
                        $subtotal += $item->getPrice();
                        $sum += $item->getPrice();
                        ?>
                        <tr>
                            <td>
                                <span class="product-name"><?php echo $item->getName(); ?></span>
                                <span class="product-variants">
                                    <?php 
                                    $variants = array();
                                    if(count($item->getItemVariants()) > 0): 
                                    ?>
                                    (
                                    <?php 
                                    $numVariants = count($item->getItemVariants()); 
                                    $i = 0;
                                    ?>
                                    <?php foreach($item->getItemVariants() as $variant): 
                                        echo $variant->getName().': '.$variant->getValue(); 
                                        if(++$i != $numVariants):
                                            echo '; ';
                                        endif;
                                        $variants[$variant->getName()] = $variant->getProductVariantValueId();
                                    endforeach; ?>
                                    )
                                    <?php endif; ?>
                                </span>
                            </td>
                            <td><?php echo $item->getAmount(); ?></td>
                            <td><?php echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td>Subtotal:</td>
                        <td><?php echo $this->currencyFormat($subtotal, 'EUR', null, 'de_DE'); ?></td>
                    </tr>
                </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        <?php if($paymenttype) : ?>
            <table class="table sum-table">
                <tr>
                    <td>Order amount:</td>
                    <td><?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <td>Payment Charge:</td>
                    <td><?php echo $this->currencyFormat($paymenttype->calcFee($sum), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <th><span style="font-size: 18px;">Total amount:</span></th>
                    <th><span style="font-size: 18px;"><?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></span></th>
                </tr>
            </table>
        <?php endif; ?>
    </div>
</div>
<div class="clear-both"></div>