<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .clear-both {
                clear: both;
            }
        </style>
    </head>
    <body>
        <p>Dear <?php $order->getBuyer()->getFirstname().' '.$order->getBuyer()->getSurname(); ?>,</p>

        <p>We received the payment in conjunction with your order from 
            <?php $order->getCreated()->format('d.m.Y') ?> with the order ID 
            <?php echo $order->getCode()->getValue(); ?>. Thanks a lot!</p>

        <p>Attached to this email, you can find the following documents:</p>
        <ul>
            <li>the invoice to your order</li>
            <li>your e-Tickets</li>
            <li>the information letter with all important information</li>
        </ul>

        <p>Please print the documents, read them carefully and present the 
            e-Tickets at the onsite registration. To be able to read the 
            document, you need to install Adobe Acrobat Reader, which you can 
            download here: <a href="http://get.adobe.com/de/reader">http://get.adobe.com/de/reader</a>.</p>

        <p>An information letter with all important informations to the EJC will follow in a later email.</p>

        <p>We wish you a pleasant journey and we are looking forward to a great convention.</p>

        <p>Best regards,<br />
        your European Juggling Association and the local EJC 2015 organizers</p>
    </body>
</html>