<?php
    $title = $this->translate('This system uses cookies');
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row">
    <div class="col-lg-8">
        <p>We use cookies on this site to be able to manage your shopping 
            cart and the items that you want to order. Without cookies, we 
            could not tell apart the (potentially many) jugglers that access 
            this site and we would not be able to keep their shopping carts 
            separated. Think of a cookie as something similar to a marker 
            that you put onto your nice white clubs: It helps you to find 
            them again in a gym full of almost identical white clubs!</p>
        <p>On a more technical note, 
            <a href="http://en.wikipedia.org/wiki/HTTP_cookie" target="_blank">wikipedia</a>
            says about cookies:</p>
        <p>"A HTTP cookie (also called web cookie, Internet cookie, browser 
            cookie or simply cookie, the latter which is not to be confused 
            with the literal definition), is a small piece of data sent 
            from a website and stored in a user's web browser while the 
            user is browsing that website. Every time the user loads the 
            website, the browser sends the cookie back to the server to 
            notify the website of the user's previous activity.[1] Cookies 
            were designed to be a reliable mechanism for websites to 
            remember stateful information (such as items in a shopping cart) 
            or to record the user's browsing activity (including clicking 
            particular buttons, logging in, or recording which pages were 
            visited by the user as far back as months or years ago)."</p>
    </div>
</div>