<?php
$this->headTitle('e-ticket Translations');


$form = $this->form;
$form->setAttribute('action', $this->url('info', array('action' => 'e-ticket')));
$form->prepare();

echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col-md-3">
        <?php echo $this->formRow($form->get('lang')); ?>
    </div>
    <div class="col-md-3">
        <?php echo $this->formRow($form->get('agegroup')); ?>
    </div>
    <div class="col-md-3">
        <?php echo $this->formHidden($form->get('csrf'));
        echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>

<?php if($agegroup):
    $agegroup_name = $agegroup->getName();
else:
    $agegroup_name = 'adult';
endif; ?>
<h1>E-Ticket for <?php echo $agegroup_name; ?> in <?php echo $lang; ?></h1>

<?php echo $this->partial('partial/eticket-translation-'.$lang.'.phtml', array('agegroup' => $agegroup)); ?>