<?php

$this->headTitle($this->translate('Impressum'));
?>

<div>
    <div class="jumbotron">
        <h1>Impressum</h1>
        <p><strong>Circulum e. V.</strong><br />
        Nicolaistr. 42<br />
        12247 Berlin<br />
        Deutschland</p>
        <p>E-Mail: <a href="mailto:kontakt@circulum.de">kontakt@circulum.de</a><br />
        Web: <a href="http://www.circulum.de/" target="_blank">www.circulum.de</a></p>
        
    </div>
</div>