<?php

$this->headTitle($this->translate('Impressum'));
?>

<div>
    <div class="jumbotron">
        <h1>Impressum</h1>
        <p>Stichting European Juggling Association<br />
        Jodenbreestraat 24-1<br />
        1011 NK Amsterdam<br />
        The Netherlands</p>

        <p>E-Mail: info@eja.net<br />
        Web: <a href="http://www.eja.net/" target="_blank">www.eja.net</a></p>
        
    </div>
</div>