<?php

$this->headTitle('Terms & Conditions');
?>

<div>
    <div class="jumbotron">
        <h1>Impressum</h1>
        <p>Stichting European Juggling Association (EJA)<br />
        Jodenbreestraat 24-1<br />
        1011 NK Amsterdam<br />
        Netherlands</p>

        <p>Phone: +31-20-623-9487<br />
        E-Mail: info (at) eja.net</p>

        <p>Registered at Kamer van Koophandel Amsterdam (41213128)</p>

        <p>Represented by:
            <ul>
                <li>Philip Nicolai</li>
                <li>Andreas Nitsche</li>
                <li>Jasper Verbree</li>
            </ul>
        </p>
    </div>
</div>