<?php

$this->headTitle('EJC Registration System');
?>

<div class="jumbotron">
    <h1>
        <?php echo $this->escapeHtml('Welcome to the'); ?>
        <br />
        <span class="green"><?php echo $this->escapeHtml('EJC Registration System'); ?></span>
    </h1>
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <p class="justify">The European Juggling Convention (EJC) 2015 will take place from 
                01.08. - 09.08.2015 in Bruneck (Italy). You can find all up to date 
                information on <a href="http://www.ejc2015.org/" target="_blank">www.ejc2015.org</a>.</p>
            <p class="justify">On this site you can purchase tickets for EJC 2015 as well as other 
                items such as galashow tickets.</p>
            <p class="justify">This year it is especially important that many jugglers register as 
                early as possible. So help the organizing team: Buy your ticket now!</p>

            <p class="justify">Please also note that the price of all tickets  increases as EJC comes 
                closer. Visit <a href="http://www.ejc2015.org/registration" target="_blank">www.ejc2015.org/registration</a> to see all ticket prices at 
                a glance.</p>
        </div>
        <div class="col-lg-2"></div>
    </div>
    
    <div class='row'>
        <div class="col-lg-7"></div>
        <div class="col-lg-5 start-button">
            <a class="btn btn-vlg btn-success" href="<?php echo $this->url('product') ?>">Go to product overview</a>
        </div>
    </div>
</div>