<?php

$this->headTitle('Event Registration System');
?>

<div class="jumbotron">
    <h1>
        <?php echo $this->escapeHtml($this->translate('Welcome to the')); ?>
        <span class="primary-color"><?php echo $this->escapeHtml('Event Registration System'); ?></span> 
    </h1>
    <div class="row">
        <div class="col-md-7">
            <p class="justify">
                <?php 
                #$startDate = '<strong>'.strftime("%a %d.%m.%Y", $this->config()['ERS']['start']->getTimestamp()).'</strong>';
                $startDate = '<strong>'.$this->setting('ers.start', 'date', ['fromFormat' => 'Y-m-d', 'toFormat' => '%a %d.%m.%Y']).'</strong>';
                #$endDate = '<strong>'.strftime("%a %d.%m.%Y", $this->config()['ERS']['end']->getTimestamp()).'</strong>';
                $endDate = '<strong>'.$this->setting('ers.end', 'date', ['fromFormat' => 'Y-m-d', 'toFormat' => '%a %d.%m.%Y']).'</strong>';
                #$website = '<a class="primary-color" href="'.$this->config()['ERS']['website'].'" target="_blank">'.$this->config()['ERS']['website'].'</a>';
                $website = $this->setting('ers.website', 'hyperlink', ['class' => 'primary-color', 'target' => '_blank']);
                /*printf($this->translate('The %s will take place from %s - %s in %s (%s). You can find all up-to-date information on %s.'), 
                        $this->config()['ERS']['name_with_number'],
                        $startDate,
                        $endDate,
                        $this->config()['ERS']['city'],
                        $this->config()['ERS']['country'],
                        $website);*/
		printf($this->translate('The %s will take place from %s - %s in %s (%s). You can find all up-to-date information on %s.'),
                        $this->setting('ers.name_with_number'),
                        $startDate,
                        $endDate,
                        $this->setting('ers.city'),
                        $this->setting('ers.country'),
                        $website); ?>

            </p>

            <p class="justify"><?php #printf($this->translate('On this website you can purchase tickets for %s as well as other items such as galashow tickets.'), $this->config()['ERS']['name_with_year']); ?></p>
        </div>
        <div class="col-md-5">
        <?php
            if($deadline):
                $form->setAttribute('action', $this->url('participant', array('action' => 'add')));
                $form->prepare();

                echo $this->form()->openTag($form); ?>

                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formRow($form->get('firstname')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formRow($form->get('surname')); ?>
                    </div>
                </div>
                <?php echo $this->formRow($form->get('birthday'));
                echo $this->formRow($form->get('email'));
                echo $this->formRow($form->get('Country_id'));

                echo $this->formHidden($form->get('csrf')); ?>
                <?php echo $this->formSubmit($form->get('submit')); ?>
                <?php echo $this->form()->closeTag(); 
            else: ?>
                <div class="alert alert-info">
                    <h3><?php echo $this->escapeHtml($this->translate('PreReg is closed')); ?></h3>
                    <p>
                        <?php printf($this->translate('The PreReg is already closed. For more information, please visit our homepage on %s'), $this->setting('ers.website', 'hyperlink')); ?>
                    </p>
                </div>
            <?php endif; ?>
        </div>
    </div>
    
    
</div>
