<?php

$this->headTitle($this->translate('Terms & Conditions'));
?>

<div class="jumbotron">
    <h1><?php echo $this->translate('Terms and Conditions'); ?></h1>
    <p>ERS Terms: <a href="/Terms and Conditions ERS EN v8.pdf">Terms and Conditions ERS</a><br />
    ORGA Terms: <a href="/Terms-and-Conditions-EN_v7.pdf">Terms and Conditions organisation</a></p>
    <h3><?php echo $this->translate('Disclaimer'); ?></h3>
    <p><?php echo $this->setting('ers.terms'); ?></p>
</div>
