<?php

$this->headTitle('Terms & Conditions');
?>

<div>
    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Back</a>
    <div class="jumbotron">
        <h1>Terms and Conditions</h1>
        <a href="/Terms-and-Conditions-ERS-EN-v4.pdf" target="_blank">Terms and Conditions ERS EN v4</a><br />
        <a href="/Terms-and-Conditions-ORGA-EN-v2.pdf" target="_blank">Terms and Conditions ORGA EN v2</a>
    </div>
</div>