<?php

$title = 'Add tax group';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/tax', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('percentage'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/tax');?>">Cancel</a>
<?php
echo $this->form()->closeTag();