<?php
// module/Admin/view/admin/tax/delete.phtml:

$title = 'Delete Tax Group';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete tax group
    <strong><?php echo $this->escapeHtml($tax->getName()); ?></strong> with
    <strong><?php echo $this->escapeHtml($tax->getPercentage()); ?>%</strong>?
</p>
<?php
$url = $this->url('admin/tax', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $tax->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/tax');?>">Cancel</a>
</div>
</form>