<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Product Variant Value';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/product-variant-value',
    array(
        'action' => 'add',
        'id'     => $this->productvariant_id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('value'));
echo $this->formRow($form->get('visible'));
echo $this->formRow($form->get('disabled'));
echo $this->formRow($form->get('ProductVariant_id'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();