<?php
// module/Album/view/album/album/add.phtml:

$title = 'add setting';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/setting', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')); ?>
<div class="row">
    <div class="col-md-12"><?php echo $this->formRow($form->get('key')); ?></div>
    <?php
        $form->remove('value');

        $form->add(array( 
            'name' => 'value', 
            #'type' => 'Zend\Form\Element\Textarea', 
            'type' => 'CKEditorModule\Form\Element\CKEditor',
            'attributes' => array( 
                'placeholder' => 'value...',
                /*'class' => 'form-control form-element',*/
            ), 
            'options' => array( 
                'label' => 'value', 
                'label_attributes' => array(
                    'class'  => 'media-object',
                ),
                'ckeditor' => array(
                    // add any config you would normaly add via CKEDITOR.editorConfig
                    'language' => 'en',
                    #'uiColor' => '#428bca',
                ),
            ), 
        ));
    ?>
    <div class="col-md-12"><?php echo $this->formRow($form->get('value')); ?></div>
</div>


<?php echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/setting');?>">Cancel</a>
<?php
echo $this->form()->closeTag();