<?php
// module/Album/view/album/album/add.phtml:

$title = 'edit setting';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/setting',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')); ?>
<div class="row">
    <div class="col-md-6"><?php echo $this->formRow($form->get('key')); ?></div>
    <div class="col-md-6"><?php echo $this->formRow($form->get('value')); ?></div>
</div>
<?php echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/setting');?>">Cancel</a>
<?php
echo $this->form()->closeTag();