<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'setting overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>key</th>
        <th>value</th>
        <th class="text-right">
            <a class="btn btn-success" href="<?php echo $this->url('admin/setting', array('action'=>'add'));?>"><i class="fa fa-plus"></i> setting</a>
        </th>
    </tr>
<?php foreach ($settings as $setting) : ?>
    <tr>
        <td><?php echo $setting->getKey(); ?></td>
        <td><?php echo $setting->getValue(); ?></td>
        <td class="text-right">
            <a class="btn btn-default" href="<?php echo $this->url('admin/setting', array('action'=>'edit', 'id' => $setting->getId()));?>"><i class="fa fa-edit"></i></a>
            <a class="btn btn-danger" href="<?php echo $this->url('admin/setting', array('action'=>'delete', 'id' => $setting->getId()));?>"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>