<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Person';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('participant', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('firstname'));
echo $this->formRow($form->get('surname'));
echo $this->formRow($form->get('birthday'));
?>
<div class="row">
    <div class="col-lg-3">
        <?php echo $this->formRow($form->get('email')); ?>
    </div>
    <div class="col-lg-5">
        <p><strong>Note:</strong> The purchaser of this order will receive all eTickets 
            of all persons. If you want to send the eTicket of this person to his/her 
            per mail add the email address.</p>
    </div>
</div>
<?php
echo $this->formRow($form->get('Country_id'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();