<?php

$title = $this->translate('Delete Person');
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php $participant = $form->getObject(); ?>
<p>Are you sure that you want to delete participant
    <strong><?php echo $this->escapeHtml($participant->getFirstname().' '.$participant->getSurname()); ?></strong>?
</p>
<?php if(count($package->getItems()) > 0): ?>
    <h2><?php echo $this->translate('These items will be deleted with this participant:'); ?></h2>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Price</th>
        </tr>
    
    <?php foreach($package->getItems() as $item): ?>
        <tr>
            <td><?php echo $item->getName(); ?></td>
            <td><?php echo $this->currencyFormat($item->getPrice(), $item->getCurrency(), null, 'de_DE'); ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif; ?>
    
<?php $form->setAttribute('action', $this->url('participant', array('action' => 'delete', 'id' => $participant->getId())))
      ->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit')); ?>

<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>

<?php echo $this->form()->closeTag();
