<?php

$title = 'Edit Person';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'participant',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
#$form->getInputFilter()->get('email')->setRequired(false);

echo $this->form()->openTag($form);
#echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('session_id'));
echo $this->formRow($form->get('firstname'));
echo $this->formRow($form->get('surname'));
echo $this->formRow($form->get('birthday'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('Country_id'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();