<?php

$title = _('Personal Details');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>List of people I'm booking EJC tickets for.</p>
<p><a class="btn btn-primary" href="<?php echo $this->url('participant', array('action'=>'add'));?>">Add person</a></p>

<table class="table">
    <tr>
        <th class="person-name"><?php echo _('Name'); ?></th>
        <th class="person-birthday"><?php echo _('Birthday'); ?></th>
        <th class="person-email"><?php echo _('Email'); ?></th>
        <th class="person-country"><?php echo _('Country'); ?></th>
        <th class="person-tools"></th>
    </tr>
    <?php foreach ($participants as $participant) : ?>
        <tr>
            <td><?php echo $participant->getFirstname()." ".$participant->getSurname(); ?></td>
            <td>
                <?php if($participant->getBirthday() != null):
                    echo $participant->getBirthday()->format('d.m.Y');
                endif; ?>
            </td>
            <td><?php echo $participant->getEmail();?></td>
            <td>
                <?php if(is_object($participant->getCountry())):
                    $country = $participant->getCountry();
                    echo $country->getName();
                else:
                    echo _('no Country');
                endif; ?>
            </td>
            <td>
                <a class='btn btn-sm btn-default' href="<?php echo $this->url('participant', array('action' => 'edit', 'id' => $participant->getId())); ?>"><i class='fa fa-edit'></i></a>
                <a class='btn btn-sm btn-danger' href="<?php echo $this->url('participant', array('action' => 'delete', 'id' => $participant->getId())); ?>"><i class='fa fa-trash'></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<p><a class="btn btn-primary" href="<?php echo $this->url('participant', array('action'=>'add'));?>">Add person</a></p>
