<?php

$title = 'My Persons';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a class="btn btn-primary" href="<?php echo $this->url('participant', array('action'=>'add'));?>">Add person</a></p>

<table class="table">
    <tr>
        <th class="person-name">Name</th>
        <th class="person-birthday">Birthday</th>
        <th class="person-email">Email</th>
        <th class="person-country">Country</th>
        <th class="person-tools"></th>
    </tr>
    <?php foreach ($participants as $participant) : ?>
        <tr>
            <td><?php echo $participant->getFirstname()." ".$participant->getSurname(); ?></td>
            <td>
                <?php if($participant->getBirthday() != null):
                    echo $participant->getBirthday()->format('d.m.Y');
                endif; ?>
            </td>
            <td><?php echo $participant->getEmail();?></td>
            <td>
                <?php if(is_object($participant->getCountry())):
                    $country = $participant->getCountry();
                    echo $country->getName();
                else:
                    echo 'no Country';
                endif; ?>
            </td>
            <td>
                <a href="<?php echo $this->url('participant', array('action' => 'edit', 'id' => $participant->getId())); ?>">edit</a> |
                <a href="<?php echo $this->url('participant', array('action' => 'delete', 'id' => $participant->getId())); ?>">delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<p><a class="btn btn-primary" href="<?php echo $this->url('participant', array('action'=>'add'));?>">Add person</a></p>