<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-01-07 08:26:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ErsBase\Entity\BankAccountCsv
 *
 * @ORM\Entity()
 * @ORM\Table(name="bank_account_csv", indexes={@ORM\Index(name="fk_bank_account_csv_bank_account1_idx", columns={"bank_account_id"})})
 * @ORM\HasLifecycleCallbacks
 */
class BankAccountCsv extends Base\BankAccountCsv
{
    public function __construct()
    {
        parent::__construct();
    }

    public function hasMatch() {
        foreach($this->getBankStatements() as $bs) {
            if(count($bs->getMatches()) > 0) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * 
     * @return float
     */
    public function getAmount() {
        $statement_format  = json_decode($this->getStatementFormat());
        $amount = (float) 0;
        foreach($this->getBankStatements() as $statement) {
            $amount += (float) $statement->getBankStatementColByNumber($statement_format->amount)->getValue();
        }
        return $amount;
    }
}
