<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-01-13 09:01:32.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ErsBase\Entity\ItemStatus
 *
 * @ORM\Entity()
 * @ORM\Table(name="item_status")
 * @ORM\HasLifecycleCallbacks
 */
class ItemStatus extends Base\ItemStatus
{
    public function __construct()
    {
        parent::__construct();
    }

}