<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-01-07 08:26:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ErsBase\Entity\Language
 *
 * @ORM\Entity()
 * @ORM\Table(name="`language`")
 */
class Language extends Base\Language
{
    public function __construct()
    {
        parent::__construct();
    }

}