<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-01-07 08:26:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ErsBase\Entity\Match
 *
 * @ORM\Entity()
 * @ORM\Table(name="`match`", indexes={@ORM\Index(name="fk_Matching_User1_idx", columns={"admin_id"}), @ORM\Index(name="fk_match_bank_statement1_idx", columns={"bank_statement_id"}), @ORM\Index(name="fk_match_order1_idx", columns={"order_id"})})
 * @ORM\HasLifecycleCallbacks
 */
class Match extends Base\Match
{
    public function __construct()
    {
        parent::__construct();
    }

}