<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-01-07 08:26:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ErsBase\Entity\OrderStatus
 *
 * @ORM\Entity()
 * @ORM\Table(name="order_status", indexes={@ORM\Index(name="fk_order_status_order1_idx", columns={"order_id"})})
 */
class OrderStatus extends Base\OrderStatus
{
    public function __construct()
    {
        parent::__construct();
    }

}