<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-01-07 08:26:28.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use BjyAuthorize\Acl\HierarchicalRoleInterface;

/**
 * ErsBase\Entity\Role
 *
 * @ORM\Entity()
 * @ORM\Table(name="`role`", indexes={@ORM\Index(name="fk_user_role_user_role1_idx", columns={"parent_id"})})
 * @ORM\HasLifecycleCallbacks
 */
class Role extends Base\Role implements HierarchicalRoleInterface
{
    public function __construct()
    {
        parent::__construct();
    }

    public function getParent() {
        return $this->getRole();
    }
}