<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-realentity) on 2016-01-13 09:49:26.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ErsBase\Entity\Status
 *
 * @ORM\Entity()
 * @ORM\Table(name="`status`")
 */
class Status extends Base\Status
{
    public function __construct()
    {
        parent::__construct();
    }

}