<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-mappedsuperclass) on 2017-07-19 23:21:08.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErsBase\Entity\Base;

use Doctrine\ORM\Mapping as ORM;

/**
 * ErsBase\Entity\Base\MailAttachment
 *
 * @ORM\MappedSuperclass
 * @ORM\Table(name="`mail_attachment`", indexes={@ORM\Index(name="fk_mail_attachment_mailq1_idx", columns={"`mailq_id`"})})
 * @ORM\HasLifecycleCallbacks
 */
abstract class MailAttachment
{
    /**
     * @ORM\Id
     * @ORM\Column(name="`id`", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="`mailq_id`", type="integer")
     */
    protected $mailq_id;

    /**
     * @ORM\Column(name="`location`", type="text", nullable=true)
     */
    protected $location;

    /**
     * @ORM\Column(name="`updated`", type="datetime", nullable=true)
     */
    protected $updated;

    /**
     * @ORM\Column(name="`created`", type="datetime", nullable=true)
     */
    protected $created;

    /**
     * @ORM\ManyToOne(targetEntity="Mailq", inversedBy="mailAttachments", cascade={"persist", "merge", "remove"})
     * @ORM\JoinColumn(name="`mailq_id`", referencedColumnName="`id`")
     */
    protected $mailq;

    public function __construct()
    {
    }

    /**
     * @ORM\PrePersist
     */
    public function PrePersist()
    {
        if(!isset($this->created)) {
            $this->created = new \DateTime();
        }
        $this->updated = new \DateTime();
    }

    /**
     * @ORM\PreUpdate
     */
    public function PreUpdate()
    {
        $this->updated = new \DateTime();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \ErsBase\Entity\Base\MailAttachment
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of mailq_id.
     *
     * @param integer $mailq_id
     * @return \ErsBase\Entity\Base\MailAttachment
     */
    public function setMailqId($mailq_id)
    {
        $this->mailq_id = $mailq_id;

        return $this;
    }

    /**
     * Get the value of mailq_id.
     *
     * @return integer
     */
    public function getMailqId()
    {
        return $this->mailq_id;
    }

    /**
     * Set the value of location.
     *
     * @param string $location
     * @return \ErsBase\Entity\Base\MailAttachment
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * Get the value of location.
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set the value of updated.
     *
     * @param \DateTime $updated
     * @return \ErsBase\Entity\Base\MailAttachment
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get the value of updated.
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set the value of created.
     *
     * @param \DateTime $created
     * @return \ErsBase\Entity\Base\MailAttachment
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get the value of created.
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set Mailq entity (many to one).
     *
     * @param \ErsBase\Entity\Base\Mailq $mailq
     * @return \ErsBase\Entity\Base\MailAttachment
     */
    public function setMailq(Mailq $mailq = null)
    {
        $this->mailq = $mailq;

        return $this;
    }

    /**
     * Get Mailq entity (many to one).
     *
     * @return \ErsBase\Entity\Base\Mailq
     */
    public function getMailq()
    {
        return $this->mailq;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'mailq_id', 'location', 'updated', 'created');
        $relationFields = array('mailq');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'mailq_id', 'location', 'updated', 'created');
    }
}