<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php #echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headTitle($this->translate('Event Registration System'))->setSeparator(' - ')->setAutoEscape(false)  // change Skeleton Application to Sticky Notes ?> 

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/css/custom.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/vendor/morrisjs/morris.css')
                ->prependStylesheet($this->basePath() . '/components/bootstrap/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/components/bootstrap/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/components/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/components/jquery-ui/themes/base/jquery-ui.min.css')
                ->prependStylesheet($this->basePath() . '/components/jquery-ui/themes/base/jquery-ui.theme.min.css')
                ->prependStylesheet($this->basePath() . '/components/jquery-timepicker-addon/dist/jquery-ui-timepicker-addon.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/components/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/components/jquery-timepicker-addon/dist/jquery-ui-timepicker-addon.js')
            ->prependFile($this->basePath() . '/components/jquery-ui/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/components/jquery/jquery.min.js')            
            ->appendFile($this->basePath() . '/js/custom_backend.js')
            ->appendFile($this->basePath() . '/vendor/raphael/raphael.min.js')
            ->appendFile($this->basePath() . '/vendor/morrisjs/morris.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <?php if (!isset($this->config()['environment'])) : ?>
        <div class="alert alert-danger text-center">
            <p>Please add the <strong>environment</strong> config key to one of your local configurations.</p>
        </div>
        <?php elseif ($this->config()['environment'] != 'production') : ?>
        <div class="alert alert-danger text-center">
            <p>Keep in mind this environment is for: <strong><?php echo $this->config()['environment']; ?></strong></p>
        </div>
        <?php endif; ?>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('admin') ?>"><?php echo 'ERS AdminPanel'; ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php 
                    $partial = array('partial/admin-main-nav.phtml', 'admin_main_nav');
                    $this->navigation()->menu('admin_main_nav')->setPartial($partial);
                    echo $this->navigation()->menu('admin_main_nav')->render(); 
                    ?>

                    <div class="nav navbar-nav navbar-right">
                    <?php 
                    $partial_right = array('partial/admin-main-nav.phtml', 'admin_top_nav');
                    echo $this->navigation()
                        ->menu('admin_top_nav')
                        ->setPartial($partial_right)
                        ->setUlClass(''); ?>
                    </div>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php 
                echo $this->flashMessenger()
                        ->setMessageOpenFormat('<div%s><p>')
                        ->setMessageCloseString('</p></div>')
                        ->render('error', ['alert', 'alert-danger']);

                echo $this->flashMessenger()
                        ->setMessageOpenFormat('<div%s><p>')
                        ->setMessageCloseString('</p></div>')
                        ->render('warning', ['alert', 'alert-warning']);

                
                echo $this->flashMessenger()
                        ->setMessageOpenFormat('<div%s><p>')
                        ->setMessageCloseString('</p></div>')
                        ->render('success', ['alert', 'alert-success']);
            ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p style="float:right;">
                    <a href="https://github.com/inbaz/ers/issues" target="_blank">report a bug</a><br />
                    <span>Version: <?php echo exec('git symbolic-ref -q HEAD || git describe --tags --exact-match'); ?></span>
                </p>
                <p>&copy; <!--2014 - --><?php echo date('Y') ?> by European Juggling Association <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
