<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php #echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headTitle($this->translate('EJC Registration System'))->setSeparator(' - ')->setAutoEscape(false)  // change Skeleton Application to Sticky Notes ?> 

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/js/jquery-ui/jquery-ui.min.css')
                ->prependStylesheet($this->basePath() . '/js/jquery-ui/jquery-ui.theme.min.css')
                ->prependStylesheet($this->basePath() . '/js/jquery-ui/jquery-ui.structure.min.css')
                ->prependStylesheet($this->basePath() . '/js/datetimepicker/jquery-ui-timepicker-addon.min.css')
                ->appendStylesheet($this->basePath() . '/css/custom.css')
                
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/datetimepicker/jquery-ui-timepicker-addon.min.js')
                ->prependFile($this->basePath() . '/js/multidatespicker/jquery-ui.multidatespicker.min.js')
                ->prependFile($this->basePath() . '/js/jquery-ui/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/js/custom.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <!--<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar">foo</span>
                        <span class="icon-bar">bar</span>
                        <span class="icon-bar">baz</span>
                    </button>
                    
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?php $this->basePath(); ?>/img/ejc_logo.png" alt="" />
                        <?php echo $this->translate('Registration System') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                        echo $this->navigation()
                            ->menu('top_nav')
                            ->setUlClass('nav nav-pills nav-top-right');
                        
                        echo $this->navigation()
                            ->menu('main_nav')
                            ->setUlClass('nav navbar-nav');
                    ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="inner-container main-container">
                <?php echo $this->content; ?>
            </div> <!-- /container -->
        </div>
        <div class="footer">
            <hr>
            <footer>
                <p style="float:right;">
                    <a href="https://github.com/inbaz/ers/issues" target="_blank">report a bug</a><br />
                    <span>Version: <?php echo exec('git describe --tags --exact-match'); ?></span>
                    <!--<a href="#" target="_blank">participant counter</a>-->
                </p>
                <p>&copy; 2014 - <?php echo date('Y') ?> by European Juggling Association <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /footer -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
