<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta property="og:locale" content="de_DE" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Event Registration System" />
        <meta property="og:description" content="Get your ticket for <?php echo $this->layout()->ers_config['name_with_year']; ?>" />
        <meta property="og:url" content="<?php echo $this->serverUrl(); ?>" />
        <meta property="og:site_name" content="Event Registration System - ERS" />
        <?php if($this->setting('ers.og_image')): ?>
            <meta property="og:image" content="<?php echo $this->serverUrl($this->setting('ers.og_image')); ?>" />
        <?php endif; ?>
        
        <?php echo $this->headTitle($this->translate('Event Registration System'))->setSeparator(' - ')->setAutoEscape(false)  // change Skeleton Application to Sticky Notes ?> 

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/components/bootstrap/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/components/bootstrap/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/components/font-awesome/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/css/cookiecuttr.css')
                ->prependStylesheet($this->basePath() . '/components/jquery-ui/themes/base/minified/jquery-ui.min.css')
                ->prependStylesheet($this->basePath() . '/components/jquery-ui/themes/base/minified/jquery.ui.theme.min.css')
                ->prependStylesheet($this->basePath() . '/components/jquery-timepicker-addon/dist/jquery-ui-timepicker-addon.css')
                ->appendStylesheet($this->basePath() . '/css/custom.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/components/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/components/jquery-timepicker-addon/dist/jquery-ui-timepicker-addon.js')
            ->prependFile($this->basePath() . '/components/jquery-ui/ui/minified/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/components/jquery/jquery.min.js')        
            ->prependFile($this->basePath() . '/js/jquery.cookiecuttr.js')
            ->prependFile($this->basePath() . '/js/jquery.cookie.js')
            ->appendFile($this->basePath() . '/js/custom.js')
            ->prependFile($this->basePath() . '/components/respond/respond-built.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/components/html5shiv/html5shiv-built.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        

        <?php if (isset($this->config()['environment']) && $this->config()['environment'] != 'production') : ?>
        <!-- Hotjar Tracking Code for prereg.eja.net -->
        <!--<script>
            (function(h,o,t,j,a,r){
                h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                h._hjSettings={hjid:82996,hjsv:5};
                a=o.getElementsByTagName('head')[0];
                r=o.createElement('script');r.async=1;
                r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                a.appendChild(r);
            })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
        </script>-->
        <?php endif; ?>
        
    </head>
    <body>
        <?php if (!isset($this->config()['environment'])) : ?>
        <div class="alert alert-danger text-center">
            <p>Please add the <strong>environment</strong> config key to one of your local configurations.</p>
        </div>
        <?php elseif ($this->config()['environment'] != 'production') : ?>
        <div class="alert alert-danger text-center">
            <p>Keep in mind this environment is for: <strong><?php echo $this->config()['environment']; ?></strong></p>
        </div>
        <?php endif; ?>
        <!--<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <?php 
                    $partial = array('partial/main-nav.phtml', 'main_nav');
                    $this->navigation()
                            ->menu('main_nav')
                            ->setPartial($partial);
                    echo $this->navigation()
                            ->menu('main_nav')
                            ->render(); 
                    ?>

                    <?php 
                    $right_partial = array('partial/main-right-nav.phtml', 'top_nav');
                    $this->navigation()
                            ->menu('top_nav')
                            ->setPartial($right_partial);
                    echo $this->navigation()
                            ->menu('top_nav')
                            ->render(); 
                    ?>
                    <?php /*echo $this->navigation()
                            ->menu('main_nav')
                            ->setUlClass('nav navbar-nav');*/ ?>
                    <?php /*echo $this->navigation()
                            ->menu('top_nav')
                            ->setUlClass('nav navbar-nav navbar-right');*/ ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="inner-container main-container">
                <?php 
                echo $this->flashMessenger()
                        ->setMessageOpenFormat('<div%s><p>')
                        ->setMessageCloseString('</p></div>')
                        ->render('error', ['alert', 'alert-danger']);

                echo $this->flashMessenger()
                        ->setMessageOpenFormat('<div%s><p>')
                        ->setMessageCloseString('</p></div>')
                        ->render('warning', ['alert', 'alert-warning']);

                
                echo $this->flashMessenger()
                        ->setMessageOpenFormat('<div%s><p>')
                        ->setMessageCloseString('</p></div>')
                        ->render('success', ['alert', 'alert-success']);
                ?>

                <?php echo $this->content; ?>
            </div> <!-- /container -->
        </div>
        <div class="footer">
            <hr>
            <footer>
                <p style="float:right;">
                    <a href="<?php echo $this->url('info', array('action' => 'terms')); ?>" target="_blank"><?php echo _('terms and conditions'); ?></a><br />
                    <a href="<?php echo $this->url('info', array('action' => 'impressum')); ?>"><?php echo _('impressum'); ?></a><br />
                    <a href="https://github.com/inbaz/ers/issues" target="_blank"><?php echo _('report a bug'); ?></a><br />
                    <span>Version: <?php echo exec('git symbolic-ref -q HEAD || git describe --tags --exact-match'); ?></span>
                </p>
                <p>&copy; 2014 - <?php echo date('Y') ?> <?php echo $this->config()['ERS']['operator'] ?> <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /footer -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
