<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php #echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headTitle($this->translate('ERS Onsite Reg'))->setSeparator(' - ')->setAutoEscape(false)  // change Skeleton Application to Sticky Notes ?> 

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/css/custom.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/js/jquery-ui/jquery-ui.theme.min.css')
                ->prependStylesheet($this->basePath() . '/js/jquery-ui/jquery-ui.structure.min.css')
                ->prependStylesheet($this->basePath() . '/js/jquery-ui/jquery-ui.min.css')
                ->prependStylesheet($this->basePath() . '/js/datetimepicker/jquery-ui-timepicker-addon.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/datetimepicker/jquery-ui-timepicker-addon.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')            
            ->appendFile($this->basePath() . '/js/custom_onsite.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <?php if (!isset($this->config()['environment'])) : ?>
        <div class="alert alert-danger text-center">
            <p>Please add the <strong>environment</strong> config key to one of your local configurations.</p>
        </div>
        <?php elseif ($this->config()['environment'] != 'production') : ?>
        <div class="alert alert-danger text-center">
            <p>Keep in mind this environment is for: <strong><?php echo $this->config()['environment']; ?></strong></p>
        </div>
        <?php endif; ?>
        <nav class="navbar navbar-default navbar-inverse" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar">foo</span>
                    <span class="icon-bar">bar</span>
                    <span class="icon-bar">baz</span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('onsite') ?>"><?php echo 'ERS Onsite Reg'; ?></a>
            </div>
            <?php echo $this->navigation()
                ->menu('onsite_top_nav')
                ->setUlClass('nav nav-pills nav-top-right'); ?>

            <?php $partial = array('partial/onsite-main-nav.phtml', 'onsite_main_nav') ?>
            <?php $this->navigation()->menu('onsite_main_nav')->setPartial($partial) ?>
            <?php echo $this->navigation()->menu('onsite_main_nav')->render() ?>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p style="float:right;">
                    <a href="https://github.com/inbaz/ers/issues" target="_blank">report a bug</a><br />
                    <span>Version: <?php echo exec('git symbolic-ref -q HEAD || git describe --tags --exact-match'); ?></span>
                </p>
                <p>&copy; <!--2014 - --><?php echo date('Y') ?> by European Juggling Association <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
