<?php
    $ejc_with_year = "EJC 2016";
    $ejc_with_number = "39th European Juggling Convention";
    $ejc_info_mail = "info@ejc2016.org";
    $ejc_website = "http://www.ejc2016.org";
?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .header, .footer {
            	width: 100%;
            	text-align: center;
            	padding: 1em;
            }
            .header {
            	margin-top: 0px;
            	background-color: #85b32a;
            	color: #fff;
            }
            .clear-both {
                clear: both;
            }
            .header > a {
            	color: #fff;
            	font-weight: bold;
            	text-decoration: none;
            }
            .footer {
            	background-color: #eeeeee;
            }
        </style>
    </head>
    <body>
        <div class='header'>EJC 2016 - 30.07.2016 - 07.08.2016 in Almere, The Netherlands - <a href='http://www.ejc2016.org'>www.ejc2016.org</a></div>

        <?php 
        $participant = $package->getParticipant(); 
        $order = $package->getOrder();
        ?>
        
        <p>Dear <?php echo $participant->getFirstname().' '.$participant->getSurname(); ?>,</p>
        <p><strong style="color: red;">here’s your correct e-ticket!</strong> Sorry, we got the first version wrong. It’s important that you have <strong style="color: red;">THIS version</strong> with you, because it’s about whether you can access the EJC site without a parent / chaperon or not. 16 and 17 year olds can, under 16s need a legal guardian onsite! We confused that in the earlier version. Sorry for the inconvenience!</p>
        <p>
            So again, please, <strong>check whether your name and your date of birth on the e-ticket fit in with your passport or identity card.</strong>
            If not, please send an email with your order number and the updated data to <a href="mailto:prereg@eja.net">prereg@eja.net</a>. We’ll change the data and you will receive the up-to-date e-ticket. Please note that you cannot register onsite if your name and date of birth don’t match your ID card.
        </p>
        <p>
            We received the payment for your order with ID <?php echo $order->getCode()->getValue(); ?> from <?php echo $order->getCreated()->format('d.m.Y'); ?>. The payment to your order is now confirmed. Attached to this email, you can find your e-ticket. It’s in English. If you’d like to read the text in <strong>another language</strong>, visit 
            <a href="http://prereg.eja.net<?php echo $this->url('info', array(
                'action' => 'e-ticket'
                )); ?>">http://prereg.eja.net<?php echo $this->url('info', array(
                    'action' => 'e-ticket'
                    )); ?></a>.
        </p>
        <p><strong>Print and sign this e-ticket.</strong> Bring it to the EJC together with your <strong>valid ID card</strong> and present both documents at the registration desk.</p>
        <p>To be able to read the documents, you need to install Adobe Acrobat Reader, which you can download here: <a href="http://get.adobe.com/reader/">http://get.adobe.com/reader/</a>.</p>
        <p>For the latest information about EJC 2016, stay tuned to <a href="http://www.ejc2016.org">www.ejc2016.org</a>. If you have any further questions concerning your EJC 2016 e-ticket, please contact the prereg coordinator via <a href="mailto:prereg@eja.net">prereg@eja.net</a>.</p>
        <p>We wish you a pleasant journey and we are looking forward welcoming you soon.</p>
        <p>Best regards,<br />
        Your European Juggling Association and the EJC 2016 organisers</p>
    </body>
</html>