<?php
    #old
    /*$ejc_with_year = "EJC 2016";
    $ejc_with_number = "39th European Juggling Convention";
    $ejc_info_mail = "info@ejc2016.org";
    $ejc_website = "http://www.ejc2016.org";*/
    
    # new
    $config = $this->config();
    $website = '<a href="'.$config['ERS']['website'].'">'.$config['ERS']['website'].'</a>';
    $infoMail = '<a href="mailto:'.$config['ERS']['info_mail'].'">'.$config['ERS']['info_mail'].'</a>';
    $adobeReaderLink = '<a href="http://get.adobe.com/reader/">http://get.adobe.com/reader/</a>';
    $termsLink = '<a href="'.$this->url('info', array('action' => 'terms'), array('force_canonical' => true)).'">'.$this->translate('terms and conditions').'</a>';
    
    $participant = $package->getParticipant(); 
    $order = $package->getOrder();
?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .header, .footer {
            	width: 100%;
            	text-align: center;
            	padding: 10px;
            }
            .header {
            	margin-top: 0px;
            	background-color: #f48029;
            	color: #fff;
            }
            .clear-both {
                clear: both;
            }
            .header a {
            	color: #fff;
            	font-weight: bold;
            	text-decoration: underline;
            }
            .footer {
            	background-color: #eeeeee;
            }
        </style>
    </head>
    <body>
        <div class='header'>
            <?php echo $config['ERS']['name_with_year'].' - '.$config['ERS']['start']->format('d.m.Y').' - '.$config['ERS']['end']->format('d.m.Y').' - '.$website; ?>
        </div>
        
        <p><?php printf($this->translate('Dear %s %s,'),
                $participant->getFirstname(),
                $participant->getSurname()); ?></p>
        <p><?php printf($this->translate('thank you again for registering for %s.'), $config['ERS']['name_with_year']); ?></p>
        <p>
            <?php printf($this->translate('We received the payment for your oder with ID %s from %s. The payment to your order is now confirmed. You find your e-ticket attached to this email.'), 
                    $order->getCode()->getValue(), 
                    $order->getCreated()->format('d.m.Y')); ?>
        </p>
        <p>
            <?php 
            printf($this->translate('First of all, <strong>please make sure that your name and date of birth on the e-ticket are identical to your name and date of birth on your identity card</strong>. If they aren’t, please send an email with your order number and the updated data to %s. We will then change the data and send you an up-to-date e-ticket. Please note that you cannot register onsite if your name and date of birth don’t match your ID card.'),
                    $infoMail); ?>
        </p>
        <p>
            <?php printf($this->translate('Please bring the e-ticket and a valid ID card to the event and present both documents at the registration desk. You can either print the e-ticket or present it on an electronic device.')); ?>
        </p>
        
        <p>
            <?php printf($this->translate('To be able to read the documents, you need to install Adobe Acrobat Reader, which you can download here: %s.'), $adobeReaderLink); ?>
        </p>
        
        <p><?php printf($this->translate('By registering for this event, you agree to the terms and conditions of attendance and participation as stated on our website at %s.'), $termsLink); ?></p>
        
        <p><?php printf($this->translate('For the latest information about %s stay tuned to %s. If you have any further questions concerning your e-ticket, please contact us via %s.'),
                $config['ERS']['name_with_year'],
                $website,
                $infoMail
                ); ?></p>
        
        <p><?php printf($this->translate('We wish you a pleasant journey and we’re looking forward to welcoming you soon!')) ?></p>
        
        <p><?php echo $this->translate('Best regards,'); ?><br />
            <?php echo $config['ERS']['salutation']; ?></p>
        
        
    </body>
</html>