<?php
    $website = '<a href="'.$this->setting('ers.website').'">'.$this->setting('ers.website').'</a>';
    
    $participant = $package->getParticipant(); 
    $order = $package->getOrder();
    
    
    $primaryColor = $this->setting('pdf.primary-color');
    if($primaryColor == '' || substr($primaryColor,1,1) != '#') {
        $primaryColor = '#F48029';
    }
?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .header, .footer {
            	width: 100%;
            	text-align: center;
            	padding: 10px;
            }
            .header {
            	margin-top: 0px;
            	background-color: <?php echo $primaryColor; ?>;
            	color: #fff;
            }
            .clear-both {
                clear: both;
            }
            .header a {
            	color: #fff;
            	font-weight: bold;
            	text-decoration: underline;
            }
            .footer {
            	background-color: #eeeeee;
            }
        </style>
    </head>
    <body>
        <div class='header'>
            <?php echo $this->setting('ers.name_with_year').' - '.$this->setting('ers.start', 'date', ['fromFormat' => 'Y-m-d', 'toFormat' => '%a %d.%m.%Y']).' - '.$this->setting('ers.end', 'date', ['fromFormat' => 'Y-m-d', 'toFormat' => '%a %d.%m.%Y']).' - '.$website; ?>
        </div>
        
        <div class="content">
            <?php echo $this->setting('email.e-ticket'); ?>
        </div>
    </body>
</html>
