<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .clear-both {
                clear: both;
            }
        </style>
    </head>
    <body>
        <p>Dear <?php echo $order->getPurchaser()->getFirstname().' '.$order->getPurchaser()->getSurname(); ?>,</p>

        <p>This is the confirmation for your order from <?php echo $order->getCreated()->format('d.m.Y'); ?> with the order ID <?php echo $order->getCode()->getValue(); ?>.</p>

        <p>Thank you for registering for the 38th European Juggling Convention! Your registration helps us to improve the EJC 2015 for you and for all fellow jugglers.</p>

        <p>You chose <?php echo $order->getPaymentType()->getName(); ?> as payment method.</p>

        <p>Please transfer the entire amount of your order within 14 days. To gain from the pre-booking conditions, please make sure that the payment is processed on time (31st of May / 15th of June), even if there are less than 14 days left.</p>

        <p>In case you chose 'bank transfer' as payment method please transfer the entire amount of your order to the following account:</p>
        <?php echo $this->partial('partial/banktransfer-info.phtml', array('order' => $order)); ?>

        <p>Please state your order ID <?php echo $order->getCode()->getValue(); ?> as reference at your transfer form.</p>

        <p>In case you chose credit card as payment method and your payment was not successful, you can restart your credit card payment via the following link:</p>
        <a href="#">%resume_link%</a>

        <p>Please consider our general terms and conditions, which are attached to this email. To be able to read the document, you need to install Adobe Acrobat Reader, which you can download here: <a href="http://get.adobe.com/de/reader">http://get.adobe.com/de/reader</a></p>

        <p>Your eTickets and further information concerning the 38th European Juggling Convention will be delivered in another email after your payment has been confirmed.</p>

        <p>We are looking forward to welcoming you in Bruneck!</p>

        <p>Best regards,<br />
        Your European Juggling Association and the local EJC 2015 organizers</p>

        <hr />
        <p>You purchased the following items:</p>
        <?php echo $this->partial('partial/order-info.phtml', array('order' => $order)); ?>

    </body>
</html>