<?php
    $orderLink = '<a href="' . 
            $this->url('order', array(
                'action' => 'view',
                'hashkey' => $order->getHashKey()
            ), array('force_canonical' => true)) . 
            '">' . $this->translate('your order') . '</a>';
    $termsLink = '<a href="' . 
            $this->url('info',
                array('action' => 'terms'),
                array('force_canonical' => true)
            ).'">' . $this->translate('terms and conditions') . '</a>';
    $orderDate = $order->getCreated()->format('d.m.Y');
    $orderId = '<b>'.$order->getCode()->getValue().'</b>';
    $preregMail = '<a href=\'mailto:'.$this->config()['ERS']['prereg_mail'].'\'>'.$this->config()['ERS']['prereg_mail'].'</a>';
    $infoMail = '<a href=\'mailto:'.$this->config()['ERS']['info_mail'].'\'>'.$this->config()['ERS']['info_mail'].'</a>';
    $website = '<a href=\''.$this->config()['ERS']['website'].'\'>'.$this->config()['ERS']['website'].'</a>';
?>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
</head>
<body>
<div style="font-family: sans-serif;">
    <p><?php printf($this->translate('Dear %s %s,'), $order->getBuyer()->getFirstname(), $order->getBuyer()->getSurname()); ?></p>

    <p>
        
        <?php 
        
        printf($this->translate('This is the confirmation for %s from %s with the order ID %s.'),
                $orderLink,
                $orderDate,
                $orderId); ?>
    </p>

    <!--<p>
        To receive this email in another language you can visit the <a href="<?php echo $this->url('order', array(
            'action' => 'email',
            'hashkey' => $order->getHashKey()
        ), array('force_canonical' => true)); ?>">resend email link</a>.
    </p>-->

    <p><?php printf($this->translate('Thank you for registering for the %s!'), $this->config()['ERS']['name_with_number']); ?></p>

    <p><?php printf($this->translate('You\'ve chosen %s as payment method.'), $order->getPaymentType()->getName()); ?></p>

    <?php
    $paymenttype = $order->getPaymentType();
    if($paymenttype->getType() == 'sepa'): ?>

        <p><?php echo $this->translate('To complete your order, we need to receive your bank transfer within 14 days.'); ?></p>

        <?php echo $this->partial('partial/sepa-banktransfer-info.phtml', array('order' => $order)); ?>

        <p><?php printf($this->translate('To see if we have already received your payment, you can visit the following link: %s'), $orderLink); ?></p>

    <?php elseif($paymenttype->getType() == 'ukbt'): ?>

        <p><?php echo $this->translate('To complete your order, we need to receive your bank transfer within 14 days.'); ?></p>

        <?php echo $this->partial('partial/ukbt-banktransfer-info.phtml', array('order' => $order)); ?>

        <p><?php printf($this->translate('To see if we have already received your payment, you can visit the following link: %s'), $orderLink); ?></p>
    <?php elseif($paymenttype->getType() == 'cheque'): ?>

        <p>The conversation rate Euro to Pounds for cheques is set to 0.8 -
            this means that you need to multiply the price with 0.8, i.e.
            120 EUR --> 96 GBP.</p>
        <p>​​Please make cheques payable to: <strong>European Juggling
            Association</strong>.</p>
        <p>Your order amount in GBP is: <strong>
            <?php
            $pound = ($order->getSum()*0.8);
            echo $this->currencyFormat($pound, 'GBP', null, 'en_GB');
            ?>
                </strong></p>
        <p>Please send:</p>
        <ul>
            <li>Cheques (amount in GBP, price calculated from Euro-price * 0,8 )</li>
            <li>your name</li>
            <li>order ID <?php echo $order->getCode()->getValue(); ?></li>
            <li>to the address of the UK country-rep:<br /><br />
                Ron Trickett<br />
                14 Peterborough Road<br />
                Newton Hall<br />
                Durham<br />
                DH1 5QX<br />
            </li>
        </ul>
        <p>If you ordered a discounted ticket (phase 1 or phase 2), please
            make sure that your cheque is received within 14 days after the
            end of this phase (i.e. 14th of May / 14th of July).</p>
        <p>To see if we have already received your payment, you can visit the following link:
        <a href="<?php echo $this->url('order', array(
            'action' => 'view',
            'hashkey' => $order->getHashKey()
        ), array('force_canonical' => true)); ?>">Your order details</a></p>

    <?php elseif($paymenttype->getType() == 'creditcard'): ?>

        <p>We should have received your payment by now.</br>
            In case your payment was not successful, you can restart your
            credit card payment via the following link:
            <a href="<?php echo $this->url('order', array(
                'action' => 'view',
                'hashkey' => $order->getHashKey()
            ), array('force_canonical' => true)); ?>">Your order details</a></p>

    <?php elseif($paymenttype->getType() == 'paypal'): ?>

        <p><?php echo $this->translate('We should have received your payment by now.'); ?><br>
            <?php echo $this->translate('In case your payment was not successful, you can restart your
            PayPal payment via the following link:'); ?>
            <a href="<?php echo $this->url('order', array(
                'action' => 'view',
                'hashkey' => $order->getHashKey()
            ), array('force_canonical' => true)); ?>"><?php echo $this->translate('Your order details'); ?></a></p>

    <?php endif; ?>

    <p>
        <?php printf($this->translate('Please consider our general %s.
        To be able to read the document, you need to install Adobe Acrobat Reader, which you can download here:'), $termsLink); ?>
        <a href="http://get.adobe.com/reader">http://get.adobe.com/reader</a>
    </p>

    <p>
        <?php printf($this->translate('Your E-Tickets and further information concerning the %s will be delivered in another email
        as soon as we start distributing the E-Tickets and your payment has been confirmed.'), $this->config()['ERS']['name_with_number']); ?>
    </p>
    <p>
        We would also like to ask for your help in spreading the word about the EJC!
        As you know the festival is financed directly from ticket sale. It would be AWESOME if you could invite your friends to join the EJC 2017 and register!
        We have prepared a little graphics that you can use if you want to help and spread the excitement about the upcoming convention that we all share! :) 
        Its size is tailored to fit the FaceBook cover photo, but please use it wherever you want!
    </p>

    <p><?php $this->translate('Regards,'); ?></p>

    <p><?php printf($this->translate('Your European Juggling Association and the local %s organisers.'), $this->config()['ERS']['name_with_number']); ?></p>

    <hr>
    <p>
        <?php printf($this->translate('You purchased the following items (ordered by %s %s):'), $order->getBuyer()->getFirstname(), $order->getBuyer()->getSurname()); ?>
    </p>

    <?php echo $this->partial('partial/order-info.phtml', array('order' => $order)); ?>

    <div style="width: 100%;
            text-align: center;
            padding: 1em;
            background-color: #eeeeee;">
        <?php printf($this->translate('This mail was sent to you by the Event Registration System (ERS),
        operated by the European Juggling Association (EJA) on
        behalf of %s.'), $this->config()['ERS']['name_with_year']); ?>
        <br>
        <?php printf($this->translate('If you have any questions about your pre-registration,
        please contact the EJA pre-registration coordinator
        at %s.'), $preregMail); ?>
        <br>
        <?php printf($this->translate('For more information about %s,
        please visit %s
        or contact %s.'), 
        $this->config()['ERS']['name_with_year'],
        $website,
        $infoMail); ?>
    </div>
</div>
</body>
</html>
