<?php
    # new
    $config = $this->config();
    $website = '<a href="'.$config['ERS']['website'].'">'.$config['ERS']['website'].'</a>';
    $infoMail = '<a href="mailto:'.$config['ERS']['info_mail'].'">'.$config['ERS']['info_mail'].'</a>';
    $adobeReaderLink = '<a href="http://get.adobe.com/reader/">http://get.adobe.com/reader/</a>';
    $termsUrl = $this->url('info', array('action' => 'terms'), array('force_canonical' => true));
    $termsLink = '<a href="'.$termsUrl.'">'.$this->translate('terms and conditions').'</a>';
    $orderUrl = $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey()), array('force_canonical' => true));;
    $orderLink = '<a href="'.$orderUrl.'">'.$orderUrl.'</a>';
    
    #$participant = $package->getParticipant(); 
    #$order = $package->getOrder();
    $buyer = $order->getBuyer();
?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .header, .footer {
            	width: 100%;
            	text-align: center;
            	padding: 1em;
            }
            .header {
            	margin-top: 0px;
            	background-color: #ea5356;
            	color: #fff;
            }
            .clear-both {
                clear: both;
            }
            .header > a {
            	color: #fff;
            	font-weight: bold;
            	text-decoration: none;
            }
            .footer {
            	background-color: #eeeeee;
            }
        </style>
    </head>
    <body>
        <div class='header'>
            <?php echo $config['ERS']['name_with_year'].' - '.$config['ERS']['start']->format('d.m.Y').' - '.$config['ERS']['end']->format('d.m.Y').' - '.$website; ?>
        </div>

        <p><?php printf($this->translate('Dear %s %s,'),
                $buyer->getFirstname(),
                $buyer->getSurname()); ?></p>

        <p><?php printf($this->translate('you registered for the %s at %s and we hope you\'re looking forward to it. We haven\'t sent you an e-ticket yet, because we haven\'t received payment for your order.'), 
                $config['ERS']['name_with_year'],
                $order->getCreated()->format('d.m.Y')) ?></p>

        <?php $paymentTarget = new \DateTime('now +14 days'); ?>
        <p><?php printf($this->translate('Please do one of the following until %s at the latest.'), $paymentTarget->format('d.m.Y')); ?></p>
        <ul>
            <li><?php printf($this->translate('Please pay your order. All needed information can be found at %s'),$orderLink); ?></li>
            <li><?php printf($this->translate('Let us know if you\'d like to transfer your ticket to somebody else (necessary data: first name, last name, date of birth and email address of the new participant)')); ?></li>
            <li><?php printf($this->translate('If none of the above options are possible for you, let us know if you\'d like us to cancel your ticket.')); ?></li>
        </ul>

        <p><?php echo $this->translate('Best regards,'); ?><br />
            <?php echo $config['ERS']['salutation']; ?></p>
    </body>
</html>
