<?php
    # new
    $config = $this->config();
    $website = '<a href="'.$config['ERS']['website'].'">'.$config['ERS']['website'].'</a>';
    #$infoMail = '<a href="mailto:'.$config['ERS']['info_mail'].'">'.$config['ERS']['info_mail'].'</a>';
    #$adobeReaderLink = '<a href="http://get.adobe.com/reader/">http://get.adobe.com/reader/</a>';
    #$termsUrl = $this->url('info', array('action' => 'terms'), array('force_canonical' => true));
    #$termsLink = '<a href="'.$termsUrl.'">'.$this->translate('terms and conditions').'</a>';
    #$orderUrl = $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey()), array('force_canonical' => true));;
    #$orderLink = '<a href="'.$orderUrl.'">'.$orderUrl.'</a>';
    
    #$participant = $package->getParticipant(); 
    #$order = $package->getOrder();
    #$buyer = $order->getBuyer();
?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .header, .footer {
            	width: 100%;
            	text-align: center;
            	padding: 1em;
            }
            .header {
            	margin-top: 0px;
            	background-color: #ea5356;
            	color: #fff;
            }
            .clear-both {
                clear: both;
            }
            .header > a {
            	color: #fff;
            	font-weight: bold;
            	text-decoration: none;
            }
            .footer {
            	background-color: #eeeeee;
            }
        </style>
    </head>
    <body>
        <div class='header'>
            <?php echo $this->setting('ers.name_with_year').' - '.$this->setting('ers.start', 'date', ['fromFormat' => 'Y-m-d', 'toFormat' => '%a %d.%m.%Y']).' - '.$this->setting('ers.end', 'date', ['fromFormat' => 'Y-m-d', 'toFormat' => '%a %d.%m.%Y']).' - '.$website; ?>
        </div>

        <div class="content">
            <?php echo $this->setting('email.payment-reminder'); ?>
        </div>
    </body>
</html>
