<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .clear-both {
                clear: both;
            }
        </style>
    </head>
    <body>
        <?php echo $this->partial('partial/sepa-banktransfer-info.phtml', array('order' => $order)); ?>
    </body>
</html>