<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .clear-both {
                clear: both;
            }
        </style>
    </head>
    <body>
        <p><?php echo $this->translate('Dear').' '.$user->getFirstname().' '.$user->getSurname(); ?>,</p>

        <p><?php echo $this->translate('You can set the password for your user account via this link:'); ?></p>
        <?php $link = $this->url('profile', array(
            'action' => 'password-reset', 'hashkey' => $user->getHashKey(),
            ), array('force_canonical' => true)); ?>
        
        <p><a href='<?php echo $link ?>'><?php echo $link; ?></a></p>
        
        <p><?php echo $this->translate('If you cannot click on this link copy the link into the address bar of your browser.'); ?></p>
        <p><?php echo $this->translate('This link will be available for the next 24 hours.'); ?></p>
        <p><?php echo $this->translate('Best regards'); ?><br />

    </body>
</html>
