<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .clear-both {
                clear: both;
            }
        </style>
    </head>
    <body>
        <p>Dear <?php echo $user->getFirstname().' '.$user->getSurname(); ?>,</p>

        <p>You can set the password for your user account via this link:</p>
        <?php $link = $this->url('profile', array(
            'action' => 'password-reset', 'hashkey' => $user->getHashKey(),
            ), array('force_canonical' => true)); ?>
        
        <p><a href='<?php echo $link ?>'><?php echo $link; ?></a></p>
        
        <p>If you cannot click on this link copy the link into the address bar 
            of your browser.</p>
        <p>This link will be available for the next 2 hours.</p>
        <p>Best regards,<br />
        Your European Juggling Association and the local EJC 2016 organizers</p>

    </body>
</html>