<div class="panel-body">
    <?php if(!$order): ?>
    <div class="alert alert-warning">
        <h3>Order could not be found.</h3>
    </div>
    <?php else: ?>
    <div class="row">
        <?php $paymenttype = $order->getPaymentType(); ?>
        <a href="<?php echo $this->url('admin/order', array('action' => 'detail', 'id' => $order->getId())); ?>">link to order</a>
        <div class="col-md-12">
            <?php 
            $sum = 0;
            foreach ($order->getPackages() as $package) : 
                if(count($package->getItems()) == 0) {
                    continue;
                }
                $user = $package->getParticipant();

                if($user->getFirstname() == '' && $user->getSurname() == '') :
                    $participant = 'unassigned items';
                else:
                    $participant = $user->getFirstname().' '.$user->getSurname();
                endif;
            ?>
            <div class="package">
                <h3><?php echo $participant; ?></h3>

                <?php if(count($package->getItems()) != 0): ?>
                <table class="table">
                    <tr>
                        <th>Product</th>
                        <th class="cart-amount">Amount</th>
                        <th class="cart-price">Price</th>
                    </tr>
                    <?php
                    $subtotal = 0;
                    foreach ($package->getItems() as $item) : 
                        $subtotal += $item->getPrice();
                        $sum += $item->getPrice();
                        ?>
                        <tr>
                            <td>
                                <span class="product-name">
                                    <?php echo $item->getName(); ?>
                                </span>
                                <span class="product-variants">
                                    <?php if(count($item->getItemVariants()) > 0): ?>
                                    (
                                    <?php 
                                    $numVariants = count($item->getItemVariants()); 
                                    $i = 0;
                                    $variants = array();
                                    ?>
                                    <?php foreach($item->getItemVariants() as $variant): 
                                        echo $variant->getName().': '.$variant->getValue(); 
                                        if(++$i != $numVariants):
                                            echo '; ';
                                        endif;
                                        $variants[] = array(
                                            'pv' => $variant->getProductVariantId(),
                                            'pvv' => $variant->getProductVariantValueId(),
                                            );
                                    endforeach; ?>
                                    )
                                    <?php endif; ?>
                                </span>
                            </td>
                            <td><?php echo $item->getAmount(); ?></td>
                            <td><?php echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td>Subtotal:</td>
                        <td><?php echo $this->currencyFormat($subtotal, 'EUR', null, 'de_DE'); ?></td>
                    </tr>
                </table>
                <?php endif; ?>
            </div>
            <?php endforeach; ?>

            <?php if($paymenttype) : ?>
                <h3><?php echo $paymenttype->getName(); ?></h3>
            <?php else: ?>
                <?php $form->get('submit')->setAttribute('disabled', 'disabled'); ?>
                <a href="<?php echo $this->url('order', array('action' => 'payment')); ?>">choose paymenttype</a>
            <?php endif; ?>
            <table class="table sum-table">
                <tr>
                    <td>Order amount:</td>
                    <td class="text-right"><?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <td>Payment Charge:</td>
                    <td class="text-right"><?php echo $this->currencyFormat($paymenttype->calcFee($order->getPrice()), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <th><span style="font-size: 18px;">Total amount:</span></th>
                    <th class="text-right"><span style="font-size: 18px;"><?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></span></th>
                </tr>
            </table>
        </div>
    </div>
    <?php endif; ?>
</div>