<?php

$title = 'Change currency of order '.$order->getCode()->getValue();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/order', 
        array(
            'action' => 'change-currency',
            'id' => $order->getId()
            )
        ));
$form->prepare();

echo $this->form()->openTag($form); ?>

<div class="row">
    <div class="col-md-6">
        <?php echo $this->formRow($form->get('currency_id')); ?>
    </div>
    <div class="col-md-6">
        <?php echo $this->formRow($form->get('paymenttype_id')); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12 text-right">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
</div>

<?php echo $this->formHidden($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>