<?php 
$package = $item->getPackage();
$order = $package->getOrder();
$participant = $package->getParticipant();
$title = 'Change Item for '.$participant->getFirstname().' '.$participant->getSurname();
$this->headTitle($title);
?>
<a href="<?php echo $this->url('admin/order', array('action' => 'detail', 'id' => $order->getId())); ?>">back to order detail</a>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<h2><?php echo $item->getName(); ?></h2>

<?php 
$itemPackages = $item->getChildItems();
foreach($itemPackages as $itemPackage):
    $subitem = $itemPackage->getSubItem(); ?>
    <h3>
        <?php echo $subitem->getName(); ?>
        <?php if(count($subitem->getItemVariants()) > 0): ?>
        (
        <?php 
        $numVariants = count($subitem->getItemVariants()); 
        $i = 0;
        $variants = array();
        ?>
        <?php foreach($subitem->getItemVariants() as $variant): 
            echo $variant->getName().': '.$variant->getValue(); 
            if(++$i != $numVariants):
                echo '; ';
            endif;
        endforeach; ?>
        )
        <?php endif; ?>
    </h3>
<?php endforeach; ?>