<?php 
$order = $package->getOrder();
$participant = $package->getParticipant();
$title = 'Change Package for '.$participant->getFirstname().' '.$participant->getSurname();
$this->headTitle($title);
?>
<a href="<?php echo $this->url('admin/order', array('action' => 'detail', 'id' => $order->getId())); ?>">back to order detail</a>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

