<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Change Order: '.$order->getCode()->getValue();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>


<?php
    $form = $this->form;
    $form->setAttribute(
            'action', 
            $this->url('admin/order', array(
                'action' => 'change-payment-type',
                'id' => $order->getId(),
            )));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div>
    <?php if(count($paymenttypes) <= 0): ?>
        <h2>There are currently no payment types available</h2>
        <p>There are currently no payment options available. Please check back at a later date. Sorry!</p>
    <?php else: ?>
        <h2>Choose Payment type</h2>
        <?php echo $this->formElementErrors($form->get('paymenttype_id')); ?>
        <?php foreach($paymenttypes as $paymenttype): ?>
            <div class="row">
                <div class="col-lg-6 col-bordered col-payment">
                    <?php if($order->getPaymentType() != null && $order->getPaymentType()->getId() == $paymenttype->getId()) :
                        $checked = true;
                    else:
                        $checked = false;
                    endif; ?>
                    <label class="payment-type">
                    <input style="display: inline;" <?php echo $checked ? 'checked="checked"' : ''; ?> type='radio' name='paymenttype_id' value='<?php echo $paymenttype->getId(); ?>' /> 
                    <?php echo $paymenttype->getName(); ?>
                    </label>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<div class="checkout">
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
    <?php echo $this->formHidden($form->get('csrf')); ?>
</div>
<?php echo $this->form()->closeTag(); ?>