<?php

$title = 'Order Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Code</th>
        <th>Date</th>
        <th>Buyer</th>
        <th>Payment type</th>
        <th>Price</th>
        <th>Status</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($orders as $order) : ?>
    <?php $status = 'undefined';
    if($order->getStatus()->getValue() == 'paid'):
        $status = 'paid';
    elseif($order->getStatus()->getValue() != 'ordered'):
        $status = 'unpaid';
    endif; ?>
    <tr>
        <td><?php echo $order->getCode()->getValue(); ?></td>
        <td><?php echo $order->getCreated()->format('d.m.Y H:i:s'); ?></td>
        <td>
            <?php 
            if($order->getBuyer()):
                echo $order->getBuyer()->getFirstname().' '.$order->getBuyer()->getSurname();     
            ?>
            <br />
            <a href="mailto:<?php echo $order->getBuyer()->getEmail(); ?>"><?php echo $order->getBuyer()->getEmail(); ?></a>
            <?php else:
                echo "no buyer could be found";
            endif;
            ?>
        </td>
        <td>
            <?php 
            if($order->getPaymentType()):
                echo $order->getPaymentType()->getName();
            else:
                echo "no payment type could be found";
            endif;
            ?>
        </td>
        <td>
            <?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?>
        </td>
        <td>
            <?php echo $order->getPaymentStatus(); ?>
        </td>
        <td>
            <a href="<?php echo $this->url('admin/order', array('action' => 'detail', 'id' => $order->getId()));?>"><?php echo $this->translate('Detail'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>