<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Order Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Code</th>
        <th>Date</th>
        <th>Purchaser</th>
        <th>Price</th>
        <th>Status</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($orders as $order) : ?>
    <?php $status = 'undefined';
    if($order->findOrderStatus('paid')->getValue() != ''):
        $status = 'paid';
    elseif($order->findOrderStatus('unpaid')->getValue() != ''):
        $status = 'unpaid';
    endif; ?>
    <tr>
        <td><?php echo $order->getCode()->getValue(); ?></td>
        <td><?php echo $order->getCreated()->format('d.m.Y H:i:s'); ?></td>
        <td>
            <?php echo $order->getPurchaser()->getFirstname().' '.$order->getPurchaser()->getSurname(); ?>
            <br />
            <a href="mailto:<?php echo $order->getPurchaser()->getEmail(); ?>"><?php echo $order->getPurchaser()->getEmail(); ?></a>
        </td>
        <td>
            <?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?>
        </td>
        <td>
            <?php echo $status; ?>
        </td>
        <td>
            <a href="<?php echo $this->url('admin/order', array('action'=>'detail', 'id' => $order->getId()));?>"><?php echo $this->translate('Detail'); ?></a>
            <!--<a href="<?php echo $this->url('admin/order', array('action'=>'edit', 'id' => $order->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
            <a href="<?php echo $this->url('admin/order', array('action'=>'delete', 'id' => $order->getId()));?>"><?php echo $this->translate('Delete'); ?></a>-->
        </td>
    </tr>
<?php endforeach; ?>
</table>