<?php

$title = 'Order Overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-md-12">
        <h2>active orders</h2>
        <?php foreach($activeOrders as $order): ?>
            <div class="panel panel-default">
                <div class="panel-heading"><?php echo $order->getCode()->getValue(); ?></div>
                <div class="panel-body">
                    price: <?php echo $order->getSum(); ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>