<?php

$title = 'Search Order';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-md-8 col-md-offset-2 col-lg-7 col-md-offset-3">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('admin/order', 
                array('action' => 'search')
                #array('query' => $params)
                ));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('q'));
        echo $this->formHidden($form->get('csrf'));
        echo $this->formSubmit($form->get('submit')); 
        echo $this->form()->closeTag(); ?>
    </div>
</div>
    
<?php if(count($result) > 0): ?>
<table class="table">
    <tr>
        <th>Code</th>
        <th>Date</th>
        <th>Buyer</th>
        <th>Payment type</th>
        <th>Price</th>
        <th>Status</th>
        <th></th>
    </tr>
    <?php foreach($result as $order): ?>
    <tr>
        <td><?php echo $order->getCode()->getValue(); ?></td>
        <td><?php echo $order->getCreated()->format('d.m.Y H:i:s'); ?></td>
        <td>
            <?php echo $order->getBuyer()->getFirstname().' '.$order->getBuyer()->getSurname(); ?>
            <br />
            <a href="mailto:<?php echo $order->getBuyer()->getEmail(); ?>"><?php echo $order->getBuyer()->getEmail(); ?></a>
        </td>
        <td>
            <?php echo $order->getPaymentType()->getName(); ?>
        </td>
        <td>
            <?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?>
        </td>
        <td>
            <?php echo $order->getPaymentStatus(); ?>
        </td>
        <td>
            <a href="<?php echo $this->url('admin/order', array('action' => 'detail', 'id' => $order->getId()));?>"><?php echo $this->translate('Detail'); ?></a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>
