<?php

$title = 'Add bank account';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/bankaccount', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('virtual'));
echo $this->formRow($form->get('type'));
/*echo $this->formRow($form->get('bank'));
echo $this->formRow($form->get('iban'));
echo $this->formRow($form->get('bic'));*/
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/bankaccount');?>">Cancel</a>
<?php
echo $this->form()->closeTag();