<?php

$title = 'Delete bank account csv including all bank statements';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if($csv->hasMatch()): ?>
<div class="alert alert-warning">
    <h3>Warning</h3>
    <p>This CSV cannot be deleted since there are already matches for bank 
        statements of this csv.</p>
</div>
<?php else: ?>
<p>Are you sure that you want to delete bank account csv
    <strong><?php echo $csv->getCsvFile(); ?></strong>?
</p>
<?php
$url = $this->url('admin/bankaccount', array(
    'action' => 'delete-upload',
    'id'     => $csv->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $csv->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/bankaccount');?>">Cancel</a>
</div>
</form>
<?php endif; ?>