<?php

$title = 'Bankaccount Format';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/bankaccount',
    array(
        'action' => 'format',
        'id'     => $bankaccount->getId(),
    )
));
$form->prepare(); ?>

<?php 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

echo $this->formRow($form->get('amount'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('date'));
echo $this->formRow($form->get('matchKey'));

echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit')); ?>
<a href="<?php echo $this->url('admin/bankaccount');?>">Cancel</a>
<div class="row">
    <table class="table">
        <tr>
            <th class="text-nowrap">Column 1</th>
            <th class="text-nowrap">Column 2</th>
            <th class="text-nowrap">Column 3</th>
            <th class="text-nowrap">Column 4</th>
            <th class="text-nowrap">Column 5</th>
            <th class="text-nowrap">Column 6</th>
            <th class="text-nowrap">Column 7</th>
            <th class="text-nowrap">Column 8</th>
            <th class="text-nowrap">Column 9</th>
            <th class="text-nowrap">Column 10</th>
        </tr>
    <?php foreach ($statements as $statement) : ?>
        <tr>
            <td><?php echo $statement->getBankStatementcol1(); ?></td>
            <td><?php echo $statement->getBankStatementcol2(); ?></td>
            <td><?php echo $statement->getBankStatementcol3(); ?></td>
            <td><?php echo $statement->getBankStatementcol4(); ?></td>
            <td><?php echo $statement->getBankStatementcol5(); ?></td>
            <td><?php echo $statement->getBankStatementcol6(); ?></td>
            <td><?php echo $statement->getBankStatementcol7(); ?></td>
            <td><?php echo $statement->getBankStatementcol8(); ?></td>
            <td><?php echo $statement->getBankStatementcol9(); ?></td>
            <td><?php echo $statement->getBankStatementcol10(); ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>
<?php echo $this->form()->closeTag(); ?>