<?php

$title = 'Bankaccount Format';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/bankaccount',
    array(
        'action' => 'format',
        'id'     => $bankaccount->getId(),
    )
));
$form->prepare(); ?>

<?php 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

echo $this->formRow($form->get('amount'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('date'));
echo $this->formRow($form->get('matchKey')); ?>
<div class='row'>
    <div class='col-xs-6'>
        <?php echo $this->formRow($form->get('sign')); ?>
    </div>
    <div class='col-xs-6'>
        <?php echo $this->formRow($form->get('sign-value')); ?>
    </div>
</div>

<?php echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit')); ?>
<a href="<?php echo $this->url('admin/bankaccount');?>">Cancel</a>
<div class="row">
    <table class="table">
        <tr>
            <?php for($i=1; $i<=$colCount; $i++): ?>
            <th class="text-nowrap">Column <?php echo $i; ?></th>
            <?php endfor; ?>
        </tr>
    <?php foreach ($statements as $statement) : ?>
        <tr>
            <?php foreach($statement->getBankStatementCols() as $col): ?>
            <td><?php echo $col->getValue(); ?></td>
            <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </table>
</div>
<?php echo $this->form()->closeTag(); ?>