<?php

$participant = $package->getParticipant();
$title = 'Download E-Ticket for '.$participant->getFirstname().' '.$participant->getSurname().' ('.$package->getCode()->getValue().')';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/package',
    array(
        'action' => 'download-eticket',
        'id'     => $package->getId(),
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
#echo $this->formRow($form->get('language'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Back</a>
<?php
echo $this->form()->closeTag();