<?php
$participant = $package->getParticipant();
$title = 'Recalculate prices for package of '.$participant->getFirstname().' '.$participant->getSurname();
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="alert alert-warning">
    Only items which are not in state <strong>cancelled</strong> will be recalculated.
</div>
<div class="row">
    <div class="col-md-6"><h2>Item before</h2></div>
    <div class="col-md-6"><h2>Item after</h2></div>
</div>
<hr>
<?php foreach($itemArray as $items): ?>
    <div class="row">
        <div class="col-md-6">
            <?php echo $this->partial('partial/package-recalculate-item.phtml', array('item' => $items['before'])); ?>
        </div>
        <div class="col-md-6">
            <?php if(is_object($items['after'])):
                echo $this->partial('partial/package-recalculate-item.phtml', array('item' => $items['after']));
            else: ?>
            <h4>This item will stay as is.</h4>
            <?php endif; ?>
        </div>
    </div>
    <hr>
<?php endforeach; ?>

<p>Do you really want to <strong>recalculate</strong> this package <?php echo $package->getCode()->getValue(); ?>?</p>
<?php
$url = $this->url('admin/package', array(
    'action' => 'recalculate',
    'id'     => $package->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $package->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-warning" id="submitbutton" />
    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
</div>
</form>