<?php
$participant = $package->getParticipant();
$title = 'Send out e-ticket for '.$participant->getFirstname().' '.$participant->getSurname().' package '.$package->getCode()->getValue();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<p>Do you really want to send out the e-ticket for <strong><?php echo $participant->getFirstname().' '.$participant->getSurname(); ?></strong> for the package <?php echo $package->getCode()->getValue(); ?>?</p>
<?php
$url = $this->url('admin/package', array(
    'action' => 'send-eticket',
    'id'     => $package->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $package->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-warning" id="submitbutton" />
    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
</div>
</form>