<?php

$title = 'Add Product Variant for '.$product->getName();
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/product-variant',
    array(
        'action' => 'add',
        'id'     => $this->product->getId(),
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('statsname'));
echo $this->formRow($form->get('type'));
echo $this->formRow($form->get('preselection'));
echo $this->formRow($form->get('product_id'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
<?php
echo $this->form()->closeTag();