<?php
// module/Admin/view/admin/product-group/delete.phtml:

$title = 'Delete Product Variant';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete product group
    <strong><?php echo $this->escapeHtml($productvariant->name); ?></strong>?
</p>
<?php
$url = $this->url('admin/product-variant', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $productvariant->id; ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/product');?>">Cancel</a>
</div>
</form>