<?php

$title = $productvariant->getName();
$this->headTitle($title);
?>
<a href="<?php echo $this->url('admin/product');?>">Back to Overview</a>
<h1>
    <?php echo $this->escapeHtml($title); ?>
    <span style="font-size: 14px;">
        <a href="<?php echo $this->url('admin/product-variant', array('action'=>'edit', 'id' => $productvariant->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
        <a href="<?php echo $this->url('admin/product-variant', array('action'=>'copy', 'id' => $productvariant->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
        <a href="<?php echo $this->url('admin/product-variant', array('action'=>'delete', 'id' => $productvariant->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
    </span>
</h1>
<div>
    <p>Product_id: <?php echo $productvariant->getId(); ?></p>
    <p>order: <?php echo $productvariant->getOrder(); ?></p>
    <p>type: <?php echo $productvariant->getType(); ?></p>
</div>
<div>
    <h2>
        Product Variant Values
        <span style="font-size: 14px;">
            <a href="<?php echo $this->url('admin/product-variant-value', array('action' => 'add', 'id' => $productvariant->getId())); ?>"><?php echo $this->translate('Add'); ?></a>
        </span>
    </h2>
    <?php foreach($productvariant->getProductVariantValues() as $value): ?>
        <div>
            <h3>
                <?php echo $value->getValue(); ?>
                <span style="font-size: 14px;">
                    <a href="<?php echo $this->url('admin/product-variant-value', array('action'=>'edit', 'id' => $value->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
                    <a href="<?php echo $this->url('admin/product-variant-value', array('action'=>'copy', 'id' => $value->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
                    <a href="<?php echo $this->url('admin/product-variant-value', array('action'=>'delete', 'id' => $value->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
                </span>
            </h3>
        </div>
    <?php endforeach; ?>
</div>