<?php

$title = _('My Packages');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div>
    <table>
        <tr>
            <td><?php echo _('Firstname:'); ?></td>
            <td><?php echo $user->getFirstname(); ?></td>
        </tr>
        <tr>
            <td><?php echo _('Surname:'); ?></td>
            <td><?php echo $user->getSurname(); ?></td>
        </tr>
        <tr>
            <td><?php echo _('E-Mail:'); ?></td>
            <td><?php echo $user->getEmail(); ?></td>
        </tr>
        <tr>
            <td><?php echo _('Birthdate:'); ?></td>
            <td><?php echo $user->getBirthday(); ?></td>
        </tr>
    </table>
</div>
