<?php

if($order == null) :
$title = 'Unable to find payment information';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>The system was not able to find the according order for this payment info 
        page. With your purchase you got an email with all needed data. Please 
        use the link in there.</p>
</div>
<?php 
else:

$title = 'Pay via Bank Transfer';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <?php echo $this->partial('partial/banktransfer-info.phtml', array('order' => $order)); ?>

    <p>We've sent this information to your email address: <strong><?php echo $order->getBuyer()->getEmail(); ?></strong></p>

    <p>
        You can request this information again, by simply bookmarking
        <a href="<?php echo $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey())); ?>">this link</a>,
        or have a look at the email we've sent you.
    </p>

    <p class="orange"><strong>Thanks for registering, see you in Almere!</strong></p>
</div>
<?php endif;