<?php

if($order == null) :
$title = 'Unable to find payment information';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>The system was not able to find the according order for this payment info 
        page. With your purchase you got an email with all needed data. Please 
        use the link in there.</p>
</div>
<?php 
else:

$title = 'Pay via Cheque';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    
    <div>
        <p>​Please make cheques payable to: <strong>European Juggling Association</strong>.</p>
        <p>Your order amount in GBP is: <strong>
            <?php
            $pound = ($order->getSum()*0.8);
            echo $this->currencyFormat($pound, 'GBP', null, 'en_GB');
            ?>
                </strong></p>
        <p>Please send:</p>
        <ul>
            <li>Cheques (amount in GBP, price calculated from Euro-price * 0,8 )</li>
            <li>your name</li>
            <li>order ID <?php echo $order->getCode()->getValue(); ?></li>
            <li>to the address of the UK country-rep:
                <pre style="width: 200px;">Ron Trickett
14 Peterborough Road
Newton Hall
Durham
DH1 5QX</pre>                
            </li>
        </ul>
    </div>
    <div>
        <p>We sent this information to your email address: <strong><?php echo $order->getBuyer()->getEmail(); ?></strong></p>
        <h3>You can request <a href="<?php echo $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey())); ?>">this information</a> again</h3>
        <p>Simply bookmark <a href="<?php echo $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey())); ?>">this link</a> or have a look at the mail we sent you.</p>
    </div>
    <div>
        <!--<h2>The official EJC 2015 T-Shirt</h2>
        <p>... and other awesome merchandise-products will soon be available for pre-ordering! We'll let you know as soon as the merchandise-webshop is open.</p>-->
        <h2>Official EJC-T-Shirt</h2>
        <p>... and other aweseome EJC merchandising products now for sale at
            <a href="http://www.stikkma.de/EJC-2015">http://www.stikkma.de/EJC-2015</a></p>
    </div>
</div>
<?php endif;