<?php

if($order == null) :
$title = 'Unable to find payment information';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>The system was not able to find the according order for this payment info 
        page. With your purchase you got an email with all needed data. Please 
        use the link in there.</p>
</div>
<?php 
else:

$title = 'Pay via Cheque';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    
    <div>
        <h2>Give your check to Ron.</h2>
    </div>
    <div>
        <p>We sent this information to your email address: <strong><?php echo $order->getPurchaser()->getEmail(); ?></strong></p>
        <h3>You can request <a href="<?php echo $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey())); ?>">this information</a> again</h3>
        <p>Simply bookmark <a href="<?php echo $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey())); ?>">this link</a> or have a look at the mail we sent you.</p>
    </div>
    <div>
        <h2>The official EJC 2015 T-Shirt</h2>
        <p>... and other awesome merchandise-products will soon be available for pre-ordering! We'll let you know as soon as the merchandise-webshop is open.</p>
    </div>
</div>
<?php endif;