<?php
$this->headMeta()->appendHttpEquiv('Refresh', '5;URL='.$ipayment_url);

?>
<div class="jumbotron">
    <p><?php echo $this->translate('You will be redirected to the credit card payment page within 5 seconds.'); ?></p>
    <p><?php echo $this->translate('If the redirect is not working, please follow this'); ?> <a href="<?php echo $ipayment_url; ?>"><?php echo $this->translate('link'); ?></a>.</p>
</div>