<?php
if(isset($notfound)):
    $title = 'Unable to find payment information';
    $this->headTitle($title);
?>

    <div class="jumbotron">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
        <p>The system was not able to find the according order for this payment info 
            page. With your purchase you got an email with all needed data. Please 
            use the link in there.</p>
    </div>

<?php elseif(isset($error)):
    $this->headTitle('PayPal Error');
?>

    <div class="jumbotron">
        <p class="text-danger"><i class="fa fa-warning"></i>
        <?php echo $this->escapeHtml($error); ?></p>
    </div>

<?php endif; ?>
