<?php
$this->headTitle("Pay with PayPal");

if(isset($error)):
?>

<div class="jumbotron">
    <p class="text-danger"><i class="fa fa-warning"></i> <?php echo $this->escapeHtml($error); ?></p>
</div>

<?php else:
    //$this->headMeta()->appendHttpEquiv('Refresh', '5;URL='.$paypal_url);
?>
<div class="jumbotron">
    <p>You will be redirected to PayPal within 5 seconds.</p>
    <p>If the redirect is not working, please follow this <a href="<?php echo $paypal_url; ?>">link</a>.</p>
</div>
<?php endif; ?>
