<?php

$title = 'Column Test';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-md-6 col-bordered">md-6</div>
    <div class="col-md-6 col-bordered">md-6</div>
</div>
<div class="row">
    <div class="col-sm-6 col-bordered">sm-6</div>
    <div class="col-sm-6 col-bordered">sm-6</div>
</div>
<div class="row">
    <div class="col-xs-6 col-bordered">xs-6</div>
    <div class="col-xs-6 col-bordered">xs-6</div>
</div>