<?php
$title = 'Statistics: Bank accounts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">All bank statements</div>
            <table class="table table-striped">
                <tr>
                    <th>Name</th>
                    <th class="text-right">Amount</th>
                    <th>Count</th>
                </tr>

                <?php foreach($allStats as $key => $value): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($key); ?></td>
                    <td class="text-right"><?php echo $this->currencyFormat($value['amount'], 'EUR', null, 'de_DE'); ?></td>
                    <td><?php echo $value['stmtcount']; ?></td>
                </tr>

                <?php endforeach; ?>

                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th class="text-right"><?php echo $this->currencyFormat(array_sum(array_column($allStats, 'amount')), 'EUR', null, 'de_DE'); ?></th>
                        <th><?php echo array_sum(array_column($allStats, 'stmtcount')); ?></th>
                    </tr>
                </tfoot>
            </table>
            <div class="panel-footer">Sum of all bank statements that were uploaded to the system.</div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Matched bank statements</div>
            <table class="table table-striped">
                <tr>
                    <th>Name</th>
                    <th class="text-right">Amount</th>
                    <th>Count</th>
                </tr>

                <?php foreach($matchingStats as $key => $value): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($key); ?></td>
                    <td class="text-right"><?php echo $this->currencyFormat($value['amount'], 'EUR', null, 'de_DE'); ?></td>
                    <td><?php echo $value['stmtcount']; ?></td>
                </tr>
                <?php endforeach; ?>

                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th class="text-right"><?php echo $this->currencyFormat(array_sum(array_column($matchingStats, 'amount')), 'EUR', null, 'de_DE'); ?></th>
                        <th><?php echo array_sum(array_column($matchingStats, 'stmtcount')); ?></th>
                    </tr>
                </tfoot>
            </table>
            <div class="panel-footer">Sum of all bank statements that have been matched to an order.</div>
        </div>
    </div>
</div>
