<?php
$title = 'Statistics';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<ul>
    <li><a href="<?php echo $this->url('admin/statistic', array('action' => 'orders')); ?>">Orders</a></li>
    <li><a href="<?php echo $this->url('admin/statistic', array('action' => 'participants')); ?>">Participants</a></li>
    <li><a href="<?php echo $this->url('admin/statistic', array('action' => 'bankaccounts')); ?>">Bank accounts</a></li>
</ul>
