<?php
/* pizza would be really nice */

$title = 'ERS Statistics';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">Orders</div>
            <div class="panel-body">
                <?php 
                $totalsum = 0;
                $transfersum = 0;
                $paymentfees = 0;
                foreach($orders as $order):
                    $totalsum += $order->getPrice();
                    $transfersum += $order->getSum();
                    $paymentfees += $order->getPaymentFees();
                endforeach;
                ?>
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th>count</th>
                            <th>total sum</th>
                            <th>payment fees</th>
                        </tr>
                        <tr>
                            <td><?php echo count($orders); ?></td>
                            <td><?php echo $this->currencyFormat($totalsum, 'EUR', null, 'de_DE'); ?></td>
                            <td><?php echo $this->currencyFormat($paymentfees, 'EUR', null, 'de_DE'); ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Participants</div>
            <div class="panel-body">
                <dl>
                    <dt>count</dt>
                    <dd><?php echo count($participants); ?></dd>
                </dl>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">Products</div>
            <div class="panel-body">
                <table class="table table-striped">
                    <?php foreach($products as $product): ?>
                    <tr>
                        <th><?php echo $product->getName(); ?></th>
                        <td><?php echo count($product->getItems()); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">Product Variants</div>
            <div class="panel-body">
                <?php foreach($variants as $variant): ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <?php if($variant->getStatsname() != ''):
                                echo $variant->getStatsname();
                            else:
                                echo $variant->getName();
                            endif; ?>
                        </div>
                            <table class="table table-striped">
                            <?php foreach($variant->getProductVariantValues() as $value): ?>
                                <tr>
                                    <th><?php echo $value->getValue(); ?></th>
                                    <td><?php echo $variant_stats[$variant->getId()][$value->getId()]; ?></td>
                                </tr>
                            <?php endforeach; ?>
                            </table>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">Orders by payment types</div>
            <table class="table table-striped">
                <tbody>
                    <?php foreach($paymenttypes as $paymenttype): ?>
                        <tr>
                            <th><?php echo $paymenttype->getName(); ?></th>
                            <td><?php echo count($paymenttype->getOrders()); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>