<?php
$title = 'Statistics: Participants onsite';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">onsite registrations per hour</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>hour</th>
                        <th>count</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $thisDate = '';
                    $itemSum = 0;
                    foreach($itemStats as $date => $stat): 
                        if($thisDate != $date): 
                            $thisDate = $date; ?>
                    <tr>
                        <th colspan="2"><?php echo $thisDate; ?></th>
                    </tr>
                        <?php endif; ?>
                        <?php foreach($stat as $hour => $count): ?>
                        <tr>
                            <td><?php echo $hour; ?></td>
                            <td><?php 
                            echo $count; 
                            $itemSum+=$count;
                            ?></td>
                        </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th><?php echo $itemSum; ?></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>