<?php
$title = 'orders per day';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<div id="order-chart" style="height: 250px;"></div>
<script type="text/javascript">
    new Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'order-chart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: <?php echo $chartData ?>,
        // The name of the data record attribute that contains x-values.
        xkey: 'order_date',
        // A list of names of data record attributes that contain y-values.
        ykeys: ['order_count'],
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: ['count', 'date'],
                
        xLabelAngle: 40,
    });
</script>
