<?php
$tables = array(
    array("heading" => "Orders by status", "column" => "Status", "data" => $stats_paymentStatuses),
    array("heading" => "Orders by payment type", "column" => "Payment type", "data" => $stats_paymentTypes)
);

$title = 'Statistics: Orders';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php foreach($tables as $tbl): ?>
<div class="panel panel-default">
    <div class="panel-heading"><?php echo $this->escapeHtml($tbl['heading']); ?></div>
    <table class="table table-striped">
        <tr>
            <th width="30%"><?php echo $this->escapeHtml($tbl['column']); ?></th>
            <th>Count</th>
            <th class="text-right">Total sum</th>
            <th class="text-right">Payment fees</th>
        </tr>
        <?php foreach($tbl['data'] as $value): ?>
        <tr>
            <td><?php echo $this->escapeHtml($value['label']); ?></td>
            <td><?php echo $value['ordercount']; ?></td>
            <td class="text-right">
                <?php echo $this->currencyFormat($value['totalsum'], 'EUR', null, 'de_DE'); ?>
            </td>
            <td class="text-right">
                <?php echo $this->currencyFormat($value['totalsum'] - $value['ordersum'], 'EUR', null, 'de_DE'); ?>
            </td>
        </tr>
        <?php endforeach; ?>

        <tfoot>
            <tr>
                <th>total sum</th>
                <th><?php echo array_sum(array_column($tbl['data'], 'ordercount')); ?></th>
                <th class="text-right">
                    <?php echo $this->currencyFormat(array_sum(array_column($tbl['data'], 'totalsum')), 'EUR', null, 'de_DE'); ?>
                </th>
                <th class="text-right">
                    <?php echo $this->currencyFormat(array_sum(array_column($tbl['data'], 'totalsum'))
                                                    - array_sum(array_column($tbl['data'], 'ordersum')), 'EUR', null, 'de_DE'); ?>
                </th>
            </tr>
        </tfoot>
    </table>
</div>
<?php endforeach; ?>
        

<!-- Legacy -->
<div class="panel panel-default" style="opacity: 0.75;">
    <div class="panel-heading">Overview [Legacy]</div>
    <table class="table table-striped">
        <tr>
            <th>Count</th>
            <th class="text-right">Total sum</th>
            <th class="text-right">Payment fees</th>
            <th></th>
        </tr>
        <tr>
            <td><?php echo $order_data['ordercount']; ?></td>
            <td class="text-right"><?php echo $this->currencyFormat($order_data['totalsum'], 'EUR', null, 'de_DE'); ?></td>
            <td class="text-right"><?php echo $this->currencyFormat($order_data['paymentfees'], 'EUR', null, 'de_DE'); ?></td>
            <td>(1)</td>
        </tr>
        <tr>
            <td></td>
            <td class="text-right"><?php echo $this->currencyFormat($order_data['totalsum_fast'], 'EUR', null, 'de_DE'); ?></td>
            <td class="text-right"><?php echo $this->currencyFormat($order_data['paymentfees_fast'], 'EUR', null, 'de_DE'); ?></td>
            <td>(2)</td>
        </tr>
        <tr>
            <td colspan="3"><p>Note that this information is redundant now, it is already contained in the "total sum" sections above.</p>
                <p>The two rows in this table are a comparison between a live recalculation of the sums (1) and the precomputed aggregate fields in the Order table (2).<br>
                It should be tested if those values match with up-to-date data.</p></td>
        </tr>
    </table>
</div>

<!--
TODO:
panel structure:
- Overview (current from stats/overview)
- Status (by status, currently shown here)
- by payment type
- [sth else?]
-->