<?php
$title = 'Statistics: Participants';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<p>Data about all users owning a ticket. Cancelled items or items with a pending refund are not counted in any of the statistics on this page.</p>
<hr>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Participants by agegroup (affecting price)</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>agegroup</th>
                        <th class="text-right">participant<br>count</th>
                        <th class="text-right">paid</th>
                        <th class="text-right">onsite</th>
                        <th class="text-right">
                            <span data-toggle="tooltip" title="amount of already paid and placed orders">order<br>amount</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($stats_agegroupPrice as $agegroup => $value): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($agegroup); ?></td>
                            <td class="text-right"><?php echo $value['count']; ?></td>
                            <td class="text-right"><?php echo $value['paid']; ?></td>
                            <td class="text-right"><?php echo $value['onsite']; ?></td>
                            <td class="text-right"><?php echo $this->currencyFormat($value['amount'], 'EUR', null, 'de_DE'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>

                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th class="text-right"><?php echo array_sum(array_column($stats_agegroupPrice, 'count')); ?></th>
                        <th class="text-right"><?php echo array_sum(array_column($stats_agegroupPrice, 'paid')); ?></th>
                        <th class="text-right"><?php echo array_sum(array_column($stats_agegroupPrice, 'onsite')); ?></th>
                        
                        <th class="text-right"><?php echo $this->currencyFormat(array_sum(array_column($stats_agegroupPrice, 'amount')), 'EUR', null, 'de_DE'); ?></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Participants by agegroup (affecting ticket)</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>agegroup</th>
                        <th class="text-right">participant<br>count</th>
                        <th class="text-right">paid</th>
                        <th class="text-right">onsite</th>
                        <th class="text-right">order<br>amount</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($stats_agegroupTicket as $agegroup => $value): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($agegroup); ?></td>
                        <td class="text-right"><?php echo $value['count']; ?></td>
                        <td class="text-right"><?php echo $value['paid']; ?></td>
                        <td class="text-right"><?php echo $value['onsite']; ?></td>
                        <td class="text-right"><?php echo $this->currencyFormat($value['amount'], 'EUR', null, 'de_DE'); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th class="text-right"><?php echo array_sum(array_column($stats_agegroupTicket, 'count')); ?></th>
                        <th class="text-right"><?php echo array_sum(array_column($stats_agegroupTicket, 'paid')); ?></th>
                        <th class="text-right"><?php echo array_sum(array_column($stats_agegroupTicket, 'onsite')); ?></th>
                        <th class="text-right"><?php echo $this->currencyFormat(array_sum(array_column($stats_agegroupTicket, 'amount')), 'EUR', null, 'de_DE'); ?></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Participants by product type</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>product</th>
                        <th class="text-right">participants</th>
                        <th class="text-right"><span  data-toggle="tooltip" title="Active items are items that are already paid or we are waiting for payment">active<br>items</span></th>
                        <th class="text-right">paid</th>
                        <th class="text-right">ordered</th>
                        <th class="text-right">average items<br>per participant</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($stats_productType as $value): ?>
                        <tr>
                            <td class="col-md-6"><?php echo $this->escapeHtml($value['label']); ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['usercount']) ? $value['usercount'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['itemcount']) ? $value['itemcount'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['paid']) ? $value['paid'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['ordered']) ? $value['ordered'] : 0; ?></td>
                            <td class="col-md-2 text-right"><?php echo number_format($value['itemcount'] / $value['usercount'], 3); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-danger">
            <div class="panel-heading">Participants ordered by payment type</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>product</th>
                        <th class="text-right">participants</th>
                        <th class="text-right"><span  data-toggle="tooltip" title="Active items are items that are already paid or we are waiting for payment">active<br>items</span></th>
                        <th class="text-right">paid</th>
                        <th class="text-right">ordered</th>
                        <th class="text-right">amount</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($stats_paymentType as $value): ?>
                        <tr>
                            <td class="col-md-6"><?php echo $this->escapeHtml($value['label']); ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['usercount']) ? $value['usercount'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['itemcount']) ? $value['itemcount'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['paid']) ? $value['paid'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['ordered']) ? $value['ordered'] : 0; ?></td>
                            <th class="col-md-2 text-right"><?php echo $this->currencyFormat(array_sum(array_column($stats_paymentType, 'amount')), 'EUR', null, 'de_DE'); ?></th>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-danger">
            <div class="panel-heading">Participants already matched by bankaccount</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>product</th>
                        <th class="text-right">participants</th>
                        <th class="text-right"><span  data-toggle="tooltip" title="Active items are items that are already paid or we are waiting for payment">active<br>items</span></th>
                        <th class="text-right">paid</th>
                        <th class="text-right">ordered</th>
                        <th class="text-right">amount</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($stats_paymentType as $value): ?>
                        <tr>
                            <td class="col-md-6"><?php echo $this->escapeHtml($value['label']); ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['usercount']) ? $value['usercount'] : 0;  ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['itemcount']) ? $value['itemcount'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['paid']) ? $value['paid'] : 0; ?></td>
                            <td class="col-md-1 text-right"><?php echo !empty($value['orered']) ? $value['ordered'] : 0; ?></td>
                            <th class="col-md-2 text-right"><?php echo $this->currencyFormat($value['amount'], 'EUR', null, 'de_DE'); ?></th>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Items by product variant</div>
            <div class="panel-body">
                <?php foreach($stats_productVariant as $productData): ?>
                    <div class="h3"><?php echo $this->escapeHtml($productData["productName"]) ?></div>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <?php foreach($productData["variantNames"] as $variantName) {
                                    echo '<th class="col-md-10">' . $this->escapeHtml($variantName) . '</th>';
                                } ?>
                                <th class="col-md-4 text-right">item<br>count</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($productData["variantData"] as $variantData): ?>
                                <tr>
                                    <?php foreach($variantData["variantLabels"] as $variantLabel) {
                                        echo '<td>' . $this->escapeHtml($variantLabel) . '</td>';
                                    } ?>
                                    <td class="text-right"><?php echo $variantData['itemCount']; ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <hr />
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Participants by country</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th class="col-md-10">country</th>
                        <th class="col-md-2 text-right">participant<br>count</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($stats_country as $value): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($value['name']); ?></td>
                            <td class="text-right"><?php echo $value['count']; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th class="text-right"><?php echo array_sum(array_column($stats_country, 'count')); ?></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
