<?php
$title = 'Statistics: Bank accounts';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>


<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">All <a href="#" data-toggle="tooltip" data-placement="top" data-html="true" title="Bank statements that <b>can</b> be matched to an order" data-container="body">enabled</a> bank statements</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th data-toggle="tooltip" data-placement="top" title="Name of the bank account" data-container="body">name</th>
                        <th class="text-right" data-toggle="tooltip" data-placement="top" title="Total amount of money in respective currrency" data-container="body">amount</th>
                        <th class="text-right" data-toggle="tooltip" data-placement="top" title="Number of enabled bank statements" data-container="body">count</th>
                        <th data-toggle="tooltip" data-placement="top" title="Date of the latest available bank statement" data-container="body">latest statement</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $totalSumEur = 0;
                    foreach($activeStats as $key => $value):
                        ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($key); ?></td>
                            <td class="text-right"><?php echo $this->currencyFormat($value['amount'], $value['currency'], null, 'de_DE'); ?></td>
                            <td class="text-right"><?php echo $value['stmtcount']; ?></td>
                            <td><?php echo ($value['latestentry'] ? (new DateTime($value['latestentry']))->format('d.m.Y H:i:s') : '-'); ?></td>
                        </tr>
                    <?php 
                    $totalSumEur += $value['amount'] * $value['factor'];
                    endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th class="text-right"><?php echo $this->currencyFormat($totalSumEur, 'EUR', null, 'de_DE'); ?></th>
                        <th class="text-right"><?php echo array_sum(array_column($activeStats, 'stmtcount')); ?></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
            <div class="panel-footer">
                Amount of money that has been received (but not necessarily matched) on all preregistration bank accounts, based on the latest available statements.
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">All <a href="#" data-toggle="tooltip" data-placement="top" data-html="true" title="Bank statements that <b>have already</b> been matched to an order" data-container="body">matched</a> bank statements</div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th data-toggle="tooltip" data-placement="top" title="Name of the bank account" data-container="body">name</th>
                        <th class="text-right" data-toggle="tooltip" data-placement="top" title="Total amount of money in respective currrency" data-container="body">amount</th>
                        <th class="text-right" data-toggle="tooltip" data-placement="top" title="Number of enabled bank statements" data-container="body">count</th>
                        <th data-toggle="tooltip" data-placement="top" title="Date of the latest available bank statement" data-container="body">latest statement</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $totalSumEur = 0;
                    foreach($matchingStats as $key => $value): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($key); ?></td>
                            <td class="text-right"><?php echo $this->currencyFormat($value['amount'], $value['currency'], null, 'de_DE'); ?></td>
                            <!--<td class="text-right"><?php echo $value['factor']; ?></td>//-->
                            <td class="text-right"><?php echo $value['stmtcount']; ?></td>
                            <td><?php echo ($value['latestentry'] ? (new DateTime($value['latestentry']))->format('d.m.Y H:i:s') : '-'); ?></td>
                        </tr>
                    <?php
                    $totalSumEur += $value['amount'] * $value['factor'];
                    endforeach; ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th>total sum</th>
                        <th class="text-right"><?php echo $this->currencyFormat($totalSumEur, 'EUR', null, 'de_DE'); ?></th>
                        <th class="text-right"><?php echo array_sum(array_column($matchingStats, 'stmtcount')); ?></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
            <div class="panel-footer">
                Amount of money that has already been matched with orders, based on the latest available statements.
            </div>
        </div>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">
            Conversion rates
        </h3>
    </div>
    <div class="panel-body">
        Where applicable, conversions to EUR have been performed using the following conversion rates:<br />
        <?php 
        $printed_currencies = array();
        foreach ($activeStats as $key => $value):
            if ($value['currency'] != 'EUR' && !in_array($value['currency'], $printed_currencies))
            {
                echo "1 " . $value['currency'] . " = " . $value['factor'] . " EUR<br />";
                array_push($printed_currencies, $value['currency']);
            }
        endforeach;
        ?>
    </div>
</div>
                