<html>
    <head>
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .clear-both {
                clear: both;
            }
            .small {
                font-size: 12px;
            }
            .very-small {
                font-size: 10px;
            }
            .bluetext {
                color: #5278cf;
            }
            .greytext {
                color: #888;
            }
            .initial-info {
                width: 40%;
            }
            .codes {
                position: absolute;
                top: 0px;
                right: 0px;
                text-align: center;
                width: 200px;
                border: 1px solid #eee;
            }
            .very-small p {
                margin: 2px;
                padding: 0;
            }
            .very-small h1 {
                color: #5278cf;
                font-size: 32px;
            }
            .justify {
                text-align: justify;
            }
            
            h4 {
                margin:0;
                padding:0;
                color: #85b32a;
            }
            .short-description {
                width: 350px;
            }
            .disclaimer {
                width: 350px;
                /*border: 1px solid #ddd;
                border-radius: 5px;
                padding: 1mm 2mm;*/
            }
            .agegroup {
                position: absolute;
                right: 250px;
                top: 35px;
                font-size: 48px;
                color: #85b32a;
                font-weight: bold;
            }
            
            .order {
                width: 200px;
                position: absolute;
                right: 0px;
                top: 300px;
                border: 1px solid #ddd;
                padding: 10px;
            }
            .order-description {
                padding: 0px;
                margin: 5px 0 0 0;
                font-size: 10px;
            }
            .order-value {
                padding: 0px;
                margin: 0 0 10px 0;
                font-size: 18px;
            }
            .compulsory-control {
                margin-top:80px;
            }
            .cc-option {
                font-size: 20px;
                color: #85b32a;
            }
            .ticket-heading {
                margin-left: 20px;
            }
        </style>
    </head>
    <body>
        <div class="codes">
            <img src="<?php echo $qrcode; ?>" alt="QR-Code is missing, please regenerate your e-Ticket" /><br />
            <img src="<?php echo $barcode; ?>" alt="Barcode is missing, please regenerate your e-Ticket" />
        </div>
        <h1>
            <img src="<?php echo getcwd(); ?>/pdf/img/logofinal_black_green2015_150.png" alt="EJC 2015 Bruneck" />
            <span class="ticket-heading">e-Ticket</span>
        </h1>
        <div class="agegroup">
            <span>U18</span>
        </div>
        <div class="short-description small">
            <h4>Kurzanleitung</h4>
            <p><strong>Drucke</strong> dieses Ticket aus und gib es nicht an 
                Dritte weiter. Ein Erziehungsberechtigter muss die Informationen 
                zur <strong>Aufsichtspflicht</strong> und den 
                <strong>Haftungsausschluss</strong> unterschreiben. Bringe 
                dieses Ticket zur Anmeldung mit. Falls du ohne 
                Erziehungsberechtigte teilnimmst, benötigen wir an der Anmeldung 
                außerdem eine <strong>Kopie des Personalausweises</strong> eines 
                Erziehungsberechtigten.</p>
        </div>
        <div class="disclaimer small">
            <h4>Haftungsauschluss</h4>
            <p>Bei Teilnahme an der 34ten Europäischen Jonglierconvention gilt 
                Haftungsausschluss für die Veranstalter, ihre Vertreter und 
                Erfüllungsgehilfen für Schäden jeder Art, es sei denn, sie 
                beruhen auf einer grob fahrlässigen oder vorsätzlichen 
                Pflichtverletzung der Veranstalter, ihrer Vertreter oder 
                Erfüllungsgehilfen oder auf Verletzung des Lebens, Körpers oder 
                der Gesundheit. Teilnehmer nehmen aus freiem Willen und auf 
                eigenes Risiko an der Veranstaltung teil, verantworten ihren 
                Gesundheitszustand selbst und achten auf diesen.</p>
        </div>
        <div class="order small">
            <h4>Bestellung</h4>
            <p class="order-description">Name:</p>
            <p class="order-value">Justus Jongleur</p>
            <p class="order-description">Geburtsdatum:</p>
            <p class="order-value">05.05.1955</p>
            <p class="order-description">Bestellung:</p>
            <p class="order-value">Week Ticket Adult</p>
            <p class="order-description">Galashow:</p>
            <p class="order-value">Freitag 19:00 Uhr</p>
        </div>
        <div class="compulsory-control small">
            <h4>Aufsichtspflicht: Lasse Option A oder Option B unterschreiben.</h4>
            <table>
                <tr>
                    <td><span class="cc-option">A</span></td>
                    <td colspan="2">
                        <p>Ich erlaube hiermit meinem Sohn / meiner Tochter (wie 
                        unter Bestellung eingetragen),  an der 38ten 
                        Europäischen Jonglierconvention teilzunehmen. Ich werde 
                        selbst ebenfalls teilnehmen und die Aufsichtspflicht 
                        für meinen Sohn / meine Tochter übernehmen. Ich 
                        akzeptiere den Haftungsausschluss.</p>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>Ort und Datum</td>
                    <td>Unterschrift des Erziehungsberechtigten</td>
                </tr>
                <tr>
                    <td colspan="3"><span class="cc-option">ODER:</span></td>
                </tr>
                <tr>
                    <td><span class="cc-option">B</span></td>
                    <td colspan="2">
                        <p>Ich erlaube hiermit meinem Sohn / meiner Tochter (wie 
                        unter Bestellung eingetragen), an der 38ten 
                        Europäischen Jonglierconvention teilzunehmen. Ich 
                        selbst werde nicht anwesend sein. Ich füge eine Kopie 
                        meines gültigen Personalausweises bei. Ohne dieses 
                        Ticket und die Kopie ist die Teilnahme meines Kindes an 
                        der Veranstaltung nicht möglich.</p>
                        <p>Ich akzeptiere den Haftungsausschluss.</p>

                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>Ort und Datum</td>
                    <td>Unterschrift des Erziehungsberechtigten</td>
                </tr>
            </table>
        </div>
    </body>
</html>