<?php 
    $primaryColor = $this->setting('pdf.primary-color');
    if($primaryColor == '' || substr($primaryColor,1,1) != '#') {
        $primaryColor = '#00D4F4';
    }
?>
<html>
    <head>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet"> 
        <style type="text/css">
		@font-face {
		    font-family: "FontAwesome";
		    font-weight: normal;
		    font-style : normal;
			   src : url("https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.eot?v=4.3.0");
			   src : url("https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.eot?#iefix&v=4.3.0") format("embedded-opentype"),
				 url("https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.woff2?v=4.3.0") format("woff2"),
				 url("https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.woff?v=4.3.0") format("woff"),
				 url("https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.ttf?v=4.3.0") format("truetype"),
				 url("https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.svg?v=4.3.0#fontawesomeregular") format("svg");
		}
            @page {
                margin: 0;
            }
            body {
                margin: 20px 25px 20px 60px;
                padding: 0;
                font-family: 'Open Sans';
                font-size: 12px;
            }
            strong {
                font-family: 'Open Sans';
		font-weight: 600;
            }
	    h1,h2,h3,h4,h5,h6 {
                font-family: 'Open Sans';
		font-weight: 400;
	    }
            .fa {
                font-family: FontAwesome;
		/*font-family: fontawesome-webfont;*/
            }
            .clear-both {
                clear: both;
            }
            .small {
                /*font-size: 10px;*/
                font-size: 9px;
            }
            .very-small {
                font-size: 10px;
            }
            .bluetext {
                color: #5278cf;
            }
            .greytext {
                color: #888;
            }
            .initial-info {
                width: 40%;
            }
            .very-small p {
                margin: 2px;
                padding: 0;
            }
            .very-small h1 {
                color: #5278cf;
                font-size: 32px;
            }
            .justify {
                text-align: justify;
            }
            
            .black {
                color: #000;
            }
            
            h3, h4 {
                margin:0;
                padding:0;
                color: <?php echo $primaryColor; ?>;
            }
            table {
                width: 100%;
            }
            .left-field {
                width: 455px;
            }
            .left-field h3 {
                font-size: 18px;
            }
            .short-description {
                width: 455px;
            }
            .disclaimer {
                width: 455px;
            }
            .agegroup {
                position: absolute;
                right: 250px;
                top: 10px;
                font-size: 48px;
                color: <?php echo $primaryColor; ?>;
                font-weight: bold;
            }
            .codes {
                width: 200px;
                position: absolute;
                top: 0px;
                right: 0px;
                text-align: center;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order {
                width: 200px;
                position: absolute;
                right: 0px;
                top: 240px;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order-description {
                padding: 0px;
                margin: 15px 0 0 0;
                font-size: 10px;
            }
            .additional-order-description {
                padding: 0px;
                margin: 5px 0 0 0;
                font-size: 10px;
            }
            .order-value {
                padding: 0px;
                margin: 0 0 0px 0;
                font-size: 16px;
            }
            .compulsory-control {
                margin-top:80px;
            }
            .cc-option {
                font-size: 20px;
                color: <?php echo $primaryColor; ?>;
                width: 30px;
            }
            .ticket-heading {
                font-family: 'Open Sans';
                margin-left: 20px;
                vertical-align: middle;
            }
            .logo {
                vertical-align: middle;
            }
            .day-table {
                font-size: 10px;
                width: 100%;
                margin-bottom: 10px;
            }
            .day-table td {
                text-align: center;
            }
            .sign-field {
                width: 200px;
                height: 40px;
                display: block;
                border-top: 1px solid;
                margin-top: 35px;
                padding-top: 5px;
            }
            a {
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <div class="codes">
            <img src="<?php echo $qrcode; ?>" alt="QR-Code is missing, please regenerate this E-Ticket" /><br />
            <?php /* <img src="<?php echo $barcode; ?>" alt="Barcode is missing, please regenerate this E-Ticket" /> */ ?>
        </div>
        <h1>
            <!--<img class="logo" src="<?php echo getcwd(); ?>/pdf/img/logo.png" alt="Logo" width="150" />-->
            <img class="logo" src="<?php echo getcwd(); ?>/pdf/img/logo.png" alt="Logo" height="80" />
            <span class="ticket-heading">E-Ticket</span>
        </h1>
        <?php if($agegroup): ?>
        <div class="agegroup">
            <span><?php echo $agegroup->getName(); ?></span>
        </div>
        <?php endif; ?>
        <div class="left-field">
            <?php echo $this->setting('pdf.e-ticket'); ?>
        </div>
        <?php 
        $variables = array(
            'package' => $package,
            'products' => $products,
            'items' => $items,
        );
        echo $this->partial('partial/eticket-package-overview.phtml', $variables); 
        ?>
        
        
    </body>
</html>
