<html>
    <head>
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .fa {
                font-family: FontAwesome;
            }
            .clear-both {
                clear: both;
            }
            .small {
                font-size: 12px;
            }
            .very-small {
                font-size: 10px;
            }
            .bluetext {
                color: #5278cf;
            }
            .greytext {
                color: #888;
            }
            .initial-info {
                width: 40%;
            }
            .very-small p {
                margin: 2px;
                padding: 0;
            }
            .very-small h1 {
                color: #5278cf;
                font-size: 32px;
            }
            .justify {
                text-align: justify;
            }
            
            .black {
                color: #000;
            }
            
            h3, h4 {
                margin:0;
                padding:0;
                color: #85b32a;
            }
            table {
                width: 100%;
            }
            .left-field {
                width: 485px;
            }
            .short-description {
                width: 485px;
            }
            .disclaimer {
                width: 485px;
            }
            .agegroup {
                position: absolute;
                right: 250px;
                top: 30px;
                font-size: 48px;
                color: #85b32a;
                font-weight: bold;
            }
            .codes {
                width: 200px;
                position: absolute;
                top: 0px;
                right: 0px;
                text-align: center;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order {
                width: 200px;
                position: absolute;
                right: 0px;
                top: 300px;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order-description {
                padding: 0px;
                margin: 5px 0 0 0;
                font-size: 10px;
            }
            .order-value {
                padding: 0px;
                margin: 0 0 10px 0;
                font-size: 18px;
            }
            .compulsory-control {
                margin-top:80px;
            }
            .cc-option {
                font-size: 20px;
                color: #85b32a;
                width: 30px;
            }
            .ticket-heading {
                margin-left: 20px;
            }
            .day-table {
                font-size: 10px;
                width: 100%;
            }
            .day-table td {
                text-align: center;
            }
            .sign-field {
                width: 200px;
                height: 40px;
                display: block;
                border-top: 1px solid;
                margin-top: 35px;
                padding-top: 5px;
            }
        </style>
    </head>
    <body>
        <div class="codes">
            <img src="<?php echo $qrcode; ?>" alt="QR-Code is missing, please regenerate your eTicket" /><br />
            <img src="<?php echo $barcode; ?>" alt="Barcode is missing, please regenerate your eTicket" />
        </div>
        <h1>
            <img src="<?php echo getcwd(); ?>/pdf/img/logofinal_black_green2015_150.png" alt="EJC 2015 Bruneck" width="120" />
            <span class="ticket-heading">eTicket</span>
        </h1>
        <?php if($agegroup): ?>
        <div class="agegroup">
            <span><?php echo $agegroup->getName(); ?></span>
        </div>
        <?php endif; ?>
        <div class="left-field small">
            <h3>Kurzanleitung</h3>
            <p><strong>Drucke</strong> dieses Ticket aus und gib es nicht an 
                Dritte weiter. Ein Erziehungsberechtigter muss die Informationen 
                zur <strong>Aufsichtspflicht</strong> und den 
                <strong>Haftungsausschluss</strong> unterschreiben. Bringe 
                dieses Ticket zur Anmeldung mit. Falls du ohne 
                Erziehungsberechtigte teilnimmst, benötigen wir an der Anmeldung 
                außerdem eine <strong>Kopie des Personalausweises</strong> eines 
                Erziehungsberechtigten.</p>
        </div>
        <div class="left-field small">
            <h3>Haftungsauschluss</h3>
            <p>Bei Teilnahme an der 38ten Europäischen Jonglierconvention gilt 
                Haftungsausschluss für die Veranstalter, ihre Vertreter und 
                Erfüllungsgehilfen für Schäden jeder Art, es sei denn, sie 
                beruhen auf einer grob fahrlässigen oder vorsätzlichen 
                Pflichtverletzung der Veranstalter, ihrer Vertreter oder 
                Erfüllungsgehilfen oder auf Verletzung des Lebens, Körpers oder 
                der Gesundheit. Teilnehmer nehmen aus freiem Willen und auf 
                eigenes Risiko an der Veranstaltung teil, verantworten ihren 
                Gesundheitszustand selbst und achten auf diesen.</p>
        </div>
        <div class="order small">
            <h3 class="black"><?php echo $package->getCode()->getValue(); ?></h3>
            <p class="order-description">Name:</p>
            <p class="order-value">
                <?php 
                $participant = $package->getParticipant();
                echo $participant->getFirstname().' '.$participant->getSurname(); 
                ?>
            </p>
            <p class="order-description">Geburtsdatum:</p>
            <p class="order-value">
                <?php 
                if($participant->getBirthday() != null) :
                    echo $participant->getBirthday()->format('d.m.Y'); 
                endif;
                ?>
            </p>
            <?php foreach($package->getItems() as $item): ?>
                <?php switch($item->getProductId()):
                    /*
                     * week ticket
                     */
                    case '1': ?>
                        <p class="order-description">Order:</p>
                        <p class="order-value">
                            <?php echo $item->getProduct()->getName(); ?>: <span class="fa">&#xf046;</span>
                        </p>
                        <?php break;
                    /*
                     * gala show ticket
                     */
                    case '5': ?>
                        <p class="order-description"><?php echo $item->getProduct()->getName(); ?></p>
                        <p class="order-value">
                            <?php foreach($item->getItemVariants() as $variant): ?>
                            <span><?php echo $variant->getValue(); ?></span>
                            <?php endforeach; ?>
                        </p>
                        <?php break;
                    /*
                     * day ticket
                     */
                    case '4': ?>
                        <?php break;
                    default: ?>
                        <?php break;
                endswitch; ?>
                
            <?php endforeach; ?>
            <p class="order-value">
                <table class="day-table">
                    <tr>
                        <td>Sat</td>
                        <td>Sun</td>
                        <td>Mon</td>
                        <td>Tue</td>
                        <td>Wed</td>
                        <td>Thu</td>
                        <td>Fri</td>
                        <td>Sat</td>
                        <td>Sun</td>
                    </tr>
                    <tr>
                        <td><span class="fa">&#xf046;</span></td>
                        <td><span class="fa">&#xf096;</span></td>
                        <td><span class="fa">&#xf046;</span></td>
                        <td><span class="fa">&#xf046;</span></td>
                        <td><span class="fa">&#xf046;</span></td>
                        <td><span class="fa">&#xf046;</span></td>
                        <td><span class="fa">&#xf046;</span></td>
                        <td><span class="fa">&#xf046;</span></td>
                        <td><span class="fa">&#xf046;</span></td>
                    </tr>
                </table>
            </p>
        </div>
        <div class="left-field small">
            <?php if($agegroup):
                switch($agegroup->getId()): 
                    case '3': ?>
                        <h3>Aufsichtspflicht: Lasse Option A oder Option B unterschreiben.</h3>
                        <table>
                            <tr>
                                <td><span class="cc-option">A</span></td>
                                <td colspan="2">
                                    <p>Ich erlaube hiermit meinem Sohn / meiner Tochter (wie 
                                    unter Bestellung eingetragen),  an der 38ten 
                                    Europäischen Jonglierconvention teilzunehmen. Ich werde 
                                    selbst ebenfalls teilnehmen und die Aufsichtspflicht 
                                    für meinen Sohn / meine Tochter übernehmen. Ich 
                                    akzeptiere den Haftungsausschluss.</p>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">Ort und Datum</span></td>
                                <td><span class="sign-field">Unterschrift des Erziehungsberechtigten</span></td>
                            </tr>
                            <tr>
                                <td colspan="3"><span class="cc-option">OR</span></td>
                            </tr>
                            <tr>
                                <td><span class="cc-option">B</span></td>
                                <td colspan="2">
                                    <p>Ich erlaube hiermit meinem Sohn / meiner Tochter (wie 
                                    unter Bestellung eingetragen), an der 38ten 
                                    Europäischen Jonglierconvention teilzunehmen. Ich 
                                    selbst werde nicht anwesend sein. Ich füge eine Kopie 
                                    meines gültigen Personalausweises bei. Ohne dieses 
                                    Ticket und die Kopie ist die Teilnahme meines Kindes an 
                                    der Veranstaltung nicht möglich.</p>
                                    <p>Ich akzeptiere den Haftungsausschluss.</p>

                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">Ort und Datum</span></td>
                                <td><span class="sign-field">Unterschrift des Erziehungsberechtigten</span></td>
                            </tr>
                        </table>
                        <?php break;
                    case '4': ?>
                        <h3>Aufsichtspflicht: Wähle und unterschreibe Option A oder Option B</h3>
                        <table>
                            <tr>
                                <td><span class="cc-option">A</span></td>
                                <td colspan="2">
                                    <p>Ich erlaube hiermit meinem Sohn / meiner 
                                        Tochter (wie unter Bestellung 
                                        eingetragen), an der 38ten Europäischen 
                                        Jonglierconvention teilzunehmen. Ich 
                                        werde selbst ebenfalls teilnehmen und 
                                        die Aufsichtspflicht für meinen Sohn / 
                                        meine Tochter übernehmen. Ich 
                                        akzeptiere den Haftungsausschluss.</p>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">Ort und Datum</span></td>
                                <td><span class="sign-field">Unterschrift des Erziehungsberechtigten</span></td>
                            </tr>
                            <tr>
                                <td colspan="3"><span class="cc-option">OR</span></td>
                            </tr>
                            <tr>
                                <td><span class="cc-option">B</span></td>
                                <td colspan="2">
                                    <p>Ich erlaube hiermit meinem Sohn / meiner 
                                        Tochter (wie unter Bestellung 
                                        eingetragen), an der 38ten Europäischen 
                                        Jonglierconvention teilzunehmen. Ich 
                                        übertrage die Funktion des 
                                        Erziehungsberechtigten inklusive der 
                                        Aufsichtspflicht an folgende 
                                        Begleitperson, welche volljährig (18 
                                        Jahre und älter) ist und der 
                                        Aufsichtspflicht tatsächlich nachkommen 
                                        kann. Dies sicherzustellen bleibt 
                                        Aufgabe des Erziehungsberechtigten und 
                                        wird vom Veranstalter nicht überprüft. 
                                        Ich füge eine Kopie meines gültigen 
                                        Personalausweises bei. Ohne dieses 
                                        Ticket und die Kopie ist die Teilnahme 
                                        meines Kindes an der Veranstaltung 
                                        nicht möglich.</p>
                                    <p>Ich akzeptiere den Haftungsausschluss.</p>

                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">Name der Begleitperson</span></td>
                                <td><span class="sign-field">Geburtsdatum der Begleitperson</span></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">Ort und Datum</span></td>
                                <td><span class="sign-field">Unterschrift des Erziehungsberechtigten</span></td>
                            </tr>
                        </table>
                        <?php break;
                    default:
                        echo $agegroup->getId();
                        break;
                endswitch; 
            else: ?>
                        <table>
                            <tr>
                                <td><span class="sign-field">Ort und Datum</span></td>
                                <td><span class="sign-field">Unterschrift des Erziehungsberechtigten</span></td>
                            </tr>
                        </table>
            <?php endif;?>
            
        </div>
    </body>
</html>