<!--
Test von cr: Anpassungen von (noch aktueller) Version von "./eticket_en.phtml" (14727bytes vom 7. Mai, 00:50).
E-Ticket für EJC-Teilnehmer.
23.05.: Texte aus docx-Datei geholt, Logo ersetzt, Farbe grün durch orange ersetzt.
04.06.: Schriftgröße geändert, damit alles auf 1 Seite passt.
07.06.: Logo durch bessere Variante ersetzt.
-->
<html>
    <head>
        <style type="text/css">
            @page {
                margin: 0;
            }
            body {
                margin: 20px 25px;
                padding: 0;
                font-family: 'OpenSans-Regular';
            }
            strong {
                font-family: 'OpenSans-Bold';
            }
            .fa {
                /*font-family: FontAwesome;*/
		font-family: fontawesome-webfont;
            }
            .clear-both {
                clear: both;
            }
            .small {
                /*font-size: 10px;*/
                font-size: 9px;
            }
            .very-small {
                font-size: 10px;
            }
            .bluetext {
                color: #5278cf;
            }
            .greytext {
                color: #888;
            }
            .initial-info {
                width: 40%;
            }
            .very-small p {
                margin: 2px;
                padding: 0;
            }
            .very-small h1 {
                color: #5278cf;
                font-size: 32px;
            }
            .justify {
                text-align: justify;
            }
            
            .black {
                color: #000;
            }
            
            h3, h4 {
                margin:0;
                padding:0;
                color: #f0882c;
            }
            table {
                width: 100%;
            }
            .left-field {
                width: 485px;
            }
            .short-description {
                width: 485px;
            }
            .disclaimer {
                width: 485px;
            }
            .agegroup {
                position: absolute;
                right: 250px;
                top: 10px;
                font-size: 48px;
                color: #f0882c;
                font-weight: bold;
            }
            .codes {
                width: 200px;
                position: absolute;
                top: 0px;
                right: 0px;
                text-align: center;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order {
                width: 200px;
                position: absolute;
                right: 0px;
                top: 240px;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order-description {
                padding: 0px;
                margin: 15px 0 0 0;
                font-size: 10px;
            }
            .additional-order-description {
                padding: 0px;
                margin: 5px 0 0 0;
                font-size: 10px;
            }
            .order-value {
                padding: 0px;
                margin: 0 0 0px 0;
                font-size: 16px;
            }
            .compulsory-control {
                margin-top:80px;
            }
            .cc-option {
                font-size: 20px;
                color: #f0882c;
                width: 30px;
            }
            .ticket-heading {
                margin-left: 20px;
                vertical-align: middle;
            }
            .logo {
                vertical-align: middle;
            }
            .day-table {
                font-size: 10px;
                width: 100%;
                margin-bottom: 10px;
            }
            .day-table td {
                text-align: center;
            }
            .sign-field {
                width: 200px;
                height: 40px;
                display: block;
                border-top: 1px solid;
                margin-top: 35px;
                padding-top: 5px;
            }
        </style>
    </head>
    <body>
        <div class="codes">
            <img src="<?php echo $qrcode; ?>" alt="QR-Code is missing, please regenerate this E-Ticket" /><br />
            <?php /* <img src="<?php echo $barcode; ?>" alt="Barcode is missing, please regenerate this E-Ticket" /> */ ?>
        </div>
        <h1>
            <img class="logo" src="<?php echo getcwd(); ?>/pdf/img/MuenchenCon_Logo_2016_150.png" alt="Logo" width="120" />
            <span class="ticket-heading">E-Ticket</span>
        </h1>
        <?php if($agegroup): ?>
        <div class="agegroup">
            <span><?php echo $agegroup->getName(); ?></span>
        </div>
        <?php endif; ?>
        <div class="left-field small">
            <h3>Brief instruction</h3>
            <?php if($agegroup):
                switch($agegroup->getName()):
                    case 'U6':
                    case 'U16': ?>
                        <p><strong>Dear chaperon, please print</strong> this 
                            ticket and never give it to a third person. A parent 
                            or <strong>legal guardian</strong> must add and 
                            <strong>sign</strong> the information concerning 
                            obligatory supervision and the disclaimer. 
                            <strong>Bring</strong> this ticket to the EJC and 
                            present it at the registration desk. If you are no 
                            parent or legal guardian of the child but a 
                            chaperon, we also need a <strong>copy of a valid ID 
                                card of the child’s legal guardian</strong>.</p>
                        <?php break;
                    case 'U18': ?>
                        <p><strong>Print</strong> this ticket and never give it 
                            to a third person. A parent or 
                            <strong>legal guardian must sign</strong> the 
                            information concerning obligatory supervision and 
                            the disclaimer. <strong>Bring</strong> this ticket 
                            to the EJC and present it at the registration desk. 
                            If you attend the EJC on your own, we also need a 
                            <strong>copy of your legal guardian’s ID 
                                card</strong>.</p>
                        <?php break;
                endswitch; 
            else: ?>
            <p><strong>Print</strong> this ticket and never give it to a third 
                person. <strong>Sign</strong> the disclaimer. 
                <strong>Bring</strong> this ticket together with your 
                <strong>valid ID card</strong> to the EJC and present them at 
                the registration desk.</p>
            <?php endif; ?>
        </div>
        <div class="left-field small">
            <h3>Disclaimer</h3>
            <p>Upon attending the EJC, in no event shall the host or its 
                representatives or its assistants be liable for any loss or 
                injury or any damages, unless they are grounded in cause of 
                gross negligence or wilful act of breach of duty by the host 
                or its representatives or its assistants. Participants attend by 
                choice, on their own risk; they take the responsibility for 
                their own health status and pay attention to it. We especially 
                point out that the EJC is a sports event where professional 
                jugglers and acrobats will train together with non – 
                professionals of all skill levels. There will be workshops in 
                all sorts of circus disciplines open (but maybe not 
                appropriate!) for everyone; above that props and apparatus 
                will be accessible, be it because the host provides them or any 
                participant simply puts them up and let others use them as well. 
                It is your own responsibility and neither the hosts’, nor the 
                workshop leaders’, their representatives’ or assistants’ to make 
                sure at any time that your health and fitness condition is 
                adequate to take part in the workshop in question or to use 
                props and apparatus mentioned hereinabove safely.</p>
        </div>
        <?php 
        $variables = array(
            'package' => $package,
            'products' => $products,
            'items' => $items,
        );
        echo $this->partial('partial/eticket-package-overview.phtml', $variables); 
        ?>
        <div class="left-field small">
            <?php if($agegroup):
                switch($agegroup->getName()): 
                    case 'U6':
                    case 'U16': ?>
                        <h3>Obligatory supervision: Have a parent / legal 
                            guardian sign option A or B</h3>
                        <table>
                            <tr>
                                <td><span class="cc-option">A</span></td>
                                <td colspan="2">
                                    <p>I hereby agree that my son / daughter (as stated on the right) take part at the EJC Almere from 30th of July till 7th of August 2016.</p><p>I will attend the EJC myself and therefore observe the obligatory supervision. I accept the disclaimer.</p>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">place and date</span></td>
                                <td><span class="sign-field">signature of legal guardian</span></td>
                            </tr>
                            <tr>
                                <td colspan="3"><span class="cc-option">OR</span></td>
                            </tr>
                            <tr>
                                <td><span class="cc-option">B</span></td>
                                <td colspan="2">
                                    <p>I hereby agree that my son / daughter (as stated on the right) take part at the EJC Almere from 30th of July till 7th of August 2016.</p><p>I entrust the following chaperon with the function of legal guardian and the obligatory
supervision. I guarantee that this chaperon is an adult (age of 18 or above) and has the ability to look after my son / daughter. The host will not check this. I will add a copy of a valid ID card of myself.</p> 
                                        <p>Without this document attending EJC will not be possible for my son / daughter. I accept the disclaimer.</p>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">name of chaperon</span></td>
                                <td><span class="sign-field">chaperon's date of birth</span></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">place and date</span></td>
                                <td><span class="sign-field">signature of legal guardian</span></td>
                            </tr>
                        </table>
                        <?php break;
                    case 'U18': ?>
                        <h3>Obligatory supervision: Have your parent / legal 
                            guardian sign option A or B</h3>
                        <table>
                            <tr>
                                <td><span class="cc-option">A</span></td>
                                <td colspan="2">
                                    <p>I hereby agree that my son / daughter (as stated on the right) take part at the EJC Almere from 30th of July till 7th of August 2016.</p><p>I will attend the EJC myself and therefore observe the obligatory supervision. I accept the disclaimer.</p>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">place and date</span></td>
                                <td><span class="sign-field">signature of legal guardian</span></td>
                            </tr>
                            <tr>
                                <td colspan="3"><span class="cc-option">OR</span></td>
                            </tr>
                            <tr>
                                <td><span class="cc-option">B</span></td>
                                <td colspan="2">
                                    <p>I hereby agree that my son / daughter (as stated on the right) take part at the EJC Almere from 30th of July till 7th of August 2016. I will not attend the EJC myself.</p><p>I will attach a copy of my ID card to this e-Ticket. Without this document, attending EJC will not be possible for my son / daughter. I accept the disclaimer.</p>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><span class="sign-field">place and date</span></td>
                                <td><span class="sign-field">signature of legal guardian</span></td>
                            </tr>
                        </table>
                        <?php break;
                    default:
                        echo $agegroup->getName();
                        break;
                endswitch; 
            else: ?>
                <table>
                    <tr>
                        <td><span class="sign-field">place and date</span></td>
                        <td><span class="sign-field">signature</span></td>
                    </tr>
                </table>
            <?php endif;?>
        </div>
    </body>
</html>
