<?php 
    $config = $this->config();
?>
<html>
    <head>
        <style type="text/css">
            @page {
                margin: 0;
            }
            body {
                margin: 20px 25px;
                padding: 0;
                font-family: 'OpenSans-Regular';
            }
            strong {
                font-family: 'OpenSans-Bold';
            }
            .fa {
                /*font-family: FontAwesome;*/
		font-family: fontawesome-webfont;
            }
            .clear-both {
                clear: both;
            }
            .small {
                /*font-size: 10px;*/
                font-size: 9px;
            }
            .very-small {
                font-size: 10px;
            }
            .bluetext {
                color: #5278cf;
            }
            .greytext {
                color: #888;
            }
            .initial-info {
                width: 40%;
            }
            .very-small p {
                margin: 2px;
                padding: 0;
            }
            .very-small h1 {
                color: #5278cf;
                font-size: 32px;
            }
            .justify {
                text-align: justify;
            }
            
            .black {
                color: #000;
            }
            
            h3, h4 {
                margin:0;
                padding:0;
                color: #ed1c24;
            }
            table {
                width: 100%;
            }
            .left-field {
                width: 485px;
            }
            .short-description {
                width: 485px;
            }
            .disclaimer {
                width: 485px;
            }
            .agegroup {
                position: absolute;
                right: 250px;
                top: 10px;
                font-size: 48px;
                color: #ed1c24;
                font-weight: bold;
            }
            .codes {
                width: 200px;
                position: absolute;
                top: 0px;
                right: 0px;
                text-align: center;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order {
                width: 200px;
                position: absolute;
                right: 0px;
                top: 240px;
                font-size: 100%;
                border: 1px solid #eee;
                padding: 10px;
            }
            .order-description {
                padding: 0px;
                margin: 15px 0 0 0;
                font-size: 10px;
            }
            .additional-order-description {
                padding: 0px;
                margin: 5px 0 0 0;
                font-size: 10px;
            }
            .order-value {
                padding: 0px;
                margin: 0 0 0px 0;
                font-size: 16px;
            }
            .compulsory-control {
                margin-top:80px;
            }
            .cc-option {
                font-size: 20px;
                color: #ed1c24;
                width: 30px;
            }
            .ticket-heading {
                margin-left: 20px;
                vertical-align: middle;
            }
            .logo {
                vertical-align: middle;
            }
            .day-table {
                font-size: 10px;
                width: 100%;
                margin-bottom: 10px;
            }
            .day-table td {
                text-align: center;
            }
            .sign-field {
                width: 200px;
                height: 40px;
                display: block;
                border-top: 1px solid;
                margin-top: 35px;
                padding-top: 5px;
            }
            a {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <div class="codes">
            <img src="<?php echo $qrcode; ?>" alt="QR-Code is missing, please regenerate this E-Ticket" /><br />
            <?php /* <img src="<?php echo $barcode; ?>" alt="Barcode is missing, please regenerate this E-Ticket" /> */ ?>
        </div>
        <h1>
            <img class="logo" src="<?php echo getcwd(); ?>/pdf/img/E-Ticket_logo_150.png" alt="Logo" width="150" />
            <span class="ticket-heading">E-Ticket</span>
        </h1>
        <?php if($agegroup): ?>
        <div class="agegroup">
            <span><?php echo $agegroup->getName(); ?></span>
        </div>
        <?php endif; ?>
        <div class="left-field">
            <h3><?php echo $this->translate('Brief instruction'); ?></h3>
            <p><?php printf($this->translate('This is your <strong>E-Ticket</strong> for the %s. Please bring this document with you to the event! It\'s not necessarily needed to print your E-Ticket. You can present it on any electronical device.'), $config['ERS']['name_with_year']); ?></p>
            <?php if($personalized): ?>
                <p><?php printf($this->translate('Please make sure that your data (name, firstname, date of birth) on this E-Ticket are the same as the ones on your <strong>ID card</strong> or <strong>passport</strong>. This will help us that only you can enter with your E-ticket and nobody else.')) ?></p>
            
                <?php if($agegroup):
                    switch($agegroup->getName()):
                        case 'U6':
                        case 'U16':
                        case 'U18': ?>
                <p>
                    <?php 
                    $youthFormUrl = $this->url('info', array('action' => 'forms'), array('force_canonical' => true));
                    $youthFormLink = '<a href="'.$youthFormUrl.'">'.$youthFormUrl.'</a>';
                    printf($this->translate('<strong>Do not forget: Bring a filled and signed U16/U18 form with you.</strong> This form needs to be signed by your parents or your legal guardian. Without this signed form we\'re not allowed to let you access the EJC area. You can find this form at %s.'),
                            $youthFormLink) ?>
                </p>
                            <?php break;
                    endswitch; ?>
                <?php else: ?>
                <!--<p><strong>Print</strong> this ticket and never give it to a third 
                    person. <strong>Sign</strong> the disclaimer. 
                    <strong>Bring</strong> this ticket together with your 
                    <strong>valid ID card</strong> to the EJC and present them at 
                    the registration desk.</p>-->
                <?php endif; ?>
            <?php endif; ?>
            <p><?php echo $this->translate('Best regards,'); ?><br />
                <?php echo $config['ERS']['salutation']; ?></p>
        </div>
        <?php 
        $variables = array(
            'package' => $package,
            'products' => $products,
            'items' => $items,
        );
        echo $this->partial('partial/eticket-package-overview.phtml', $variables); 
        ?>
        
        
    </body>
</html>
