<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add Agegroup';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<p>EJC takes place: <?php echo $this->setting('ers.start', 'date')->format('d.m.Y'); ?> - <?php echo $this->setting('ers.end', 'date')->format('d.m.Y'); ?></p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/agegroup', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('agegroup'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('price_change'));
echo $this->formRow($form->get('ticket_change'));
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/agegroup');?>">Cancel</a>
<?php
echo $this->form()->closeTag();
