<?php

$title = 'Delete Agegroup';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete price limit
    <strong><?php echo $agegroup->getAgegroup()->format('Y-m-d H:i:s'); ?></strong> 
    and all prices attached to it?
</p>
<?php foreach($productprices as $price): ?>
<p>
    <?php echo $price->getProduct()->getName().': ';?>
    <?php echo $this->currencyFormat($price->getCharge(), 'EUR', null, 'de_DE'); ?>
</p>
<?php endforeach; ?>
<?php
$url = $this->url('admin/agegroup', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $agegroup->getId(); ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-danger" id="submitbutton" />
    <a href="<?php echo $this->url('admin/agegroup');?>">Cancel</a>
</div>
</form>