<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Agegroup Overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>can change price <i class="fa fa-question-circle text-info" data-toggle="tooltip" title="Agegroups that can change price will be listed in the product view to be able to add a discount for these agegroups."></i></th>
        <th>can change ticket <i class="fa fa-question-circle text-info" data-toggle="tooltip" title="Agegroups that can change tickets will put their name on the top of the E-Ticket if the participants age is below the given date."></i></th>
        <th class="text-right">
            <a class="btn btn-success" href="<?php echo $this->url('admin/agegroup', array('action'=>'add'));?>"><i class="fa fa-plus"></i> Agegroup</a>
        </th>
    </tr>
<?php foreach ($agegroups as $agegroup) : ?>
    <tr>
        <td><?php echo $agegroup->getName(); ?></td>
        <td><?php echo $agegroup->getAgegroup()->format('d.m.Y'); ?></td>
        <td>
            <?php if($agegroup->getPriceChange()): ?>
            <i class="fa fa-check"></i>
            <?php else: ?>
            <i class="fa fa-close"></i>
            <?php endif; ?>
        </td>
        <td>
            <?php if($agegroup->getTicketChange()): ?>
            <i class="fa fa-check"></i>
            <?php else: ?>
            <i class="fa fa-close"></i>
            <?php endif; ?>
        </td>
        <td class="text-right">
            <a class="btn btn-default" href="<?php echo $this->url('admin/agegroup', array('action'=>'edit', 'id' => $agegroup->getId()));?>"><i class="fa fa-edit"></i></a>
            <a class="btn btn-danger" href="<?php echo $this->url('admin/agegroup', array('action'=>'delete', 'id' => $agegroup->getId()));?>"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>