<?php
// module/RegistrationSystem/view/registration-system/admin/index.phtml:

$title = 'Agegroup Overview';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/agegroup', array('action'=>'add'));?>">Add Agegroup</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>can change price</th>
        <th>&nbsp;</th>
    </tr>
<?php foreach ($agegroups as $agegroup) : ?>
    <tr>
        <td><?php echo $agegroup->getName(); ?></td>
        <td><?php echo $agegroup->getAgegroup()->format('d.m.Y'); ?></td>
        <td>
            <?php if($agegroup->getPriceChange()): ?>
            <i class="fa fa-check"></i>
            <?php else: ?>
            <i class="fa fa-close"></i>
            <?php endif; ?>
        </td>
        <td>
            <a href="<?php echo $this->url('admin/agegroup', array('action'=>'edit', 'id' => $agegroup->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
            <a href="<?php echo $this->url('admin/agegroup', array('action'=>'delete', 'id' => $agegroup->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>