<?php
$title = 'Admin';
$this->headTitle($title);
?>

<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<div class="row">
    <div class="col-md-6">
        <h2>Order search</h2>
        <?php
        $form = $this->order_search_form;
        $form->setAttribute('action', $this->url('admin/order', 
                array('action' => 'search')
                ));
        $form->prepare();

        echo $this->form()->openTag($form); ?>
        <div class="input-group input-group-lg">
            <?php echo $this->formRow($form->get('q')); ?>
            <span class="input-group-btn">
                <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
            </span>
        </div><!-- /input-group -->
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
