<?php

$this->headTitle($product->getName());
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options);?>"><?php echo $this->translate('back to Overview'); ?></a>
<h1><?php echo $this->escapeHtml($product->getName()); ?></h1>
<?php
if(count($product->getProductPrices()) == 0):
?>
<p class="desc-short">This product is unavailable</p>
<?php
else:
?>
<p class="desc-short"><?php echo $product->getShortDescription(); ?></p>
<div class="product-view">
    <div class="product-image"><img src="/img/no-available-image.png" alt="No available image" width="200"></div>
    <div class="desc-long"><?php echo $product->getLongDescription(); ?></div>
    <div class="clear-both"></div>
    <?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    
    if($product->getPersonalized() || count($participants) > 0) {
        
        echo $this->formRow($form->get('participant_id'));
        echo $this->formRow($form->get('addParticipant'));
    }
    $form->get('Product_id')->setAttribute('value', $product->getId());
    echo $this->formHidden($form->get('Product_id'));
    $prices = $product->getProductPrices();
    
    for($i = 0; $i<$form->getVariantCounter(); $i++) {
        echo $this->formHidden($form->get('variant_id_'.$i));
        echo $this->formRow($form->get('variant_value_'.$i));
        echo $this->formRow($form->get('variant_type_'.$i));
    }
    ?>
    <div class="product-price-div">
        <span class="product-price"><?php echo $this->currencyFormat($product->getPrice()->getCharge(), 'EUR', null, 'de_DE'); ?></span>
        <?php 
        if($form->get('submit')->getAttribute('disabled') == 'disabled'):
        ?>
            <div class="alert alert-warning">
                <h4>Please choose a participant</h4>
                <p>This is a personalized ticket. You have to choose a participant for whom this ticket will be valid.</p>
            </div>
        <?php
        endif;
            echo $this->formSubmit($form->get('submit'));
        ?>
    </div>
    <div class="clear-both"></div>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
<?php
endif;
?>