<?php $this->headTitle($product->getName()); ?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options);?>"><?php echo $this->translate('back to Overview'); ?></a>
<?php if($chooser): ?>
<div class="p_overlay">
    <div class="p_overlay_inner">
        <h3>
            Added <span class="green"><?php echo $product->getName(); ?></span> to your shopping cart.
        </h3>
        <div class="row">
            <div class="col-sm-6">
                <p><a class="btn btn-success" href="<?php echo $this->url('product'); ?>"><i class="fa fa-caret-left"></i> add more products</a></p>
                <p><a class="btn btn-success" href="<?php echo $this->url(
                    $bc_stay->route, 
                    $bc_stay->params, 
                    $bc_stay->options
                    ); ?>"><i class="fa fa-caret-left"></i> add this product again</a></p>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-success pull-right" href="<?php echo $this->url('order'); ?>">shopping cart <i class="fa fa-caret-right"></i></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

<?php if(count($product->getProductPrices()) == 0): ?>
    <p class="desc-short">This product is unavailable</p>
<?php else: ?>
<div class="product-view">
    <?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-lg-5" style="text-align: center; margin: 20px 0;">
            <!--<i class="fa fa-file-text-o product-icon-lg"></i>-->
            <i class="fa fa-ticket product-icon-lg"></i>
            <!--<img src="/img/no-available-image.png" alt="No available image" width="200">-->
        </div>
        <div class="col-lg-7">
            <div class="row">
                <div class="col-lg-12">
                    <h1><?php echo $this->escapeHtml($product->getName()); ?></h1>
                </div>
            </div>
            <?php if($formfail): ?>
            <div class="row">
                <div class="alert alert-danger">
                    <p>Please complete the whole form to put this product into the cart.</p>
                </div>
            </div>
            <?php endif; ?>
            <div class="row">
                <div class="col-lg-6">
                    <p class="desc-short"><?php echo $product->getShortDescription(); ?></p>
                    <?php echo $product->getLongDescription(); ?>
                </div>
                <div class="col-lg-6">
                    <p class="small text-right">The prices will increase after <?php echo $deadline->getDeadline()->format('d.m.Y H:i:s'); ?></p>
                    <dl class="dl-horizontal">
                        <?php foreach($agegroups as $ag): ?>
                        <?php 
                        #$class = '';
                        $class = 'product-price-active';
                        /*if($agegroup != null && $agegroup->getId() == $ag->getId()):
                            $class = 'product-price-active';
                        endif;*/ ?>
                        <dt class="product-price<?php echo ' '.$class ?>">
                            <?php echo $ag->getName(); ?>
                        </dt>
                        <dd class="product-price<?php echo ' '.$class ?>">
                            <?php echo $this->currencyFormat($product->getProductPrice($ag, $deadline)->getCharge(), 'EUR', null, 'de_DE'); ?>
                        </dd>
                        <?php endforeach; ?>
                        <?php 
                        #$class = '';
                        $class = 'product-price-active';
                        /*if($participant->getSessionId() == 0 || $agegroup == null):
                            $class = 'product-price-active';
                        endif;*/ ?>
                        <dt class="product-price<?php echo ' '.$class ?>">normal</dt>
                        <dd class="product-price<?php echo ' '.$class ?>">
                            <?php echo $this->currencyFormat($product->getProductPrice(null, $deadline)->getCharge(), 'EUR', null, 'de_DE'); ?>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 ui-tabs-panel ui-widget-content ui-corner-all">
                    <div id="person-detail">
                        <ul>
                            <?php if(!$product->getPersonalized()): ?>
                                <li><a href="#agegroup">Agegroup</a></li>
                            <?php endif; ?>
                            <li><a href="#person">Person</a></li>
                        </ul>
                        <?php if(!$product->getPersonalized()): ?>
                            <div id="agegroup">
                                <?php 
                                echo $this->formRow($form->get('agegroup_id')); 
                                /*
                                 * I need the empty participant_id here so the 
                                 * validator can work correctly
                                 */
                                echo $this->formHidden($form->get('participant_id'));
                                ?>
                            </div>
                        <?php endif; ?>
                        <div id="person">
                            <?php if($form->get('submit')->getAttribute('disabled') == 'disabled'): ?>
                                <div class="alert alert-warning">
                                    <h4>Please choose a person</h4>
                                    <p>This is a personalized ticket. To continue, please first 
                                        <a href="<?php echo $this->url('participant', array('action' => 'add')); ?>">add the person</a> who will use the ticket for the event.</p>
                                    <div class="clear-both"></div>
                                </div>
                            <?php 
                            else:
                                echo $this->formRow($form->get('participant_id'));
                            endif;
                            
                            /*
                             * I need the empty agegroup_id here so the 
                             * validator can work correctly
                             */
                            echo $this->formHidden($form->get('agegroup_id'));
                            ?>
                            <p><strong>Tip:</strong><br />You can 
                                <a href="<?php echo $this->url('participant', array('action' => 'add')); ?>">add a new person</a>
                                or edit the details of any person with "My Persons" from the main menu.</p>
                        </div>
                    </div>

                    <?php $form->get('Product_id')->setAttribute('value', $product->getId());
                    echo $this->formHidden($form->get('Product_id'));
                    #$prices = $product->getProductPrices();

                    /*for($i = 0; $i<$form->getVariantCounter(); $i++) {
                        echo $this->formHidden($form->get('variant_id_'.$i));
                        echo $this->formRow($form->get('variant_value_'.$i));
                        echo $this->formRow($form->get('variant_type_'.$i));
                    }*/
                    
                    foreach($product->getProductVariants() as $variant) {
                        echo $this->formRow($form->get('pv['.$variant->getId().']'));
                    }
                    ?>
                    <p class="text-right">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </p>
                </div>
                <div class="col-lg-6">
                    <?php if(count($product->getChildProducts()) > 0): ?>
                    <h3>Included Items:</h3>
                    <?php foreach($product->getChildProducts() as $package): 
                        $child = $package->getSubProduct(); ?>
                        <h4><?php echo $child->getName(); ?></h4>
                        <?php foreach($child->getProductVariants() as $variant) :
                            echo $this->formRow($form->get('pv['.$variant->getId().']'));
                        endforeach;?>
                        
                    <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
<?php endif; ?>