<?php

$title = $this->translate('Delete Item from shopping cart');
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<p>
    <?php 
    $productName = '<strong>'.$this->escapeHtml($item->getName()).'</strong>';
    if($participant == null): ?>
        <?php printf($this->translate('Are you sure that you want to delete %s?'), $productName); ?>
    <?php else: ?>
        <?php printf($this->translate('Are you sure that you want to delete %s for %s %s?'), $productName, $participant->getFirstname(), $participant->getSurname()); ?>
    <?php endif; ?>
    ?
</p>

<?php $obj = $form->getObject();
$form->setAttribute('action', $this->url('product', array('action' => 'delete', 'product_id' => $obj->getProductId(), 'item_id' => $obj->getId())))
      ->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit')); ?>

<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>"><?php echo $this->translate('Cancel'); ?></a>

<?php echo $this->form()->closeTag();
