<?php

$this->headTitle($product->getName());
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options);?>"><?php echo $this->translate('back to Overview'); ?></a>
<h1><?php echo $this->escapeHtml($product->getName()); ?></h1>
<?php if($chooser): ?>
<div class="p_overlay">
    <div class="p_overlay_inner">
        <p class="p_overlay_close">
            <span class="p_overlay_close_inner">
                <a href="<?php echo $this->url($bc_stay->route, $bc_stay->params, $bc_stay->options);?>">X</a>
            </span>
        </p>
        <h3>
            Changed <span class="green"><?php echo $product->getName(); ?></span> in your shopping cart.
        </h3>
        <div class="floatLeft">
            <a class="btn btn-default" href="<?php echo $this->url('product'); ?>">&lt; products</a>
        </div>
        <div class="floatRight">
            <a class="btn btn-primary" href="<?php echo $this->url('order'); ?>">shopping cart &gt;</a>
        </div>
        <div class="clear-both"></div>
    </div>
</div>
<?php endif; ?>
<?php
if(count($product->getProductPrices()) == 0):
?>
<p class="desc-short">This product is unavailable</p>
<?php
else:
?>
<p class="desc-short"><?php echo $product->getShortDescription(); ?></p>
<div class="product-view">
    <div class="product-image"><img src="/img/no-available-image.png" alt="No image available" width="200"></div>
    <div class="desc-long"><?php echo $product->getLongDescription(); ?></div>
    <div class="clear-both"></div>
    <?php
    $form = $this->form;
    $form->prepare();
    
    $form->get('submit')->setAttribute('value', 'save changes');

    echo $this->form()->openTag($form);
    
    if($product->getPersonalized() || count($participants) > 0) {
        echo $this->formRow($form->get('participant_id'));
    ?>
    <a href="<?php echo $this->url('participant', array('action' => 'add')); ?>">add person to this list</a>
    <?php
       #echo $this->formRow($form->get('addParticipant'));
    }
    $form->get('Product_id')->setAttribute('value', $product->getId());
    echo $this->formHidden($form->get('Product_id'));
    $prices = $product->getProductPrices();
    
    for($i = 0; $i<$form->getVariantCounter(); $i++) {
        echo $this->formHidden($form->get('variant_id_'.$i));
        echo $this->formRow($form->get('variant_value_'.$i));
        echo $this->formRow($form->get('variant_type_'.$i));
    }
    ?>
    <div class="product-price-div">
        <?php #foreach($prices as $price): ?>
        <span class="product-price"><?php echo $this->currencyFormat($product->getPrice()->getCharge(), 'EUR', null, 'de_DE'); ?></span>    
        <?php #endforeach; ?>
        <?php 
            echo $this->formSubmit($form->get('submit'));
        ?>
        <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>
    </div>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
<?php
endif;
?>