<?php $this->headTitle($product->getName()); ?>
<?php if(count($product->getProductPrices()) == 0): ?>
    <p class="desc-short"><?php echo $this->translate('This product is unavailable'); ?></p>
<?php else: ?>
<p class="desc-short"><?php echo $product->getShortDescription(); ?></p>
<div class="product-view">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->get('submit')->setAttribute('value', 'save changes'); ?>

    <div class="row">
        <div class="col-md-5" style="text-align: center; margin: 20px 0;">
            <i class="fa fa-ticket product-icon-lg"></i>
        </div>
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-12">
                    <h1><?php echo $this->escapeHtml($product->getName()); ?></h1>
                </div>
            </div>
            <?php if($formfail): ?>
            <div class="row">
                <div class="alert alert-danger">
                    <p><?php echo $this->translate('Please complete the whole form to put this product into the cart.'); ?></p>
                </div>
            </div>
            <?php endif; ?>
            <div class="row">
                <div class="col-md-6">
                    <p class="desc-short"><?php echo $product->getShortDescription(); ?></p>
                    <?php echo $product->getLongDescription(); ?>
                </div>
                <div class="col-md-6">
                    <?php if($product->getPriceCount() != 1): ?>
                        <p class="small text-right"><?php echo $this->translate('The prices will increase after'); ?><br><?php echo $deadline->getDeadline()->format('d.m.Y H:i:s T'); ?></p>
                        <p class="text-right">
                            <?php echo $this->partial('partial/currency-chooser.phtml', array('form' => $this->currencychooser())); ?>
                        </p>
                    <?php endif; ?>
                    <?php echo $this->partial('partial/product-price.phtml', array('agegroups' => $agegroups, 'deadline' => $deadline, 'product' => $product)); ?>
                </div>
            </div>
            <div class="row">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col-md-6 ui-tabs-panel ui-widget-content ui-corner-all">
                    <div id="person-detail">
                        <ul>
                            <?php # agegroup is disabled at all this year
                            if(!$product->getPersonalized() && $product->getPriceCount() != 1 && false): ?>
                                <li><a href="#agegroup"><?php echo $this->translate('Agegroup'); ?></a></li>
                            <?php endif; ?>
                            <li><a href="#person"><?php echo $this->translate('Person'); ?></a></li>
                        </ul>
                        <?php if(!$product->getPersonalized() && $product->getPriceCount() != 1 && false): ?>
                            <div id="agegroup">
                                <?php
                                echo $this->formRow($form->get('agegroup_id')); 
                                /*
                                 * I need the empty participant_id here so the 
                                 * validator can work correctly
                                 */
                                echo $this->formHidden($form->get('participant_id'));
                                ?>
                            </div>
                        <?php endif; ?>
                        <div id="person">
                            <?php if($form->get('submit')->getAttribute('disabled') == 'disabled'): ?>
                                <div class="alert alert-warning">
                                    <h4><?php echo $this->translate('Please choose a person'); ?></h4>
                                    <p><?php echo $this->translate('This is a personalized ticket. To continue, please first'); ?> 
                                        <a href="<?php echo $this->url('participant', array('action' => 'add')); ?>"><?php echo $this->translate('add the person'); ?></a> <?php echo $this->translate('who will use the ticket for the event.'); ?></p>
                                    <div class="clear-both"></div>
                                </div>
                            <?php 
                            endif;
                            echo $this->formRow($form->get('participant_id'));
                            /*
                             * I need the empty agegroup_id here so the 
                             * validator can work correctly
                             */
                            echo $this->formHidden($form->get('agegroup_id'));
                            ?>
                            <p><strong><?php echo $this->translate('Tip'); ?>:</strong><br /><?php echo $this->translate('You can'); ?> 
                                <!--<a href="<?php echo $this->url('participant', array('action' => 'add')); ?>">add a new person</a>-->
                                <a href="#" data-toggle="modal" data-target="#addParticipant"><?php echo $this->translate('add a new person'); ?></a>
                                <?php echo $this->translate('or edit the details of any person with "My Persons" from the main menu.'); ?></p>
                        </div>
                    </div>
                    
                    <?php $form->get('Product_id')->setAttribute('value', $product->getId());
                    echo $this->formHidden($form->get('Product_id'));
                    #$prices = $product->getProductPrices();

                    /*for($i = 0; $i<$form->getVariantCounter(); $i++) {
                        echo $this->formHidden($form->get('variant_id_'.$i));
                        echo $this->formRow($form->get('variant_value_'.$i));
                        echo $this->formRow($form->get('variant_type_'.$i));
                    }*/
                    foreach($product->getProductVariants() as $variant) {
                        echo $this->formRow($form->get('pv['.$variant->getId().']'));
                    }
                    ?>
                    <p class="text-right">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options);?>"><?php echo $this->translate('Cancel'); ?></a>
                    </p>
                </div>
                <div class="col-md-6">
                    <?php if(count($product->getChildProducts()) > 0): ?>
                    <h3>Included Items:</h3>
                    <?php foreach($product->getChildProducts() as $package): 
                        $child = $package->getSubProduct(); ?>
                        <h4><?php echo $child->getName(); ?></h4>
                        <?php foreach($child->getProductVariants() as $variant) :
                            echo $this->formRow($form->get('pv['.$variant->getId().']'));
                        endforeach;?>
                        
                    <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<div id="addParticipant" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Add new participant'); ?></h4>
            </div>
            <div class="modal-body">
                <?php
                $participantForm = $this->participantForm;
                $participantForm->setAttribute('action', $this->url('participant', array('action' => 'add')));
                $participantForm->prepare();

                echo $this->form()->openTag($participantForm); ?>

                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formRow($participantForm->get('firstname')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formRow($participantForm->get('surname')); ?>
                    </div>
                </div>
                <?php echo $this->formRow($participantForm->get('birthday'));
                echo $this->formRow($participantForm->get('email'));
                echo $this->formRow($participantForm->get('Country_id'));

                echo $this->formHidden($participantForm->get('csrf')); ?>
                <?php echo $this->formSubmit($participantForm->get('submit')); ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
            </div>
        </div>
    </div>
</div>
<div id="chooser" class="modal fade<?php if($chooser) { echo ' in'; } ?>" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <?php echo $this->translate('Added'); ?> <span class="color-primary"><?php echo $product->getName(); ?></span> <?php echo $this->translate('to your shopping cart.'); ?>
                </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-6">
                        <p><a class="btn btn-primary" href="<?php echo $this->url('product'); ?>"><i class="fa fa-caret-left"></i> <?php echo $this->translate('add more products'); ?></a></p>
                        <p><a class="btn btn-primary" href="<?php echo $this->url(
                            $bc_stay->route, 
                            $bc_stay->params, 
                            $bc_stay->options
                            ); ?>"><i class="fa fa-caret-left"></i> <?php echo $this->translate('add this product again'); ?></a></p>
                    </div>
                    <div class="col-sm-6">
                        <a class="btn btn-primary pull-right" href="<?php echo $this->url('order'); ?>"><?php echo $this->translate('shopping cart'); ?> <i class="fa fa-caret-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif;