<?php
// module/Catalogue/view/pre-registration/product/index.phtml:

$title = 'Tickets for EJC 2015';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
foreach ($products as $product) : 
    if(count($product->getProductPrices()) == 0):
        continue;
    endif;
?>
<div class="product-container">
    <div class="add-to-cart">
        <p class="price">
            <?php echo $this->currencyFormat($product->getPrice()->getCharge(), 'EUR', null, 'de_DE'); ?><br />
        </p>
        <p class="product-detail">
            <a href="<?php echo $this->url('product', array('action' => 'add', 'product_id' => $product->getId()));?>"><?php echo $this->translate('product detail'); ?></a>
        </p>
    </div>
    <h3><?php echo $product->getName(); ?></h3>
    <p><?php echo $product->getShortDescription(); ?></p>
    
    <?php #$NextPriceDate = \DateTime::createFromFormat('Y-m-d H:i:s', $product->getNextPrice()->validFrom); ?>
    
</div>
<hr />

<?php endforeach; ?>