<?php

$title = 'Tickets for '.$ers_config['name_with_year'];
$this->headTitle($title);
?>
<?php if($deadline): ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="row">
        <div class="col-md-6">
            <p>Click on any item to add further information and place it in your shopping cart.</p>
        </div>
        <div class="col-md-6">
            <p class="text-right">The prices will increase after<br><?php echo $deadline->getDeadline()->format('d.m.Y H:i:s T'); ?></p>
        </div>
    </div>

    <?php 
    foreach ($products as $product) : 
        if(count($product->getProductPrices()) == 0):
            continue;
        endif;
    ?>
    <a class="product-item" href="<?php echo $this->url('product', array('action' => 'add', 'product_id' => $product->getId()));?>">
        <span class="product-title"><?php echo $product->getName(); ?></span>
        <span class="product-short-description"><?php echo $product->getShortDescription(); ?></span>
        <?php if($product->getPriceCount() != 1): ?>
        <table class='table table-notbordered price-table'>
            <?php foreach($agegroups as $ag): ?>
            <tr>
                <td>
                    <span class="product-price-list product-price-active"><?php echo $ag->getName(); ?></span>
                </td>
                <td>
                    <span class="product-price-list product-price-active"><?php echo $this->currencyFormat($product->getProductPrice($ag, $deadline)->getCharge(), 'EUR', null, 'de_DE'); ?></span>
                </td>
            </tr>
            <?php endforeach; ?>
            
            <tr>
                <td>
                    <span class="product-price-list product-price-active">normal</span>
                </td>
                <td>
                    <span class="product-price-list product-price-active"><?php echo $this->currencyFormat($product->getProductPrice(null, $deadline)->getCharge(), 'EUR', null, 'de_DE'); ?></span>
                </td>
            </tr>
        </table>
        <?php else: ?>
        <table class='table table-notbordered price-table'>
            <tr>
                <td>
                    <span class="product-price-list product-price-active"><?php echo $this->currencyFormat($product->getProductPrice(null, $deadline)->getCharge(), 'EUR', null, 'de_DE'); ?></span>
                </td>
            </tr>
        </table>
        <?php endif; ?>
        <div class="clear-both"></div>
    </a>
    <hr />

    <?php endforeach;
else: ?>
    <div class="jumbotron">
        <h1>
            <?php echo $this->escapeHtml('PreReg is closed'); ?>
        </h1>
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <p>The PreReg is already closed. For more information, please visit our homepage on <a href="<?php echo $ers_config['registration_info'] ?>"><?php echo $ers_config['registration_info'] ?></a></p>
            </div>
        </div>
    </div>
<?php endif;