<?php

$this->headTitle($product->name);
?>
<a href="<?php echo $this->url('product');?>"><?php echo $this->translate('back to Overview'); ?></a>
<h1><?php echo $this->escapeHtml($product->name); ?></h1>
<?php
if(count($product->getPrices()) == 0):
?>
<p class="desc-short">This product is unavailable</p>
<?php
else:
?>
<p class="desc-short"><?php echo $product->shortDescription; ?></p>
<div class="product-view">
    <div class="product-image"><img src="/img/no-available-image.png" alt="No available image" width="200"></div>
    <div class="desc-long"><?php echo $product->longDescription; ?></div>
    <div class="clearfix"></div>
    <?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form);
    
    if($product->isPersonalized() || count($participants) > 0) {
        
        echo $this->formRow($form->get('participant_id'));
        echo $this->formRow($form->get('addParticipant'));
    }
    $form->get('Product_id')->setAttribute('value', $product->id);
    echo $this->formHidden($form->get('Product_id'));
    $price = $product->getPrice();
    
    for($i = 0; $i<$form->getVariantCounter(); $i++) {
        echo $this->formHidden($form->get('variant_id_'.$i));
        echo $this->formRow($form->get('variant_value_'.$i));
        echo $this->formRow($form->get('variant_type_'.$i));
    }
    ?>
    <div class="product-price-div">
        <span class="product-price"><?php echo $this->currencyFormat($price->charge, 'EUR', null, 'de_DE'); ?></span>    
        <?php 
            echo $this->formSubmit($form->get('submit'));
        ?>
    </div>
    <?php
    echo $this->form()->closeTag();
    ?>
</div>
<?php
endif;
?>