<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/product', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('order'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('shortDescription'));
echo $this->formRow($form->get('longDescription'));
echo $this->formRow($form->get('personalized'));
echo $this->formRow($form->get('Tax_id'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/product');?>">Cancel</a>
<?php
echo $this->form()->closeTag();