<?php

$obj = $form->getObject();
$form->setAttribute('action', $this->url('admin/product', array('action' => 'delete', 'id' => $obj->getId())))
      ->prepare();

$title = 'Delete Product';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<?php if($items != null && count($items) > 0) :?>
    <p>Product for which orders already exist can't be deleted, just disable this product.</p>
    <a href="<?php echo $this->url('admin/product');?>">Back</a>
<?php else: ?>
    <?php if(count($product->getParentProducts()) != 0 || count($product->getChildProducts()) != 0): ?>
    <?php if(count($product->getParentProducts()) != 0): ?>
        <p>Please unconnect his product from its parent products.</p>

        <ul>
        <?php foreach($product->getParentProducts() as $parent): ?>
            <li><?php echo $parent->getProduct()->getName();?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if(count($product->getChildProducts()) != 0): ?>
        <p>Please delete the child products first.</p>

        <ul>
        <?php foreach($product->getChildProducts() as $child): ?>
            <li><?php echo $child->getSubProduct()->getName();?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php else: ?>
    <p>Are you sure that you want to delete the product
        <strong><?php echo $this->escapeHtml($product->getName()); ?></strong>?
    </p>
    
    <?php echo $this->form()->openTag($form);

    echo $this->formHidden($form->get('csrf'));
    echo $this->formElement($form->get('submit')); ?>

    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>

    <?php echo $this->form()->closeTag(); ?>

    <?php endif; ?>
<?php endif;?>