<?php

$title = 'Edit Product';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'admin/product',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('active'));
echo $this->formHidden($form->get('deleted'));
echo $this->formRow($form->get('position'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('shortDescription'));
echo $this->formRow($form->get('longDescription'));
echo $this->formRow($form->get('personalized'));
echo $this->formRow($form->get('taxId'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url('admin/product');?>">Cancel</a>
<?php
echo $this->form()->closeTag();