<?php

$title = 'Product Overview';
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>
<p>
    
</p>

<table class="table">
    <tr>
        <th>pos.</th>
        <th>visible<br />in shop</th>
        <th>visible<br />on e-ticket</th>
        <th>name</th>
        <th>template for e-ticket <i class="fa fa-question-circle text-info" data-toggle="tooltip" title="Some product types can be displayed on the e-ticket via a template. If no template fits for your product request a template through an issue on github. You can find a link to the issue tracker on the bottom right of this page."></i></th>
        <!--<th>Variant</th>-->
        <th>
            <a class="btn btn-sm btn-success" href="<?php echo $this->url('admin/product', array('action'=>'add'));?>"><i class="fa fa-plus"></i> <?php echo _('product'); ?></a>
        </th>
    </tr>
<?php foreach ($products as $product) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($product->getPosition());?></td>
        <td>
            <?php if($product->getVisible()) : ?>
                <i class="fa fa-lg fa-eye"></i>
            <?php else: ?>
                <i class="fa fa-lg fa-eye-slash"></i>
            <?php endif; ?>
        </td>
        <td>
            <?php if($product->getVisibleOnEticket()) : ?>
                <i class="fa fa-lg fa-eye"></i>
            <?php else: ?>
                <i class="fa fa-lg fa-eye-slash"></i>
            <?php endif; ?>
        </td>
        <td><?php 
            if($product->getPersonalized()) : ?> 
                <!--<img src="/img/icons/32px/user.png" alt="(personalized)" title="This product needs to be linked to a user" />-->
                <i class="fa fa-lg fa-user" data-toggle="tooltip" title="This is a personalized product."></i>
            <?php endif;?>
            <?php if(count($product->getChildProducts()) > 0): ?>
                <i class="fa fa-lg fa-archive" data-toggle="tooltip" title="This product has a child product."></i>
            <?php endif; ?>
            <?php echo $this->escapeHtml($product->getName()); ?>
        </td>
        <td>
            <?php echo $product->getTicketTemplate() == '' ? 'not set' : $product->getTicketTemplate(); ?>
        </td>
        <td>
            <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/product', array('action' => 'view', 'id' => $product->getId()));?>"><i class="fa fa-search"></i></a>
            <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/product-price', array('action' => 'view', 'id' => $product->getId()));?>"><i class="fa fa-money"></i></a>
            <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/product', array('action' => 'edit', 'id' => $product->getId()));?>"><i class="fa fa-edit"></i></a>
            <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/product', array('action' => 'copy', 'id' => $product->getId()));?>"><i class="fa fa-copy"></i></a>
            <a class="btn btn-sm btn-danger" href="<?php echo $this->url('admin/product', array('action' => 'delete', 'id' => $product->getId()));?>"><i class="fa fa-trash"></i></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>