<?php

$title = $product->getName();
$this->headTitle($title);
?>
<a href="<?php echo $this->url('admin/product');?>">Back to Overview</a>
<h1>
    <?php echo $this->escapeHtml($title); ?>
    <span style="font-size: 14px;">
        <a href="<?php echo $this->url('admin/product', array('action'=>'edit', 'id' => $product->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
        <a href="<?php echo $this->url('admin/product', array('action'=>'copy', 'id' => $product->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
        <a href="<?php echo $this->url('admin/product', array('action'=>'delete', 'id' => $product->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
    </span>
</h1>
<div>
    <p>Product_id: <?php echo $product->getId(); ?></p>
    <p>order: <?php echo $product->getOrder(); ?></p>
    <p>short description: <?php echo $product->getShortDescription(); ?></p>
    <p>long description: <?php echo $product->getLongDescription(); ?></p>
    <p>is personalized: <?php if($product->isPersonalized()) : echo "yes"; else: echo "no"; endif; ?></p>
    <p>tax: <?php echo $product->getTaxId(); ?></p>
</div>
<div>
    <h2>
        Product Variants
        <span style="font-size: 14px;">
            <a href="<?php echo $this->url('admin/product-variant', array('action' => 'add', 'id' => $product->getId())); ?>"><?php echo $this->translate('Add'); ?></a>
        </span>
    </h2>
    <?php foreach($product->getVariants() as $variant): ?>
        <div>
            <h3>
                <?php echo $variant->getName(); ?>
                <span style="font-size: 14px;">
                    <a href="<?php echo $this->url('admin/product-variant', array('action'=>'edit', 'id' => $product->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
                    <a href="<?php echo $this->url('admin/product-variant', array('action'=>'copy', 'id' => $product->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
                    <a href="<?php echo $this->url('admin/product-variant', array('action'=>'delete', 'id' => $product->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
                </span>
            </h3>
            <p>order: <?php echo $variant->getOrder(); ?></p>
            <p>type: <?php echo $variant->getType(); ?></p>
        </div>
    <?php endforeach; ?>
</div>
<div>
    <h2>
        Product Prices
        <span style="font-size: 14px;">
            <a href="<?php echo $this->url('admin/product-price', array('action' => 'add', 'id' => $product->getId())); ?>"><?php echo $this->translate('Add'); ?></a>
        </span>
    </h2>
    <?php foreach($product->getPrices() as $price): ?>
        <div>
            <h3>
                <span><?php echo $this->currencyFormat($price->getCharge(), 'EUR', null, 'de_DE'); ?></span>
                <span style="font-size: 14px;">
                    <a href="<?php echo $this->url('admin/product-price', array('action'=>'edit', 'id' => $price->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
                    <a href="<?php echo $this->url('admin/product-price', array('action'=>'copy', 'id' => $price->getId()));?>"><?php echo $this->translate('Copy'); ?></a>
                    <a href="<?php echo $this->url('admin/product-price', array('action'=>'delete', 'id' => $price->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
                </span>
            </h3>
        </div>
    <?php endforeach; ?>
</div>