<?php

$title = $product->getName();
$this->headTitle($title);
?>
<h1 class="page-header">
    <?php echo $this->escapeHtml($title); ?>
    <span style="font-size: 14px;">
        <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/product', array('action'=>'edit', 'id' => $product->getId()));?>"><i class="fa fa-edit"></i></a>
        <a class="btn btn-sm btn-default" href="<?php echo $this->url('admin/product', array('action'=>'copy', 'id' => $product->getId()));?>"><i class="fa fa-copy"></i></a>
        <a class="btn btn-sm btn-danger" href="<?php echo $this->url('admin/product', array('action'=>'delete', 'id' => $product->getId()));?>"><i class="fa fa-trash"></i></a>
    </span>
</h1>
<div class="product-info-field">
    <p>Product_id: <?php echo $product->getId(); ?></p>
    <p>order: <?php echo $product->getPosition(); ?></p>
    <p>short description: <?php echo $product->getShortDescription(); ?></p>
    <p>long description: <?php echo $product->getLongDescription(); ?></p>
    <p>is personalized: <?php if($product->getPersonalized()) : echo "yes"; else: echo "no"; endif; ?></p>
    <p>tax: <?php echo $product->getTax()->getName().' '.$product->getTax()->getPercentage().'%'; ?></p>
</div>
<div class="product-info-field">
    <h2>
        Product Variants
        <span style="font-size: 14px;">
            <a href="<?php echo $this->url('admin/product-variant', array('action' => 'add', 'id' => $product->getId())); ?>"><?php echo $this->translate('Add'); ?></a>
        </span>
    </h2>
    <?php foreach($product->getProductVariants() as $variant): ?>
        <div>
            <h3>
                <?php echo $variant->getName(); ?>
                <span style="font-size: 14px;">
                    <a href="<?php echo $this->url('admin/product-variant', array('action'=>'edit', 'id' => $variant->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
                    <a href="<?php echo $this->url('admin/product-variant', array('action'=>'delete', 'id' => $variant->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
                </span>
            </h3>
            <p>order: <?php echo $variant->getPosition(); ?></p>
            <p>type: <?php echo $variant->getType(); ?></p>
            <h4>
                Values for this Variant
                <span style="font-size: 14px;">
                    <a href="<?php echo $this->url('admin/product-variant-value', array('action'=>'add', 'id' => $variant->getId()));?>"><?php echo $this->translate('Add Variant Value'); ?></a>
                </span>
            </h4>
            <table class="table">
                <tr>
                    <th>No.</th>
                    <th>Value</th>
                    <th>Visible</th>
                    <th>Disabled</th>
                    <th></th>
                </tr>
            
            <?php foreach($variant->getProductVariantValues() as $value): ?>
                <tr>
                    <td><?php echo $value->getPosition(); ?></td>
                    <td><?php echo $value->getValue(); ?></td>
                    <td>
                        <?php if($value->getVisible()): ?>
                            <i class="fa fa-eye"></i>
                        <?php else: ?>
                            <i class="fa fa-eye-slash"></i>
                        <?php endif; ?>
                    </td>
                    <td>
                        <?php if($value->getDisabled()): ?>
                            <i class="fa fa-eye-slash"></i>
                        <?php else: ?>
                            <i class="fa fa-eye"></i>
                        <?php endif; ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->url('admin/product-variant-value', array('action'=>'edit', 'id' => $value->getId()));?>"><?php echo $this->translate('Edit'); ?></a>
                        <a href="<?php echo $this->url('admin/product-variant-value', array('action'=>'delete', 'id' => $value->getId()));?>"><?php echo $this->translate('Delete'); ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </table>
        </div>
    <?php endforeach; ?>
</div>
<div class="product-info-field">
    <h2>
        Product Prices
        <span style="font-size: 14px;">
            <a href="<?php echo $this->url('admin/product-price', array('action' => 'add', 'id' => $product->getId())); ?>"><?php echo $this->translate('Add'); ?></a>
        </span>
    </h2>
    <?php echo $this->partial(
        'partial/price-matrix.phtml', 
        array(
            'agegroups' => $agegroups,
            'deadlines' => $deadlines,
            'product' => $product,
            'currencies' => $currencies,
        )
    ); ?>
</div>
<div class="product-info-field">
    <h2>
        Sub Products
        <span style="font-size: 14px;">
            <a href="<?php echo $this->url('admin/product-package', array('action' => 'add', 'id' => $product->getId())); ?>"><?php echo $this->translate('Add'); ?></a>
        </span>
    </h2>
    <?php foreach($product->getChildProducts() as $productPackage): ?>
    <?php $subproduct = $productPackage->getSubProduct(); ?>
    <h3>
        <?php echo $this->escapeHtml($subproduct->getName()); ?>
        <span style="font-size: 14px;">
            <a href="<?php echo $this->url(
                    'admin/product-package', 
                    array(
                        'action'=>'edit', 
                        'id' => $productPackage->getId(), 
                        'subproduct_id' => $subproduct->getId()
                    )
                );?>"><?php echo $this->translate('Edit'); ?></a>
            <a href="<?php echo $this->url(
                    'admin/product-package', 
                    array(
                        'action'=>'delete', 
                        'id' => $productPackage->getId()
                    )
                );?>"><?php echo $this->translate('Delete'); ?></a>
        </span>
    </h3>
    <div>
        <p>Product_id: <?php echo $subproduct->getId(); ?></p>
        <p>order: <?php echo $subproduct->getPosition(); ?></p>
        <p>short description: <?php echo $subproduct->getShortDescription(); ?></p>
        <p>long description: <?php echo $subproduct->getLongDescription(); ?></p>
        <p>is personalized: <?php if($subproduct->getPersonalized()) : echo "yes"; else: echo "no"; endif; ?></p>
    </div>
    <?php endforeach; ?>
</div>